[package]
name = "hares-physics"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
hares-types = { workspace = true }
uom = { workspace = true }
thiserror = { workspace = true }
chrono = { workspace = true }
tracing = { workspace = true }

[features]
check_invariants = []
observe = []

[dev-dependencies]
approx = "0.5"
