[package]
name = "hares-types"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[features]
check_invariants = []
observe = []

[dependencies]
serde = { workspace = true }
thiserror = { workspace = true }
chrono = { workspace = true, features = ["serde"] }
bitflags = { workspace = true, features = ["serde"] }
rand = { workspace = true }
rand_chacha = { workspace = true }
rand_distr = { workspace = true }
tracing = { workspace = true }

[dev-dependencies]
serde_json = { workspace = true }
