"""Type stubs for the HARES Rust extension module."""

from __future__ import annotations

import datetime
from collections.abc import Callable, Iterator
from typing import Any

import polars as pl

class PyControlSignal:
    @staticmethod
    def power_setpoint(
        kw: float, reactive_kvar: float | None = ...
    ) -> PyControlSignal: ...
    @staticmethod
    def thermal_setpoint(
        heat_c: float | None = ...,
        cool_c: float | None = ...,
        deadband_c: float | None = ...,
    ) -> PyControlSignal: ...
    @staticmethod
    def thermal_setpoint_delta(
        heating_delta_c: float | None = ...,
        cooling_delta_c: float | None = ...,
    ) -> PyControlSignal: ...
    @staticmethod
    def soc_target(
        target: float,
        min: float | None = ...,
        max: float | None = ...,
    ) -> PyControlSignal: ...
    @staticmethod
    def humidity_setpoint(
        target_rh: float,
        min_rh: float | None = ...,
        max_rh: float | None = ...,
    ) -> PyControlSignal: ...
    @staticmethod
    def power_limit(
        max_power_kw: float,
        ramp_rate_kw_per_s: float | None = ...,
    ) -> PyControlSignal: ...
    @staticmethod
    def duty_cycle(
        on_fraction: float,
        period_s: float | None = ...,
        component: DutyCycleComponent | None = ...,
    ) -> PyControlSignal: ...
    @staticmethod
    def grid_connect(connected: bool) -> PyControlSignal: ...
    @staticmethod
    def self_consumption(
        enabled: bool, solar_only_charging: bool
    ) -> PyControlSignal: ...
    @staticmethod
    def curtailment_percent(percent: float) -> PyControlSignal: ...
    @staticmethod
    def reactive_setpoint(kvar: float) -> PyControlSignal: ...
    @staticmethod
    def power_factor_setpoint(power_factor: float) -> PyControlSignal: ...
    @staticmethod
    def inverter_priority_mode(priority: InverterPriority) -> PyControlSignal: ...
    @staticmethod
    def protocol_native(protocol_id: int, payload: bytes) -> PyControlSignal: ...
    @staticmethod
    def ideal_capacity_mode_override(mode: str) -> PyControlSignal: ...
    @staticmethod
    def ideal_capacity(capacity_w: float) -> PyControlSignal: ...
    @staticmethod
    def load_fraction(fraction: float) -> PyControlSignal: ...
    @staticmethod
    def mode_override(mode: OperatingMode) -> PyControlSignal: ...
    @staticmethod
    def mode_override_str(mode: str) -> PyControlSignal: ...
    @staticmethod
    def demand_response(
        level: DRLevel, duration_s: float | None = ...
    ) -> PyControlSignal: ...
    @staticmethod
    def demand_response_str(
        level: str, duration_s: float | None = ...
    ) -> PyControlSignal: ...
    @classmethod
    def from_dict(cls, d: dict[str, Any]) -> PyControlSignal: ...
    def to_dict(self) -> dict[str, Any]: ...

class ControlSignal(PyControlSignal): ...

class PyTelemetry:
    def zone(self) -> dict[str, Any]: ...
    def equipment(self) -> dict[str, Any]: ...
    def total_power_kw(self) -> float: ...

class PyDwelling:
    @classmethod
    def from_hpxml(
        cls,
        hpxml: str,
        schedule: str,
        weather: str,
        *,
        start_time: str | datetime.datetime | None = ...,
        duration_s: int | float | datetime.timedelta = ...,
        time_res_s: int | float | datetime.timedelta = ...,
        defaults_path: str | None = ...,
        bldg_id: int = ...,
        master_seed: int = ...,
        output_verbosity: int = ...,
        output_path: str | None = ...,
        output_to_parquet: bool = ...,
        output_chunk_size: int = ...,
        civil_timezone: str | None = ...,
        setpoint_deadband_c: float | None = ...,
        **kwargs: Any,
    ) -> PyDwelling: ...
    def initialize(self) -> None: ...
    def timesteps(self) -> Iterator[Any]: ...
    def simulate(self) -> pl.DataFrame: ...
    def step(self) -> dict[str, Any]: ...
    def apply_control(self, name: str, signal: PyControlSignal) -> None: ...
    def set_price_signal(self, signal: dict[str, float | None]) -> None: ...
    def set_grid_voltage(self, voltage_pu: float) -> None: ...
    def telemetry(self) -> PyTelemetry: ...
    def equipment_descriptors(self) -> list[EquipmentDescriptor]: ...
    def equipment_names(self) -> list[str]: ...
    def validate_control(self, name: str, signal: PyControlSignal) -> bool: ...
    def results(self) -> pl.DataFrame: ...
    def metrics(self) -> PySimulationMetrics: ...
    def reset_with_seed(self, seed: int) -> None: ...
    def save_state(self) -> bytes: ...
    def load_state(self, state: bytes) -> None: ...
    def set_solar_override(
        self,
        data: str
        | pl.DataFrame
        | dict[int, dict[str, Any]]
        | list[list[dict[str, Any]]],
    ) -> None: ...
    def clear_solar_override(self) -> None: ...
    def has_solar_override(self) -> bool: ...
    def surface_ids(self) -> list[int]: ...
    def roof_planes(self) -> list[RoofPlane]: ...
    def pv_candidates(self) -> list[PvCandidate]: ...
    def estimate_pv_capacity(
        self,
        target_kw: float,
        min_kw: float = ...,
        max_kw: float = ...,
    ) -> PvSizingResult: ...
    @property
    def config(self) -> SimulationConfig: ...

class SimulationConfig:
    def __init__(
        self,
        start_time: str | None = ...,
        duration: int | None = ...,
        time_res: int | None = ...,
        output_verbosity: int | None = ...,
        output_path: str | None = ...,
        output_to_parquet: bool | None = ...,
        output_chunk_size: int | None = ...,
        master_seed: int | None = ...,
        civil_timezone: str | None = ...,
        setpoint_deadband_c: float | None = ...,
    ) -> None: ...
    @property
    def start_time(self) -> str: ...
    @property
    def duration(self) -> int: ...
    @property
    def time_res(self) -> int: ...
    @property
    def output_verbosity(self) -> int: ...
    @property
    def output_path(self) -> str | None: ...
    @property
    def output_to_parquet(self) -> bool: ...
    @property
    def output_chunk_size(self) -> int: ...
    @property
    def setpoint_deadband_c(self) -> float | None: ...
    @property
    def master_seed(self) -> int: ...
    @property
    def civil_timezone(self) -> str | None: ...
    def __repr__(self) -> str: ...

class DwellingConfig:
    def __init__(
        self,
        hpxml: str,
        schedule: str,
        weather: str,
        config: SimulationConfig | None = ...,
        defaults_path: str | None = ...,
        bldg_id: int | None = ...,
        initialization_duration: int | None = ...,
        resample_overrides: dict[str, str] | None = ...,
        overrides: dict[str, Any] | None = ...,
    ) -> None: ...
    @property
    def hpxml(self) -> str: ...
    @property
    def schedule(self) -> str: ...
    @property
    def weather(self) -> str: ...
    @property
    def config(self) -> SimulationConfig | None: ...
    @property
    def defaults_path(self) -> str | None: ...
    @property
    def bldg_id(self) -> int: ...
    @property
    def initialization_duration(self) -> int | None: ...
    @property
    def resample_overrides(self) -> dict[str, str] | None: ...
    @property
    def overrides(self) -> dict[str, Any] | None: ...
    def __repr__(self) -> str: ...

class PyFleet:
    @classmethod
    def from_buildings(
        cls,
        configs: list[DwellingConfig],
        sample_weights: list[float] | None = ...,
    ) -> PyFleet: ...
    @classmethod
    def from_resstock(
        cls,
        metadata_path: str,
        hpxml_dir: str,
        weather_dir: str,
        filter: dict[str, str] | None = ...,
        resstock_version: ResStockVersion | str | None = ...,
    ) -> PyFleet: ...
    def simulate(
        self,
        n_threads: int | None = ...,
        resolution: AggregationResolution | str | None = ...,
        raise_on_failure: bool | None = ...,
        progress: Callable[[int, int], None] | None = ...,
    ) -> PyFleetResults: ...
    def __len__(self) -> int: ...

class PyFleetResults:
    @property
    def per_dwelling_metrics(self) -> pl.DataFrame: ...
    @property
    def aggregate_timeseries(self) -> pl.DataFrame: ...
    @property
    def failures(self) -> list[dict[str, Any]]: ...
    @property
    def n_succeeded(self) -> int: ...
    @property
    def n_failed(self) -> int: ...

def batch_step(
    dwellings: list[PyDwelling],
    actions: list[list[float]],
    observation_fields: list[str],
) -> list[dict[str, Any]]: ...

class Battery:
    def __init__(
        self,
        name: str,
        capacity_kwh: float,
        max_charge_kw: float | None = ...,
        max_discharge_kw: float | None = ...,
    ) -> None: ...

class PV:
    def __init__(
        self, name: str, capacity_kw: float, tilt: float, azimuth: float
    ) -> None: ...

class EV:
    def __init__(
        self,
        name: str,
        capacity_kwh: float | None = ...,
        max_charging_kw: float | None = ...,
    ) -> None: ...

class RoofPlane:
    @property
    def index(self) -> int: ...
    @property
    def area_m2(self) -> float: ...
    @property
    def tilt_deg(self) -> float: ...
    @property
    def azimuth_deg(self) -> float | None: ...
    @property
    def material(self) -> str | None: ...
    @property
    def boundary_index(self) -> int | None: ...

class PvCandidate:
    @property
    def plane_idx(self) -> int: ...
    @property
    def azimuth_deg(self) -> float: ...
    @property
    def tilt_deg(self) -> float: ...
    @property
    def usable_m2(self) -> float: ...
    @property
    def max_panels(self) -> int: ...
    @property
    def max_capacity_kw(self) -> float: ...
    @property
    def solar_score(self) -> float: ...
    @property
    def boundary_index(self) -> int | None: ...

class PvSizingResult:
    @property
    def capacity_kw(self) -> float: ...
    @property
    def num_panels(self) -> int: ...
    @property
    def collector_area_m2(self) -> float: ...
    @property
    def array_azimuth_deg(self) -> float: ...
    @property
    def array_tilt_deg(self) -> float: ...
    @property
    def system_losses_fraction(self) -> float: ...
    @property
    def max_roof_capacity_kw(self) -> float: ...
    @property
    def panel_watts(self) -> int: ...

class TelemetryField:
    @property
    def name(self) -> str: ...
    @property
    def unit(self) -> str: ...
    @property
    def description(self) -> str: ...

class EquipmentDescriptor:
    @property
    def id(self) -> int: ...
    @property
    def name(self) -> str: ...
    @property
    def end_use(self) -> EndUse: ...
    @property
    def equipment_type(self) -> str: ...
    @property
    def zone(self) -> int | None: ...
    @property
    def fuel_type(self) -> FuelType: ...
    @property
    def stage(self) -> ExecutionStage: ...
    @property
    def control_capabilities(self) -> ControlCapabilities: ...
    @property
    def telemetry_fields(self) -> list[TelemetryField]: ...

class EndUse:
    Heating: EndUse
    Cooling: EndUse
    HotWater: EndUse
    Lighting: EndUse
    Cooking: EndUse
    Other: EndUse
    @staticmethod
    def heating() -> EndUse: ...
    @staticmethod
    def cooling() -> EndUse: ...
    @staticmethod
    def hot_water() -> EndUse: ...
    @staticmethod
    def lighting() -> EndUse: ...
    @staticmethod
    def cooking() -> EndUse: ...
    @staticmethod
    def other() -> EndUse: ...
    @staticmethod
    def custom(name: str) -> EndUse: ...
    @staticmethod
    def from_str(name: str) -> EndUse: ...
    @staticmethod
    def is_standard(name: str) -> bool: ...
    def as_str(self) -> str: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...

class FuelType:
    Electricity: FuelType
    NaturalGas: FuelType
    Propane: FuelType
    FuelOil: FuelType
    Wood: FuelType
    NoFuel: FuelType
    @staticmethod
    def electricity() -> FuelType: ...
    @staticmethod
    def natural_gas() -> FuelType: ...
    @staticmethod
    def propane() -> FuelType: ...
    @staticmethod
    def fuel_oil() -> FuelType: ...
    @staticmethod
    def wood() -> FuelType: ...
    @staticmethod
    def no_fuel() -> FuelType: ...
    @staticmethod
    def from_str(name: str) -> FuelType: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...

class OperatingMode:
    None_: OperatingMode
    HeatingResistance: OperatingMode
    HeatingHP: OperatingMode
    CoolingHP: OperatingMode
    HeatingHPWH: OperatingMode
    HeatingHPAndER: OperatingMode
    HeatingHPAndBackup: OperatingMode
    HeatingHPAndWH: OperatingMode
    HeatingHPAndERAndWH: OperatingMode
    HeatingHPAndBackupAndWH: OperatingMode
    HeatingHPAndERBackup: OperatingMode
    HeatingHPAndERWH: OperatingMode
    HeatingHPAndERBackupWH: OperatingMode
    HeatingHPAndBackupWH: OperatingMode
    HeatingHPWH: OperatingMode
    HeatingHPAndBackupElement: OperatingMode
    HeatingHPAndERAndBackupElement: OperatingMode
    HeatingHPAndERWH: OperatingMode
    HeatingHPAndBackupAndER: OperatingMode
    HeatingHPAndBackupAndERWH: OperatingMode
    HeatingHPAndBackupElementAndWH: OperatingMode
    HeatingHPAndERAndBackupElementAndWH: OperatingMode
    HeatingHPWh: OperatingMode
    HeatingHPAndBackupElementAndER: OperatingMode
    HeatingHPAndBackupElementAndERWH: OperatingMode
    HeatingHPAndBackupElementAndWH: OperatingMode
    HeatingHPAndER: OperatingMode
    HeatingHPAndBackup: OperatingMode
    HeatPumpWH: OperatingMode
    BackupElement: OperatingMode
    @staticmethod
    def none_() -> OperatingMode: ...
    @staticmethod
    def heating_resistance() -> OperatingMode: ...
    @staticmethod
    def heating_hp() -> OperatingMode: ...
    @staticmethod
    def cooling_hp() -> OperatingMode: ...
    @staticmethod
    def heating_hpwh() -> OperatingMode: ...
    @staticmethod
    def heating_hp_and_er() -> OperatingMode: ...
    @staticmethod
    def heating_hp_and_backup() -> OperatingMode: ...
    @staticmethod
    def heating_hp_and_wh() -> OperatingMode: ...
    @staticmethod
    def heating_hp_and_er_and_wh() -> OperatingMode: ...
    @staticmethod
    def heating_hp_and_backup_and_wh() -> OperatingMode: ...
    @staticmethod
    def heating_hp_and_er_backup() -> OperatingMode: ...
    @staticmethod
    def heating_hp_and_er_wh() -> OperatingMode: ...
    @staticmethod
    def heating_hp_and_er_backup_wh() -> OperatingMode: ...
    @staticmethod
    def heating_hp_and_backup_wh() -> OperatingMode: ...
    @staticmethod
    def heat_pump_wh() -> OperatingMode: ...
    @staticmethod
    def backup_element() -> OperatingMode: ...
    @staticmethod
    def from_str(name: str) -> OperatingMode: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...

class Mode(OperatingMode): ...

class DRLevel:
    Normal: DRLevel
    Moderate: DRLevel
    High: DRLevel
    Critical: DRLevel
    GridEmergency: DRLevel
    @staticmethod
    def normal() -> DRLevel: ...
    @staticmethod
    def moderate() -> DRLevel: ...
    @staticmethod
    def high() -> DRLevel: ...
    @staticmethod
    def critical() -> DRLevel: ...
    @staticmethod
    def grid_emergency() -> DRLevel: ...
    @staticmethod
    def from_str(name: str) -> DRLevel: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...

class ExecutionStage:
    Independent: ExecutionStage
    Electrical: ExecutionStage
    Thermal: ExecutionStage
    EnvelopeResolution: ExecutionStage
    @staticmethod
    def independent() -> ExecutionStage: ...
    @staticmethod
    def electrical() -> ExecutionStage: ...
    @staticmethod
    def thermal() -> ExecutionStage: ...
    @staticmethod
    def envelope_resolution() -> ExecutionStage: ...
    @staticmethod
    def from_str(name: str) -> ExecutionStage: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...

class FluidType:
    Water: FluidType
    Glycol: FluidType
    Refrigerant: FluidType
    @staticmethod
    def water() -> FluidType: ...
    @staticmethod
    def glycol() -> FluidType: ...
    @staticmethod
    def refrigerant() -> FluidType: ...
    @staticmethod
    def from_str(name: str) -> FluidType: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...

class InverterPriority:
    Watt: InverterPriority
    Var: InverterPriority
    Cpf: InverterPriority
    @staticmethod
    def watt() -> InverterPriority: ...
    @staticmethod
    def var() -> InverterPriority: ...
    @staticmethod
    def cpf() -> InverterPriority: ...
    @staticmethod
    def from_str(name: str) -> InverterPriority: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...

class DutyCycleComponent:
    Compressor: DutyCycleComponent
    BackupElement: DutyCycleComponent
    @staticmethod
    def compressor() -> DutyCycleComponent: ...
    @staticmethod
    def backup_element() -> DutyCycleComponent: ...
    @staticmethod
    def from_str(name: str) -> DutyCycleComponent: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...

class SimStatus:
    @staticmethod
    def ok() -> SimStatus: ...
    @staticmethod
    def flagged(message: str | None = ...) -> SimStatus: ...
    @staticmethod
    def failed(message: str | None = ...) -> SimStatus: ...
    @staticmethod
    def from_str(name: str) -> SimStatus: ...
    @property
    def message(self) -> str | None: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...

class AggregationResolution:
    FifteenMin: AggregationResolution
    Hourly: AggregationResolution
    @staticmethod
    def fifteen_min() -> AggregationResolution: ...
    @staticmethod
    def hourly() -> AggregationResolution: ...
    @staticmethod
    def from_str(name: str) -> AggregationResolution: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...

class ResStockVersion:
    V2024_1: ResStockVersion
    V2024_2: ResStockVersion
    V2025_1: ResStockVersion
    @staticmethod
    def v2024_1() -> ResStockVersion: ...
    @staticmethod
    def v2024_2() -> ResStockVersion: ...
    @staticmethod
    def v2025_1() -> ResStockVersion: ...
    @staticmethod
    def from_str(name: str) -> ResStockVersion: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...

class ControlCapabilities:
    POWER_SETPOINT: ControlCapabilities
    SOC_TARGET: ControlCapabilities
    THERMAL_SETPOINT: ControlCapabilities
    POWER_LIMIT: ControlCapabilities
    MODE_OVERRIDE: ControlCapabilities
    DUTY_CYCLE: ControlCapabilities
    LOAD_FRACTION: ControlCapabilities
    GRID_CONNECT: ControlCapabilities
    SELF_CONSUMPTION: ControlCapabilities
    DEMAND_RESPONSE: ControlCapabilities
    PROTOCOL_NATIVE: ControlCapabilities
    HUMIDITY_SETPOINT: ControlCapabilities
    CURTAILMENT_PERCENT: ControlCapabilities
    REACTIVE_SETPOINT: ControlCapabilities
    POWER_FACTOR_SETPOINT: ControlCapabilities
    INVERTER_PRIORITY_MODE: ControlCapabilities
    @staticmethod
    def from_list(names: list[str]) -> ControlCapabilities: ...
    def __or__(self, other: ControlCapabilities) -> ControlCapabilities: ...
    def __contains__(self, other: ControlCapabilities) -> bool: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...

class LutType:
    ChargingCurve: LutType
    Ocv: LutType
    UNeg: LutType
    @staticmethod
    def charging_curve() -> LutType: ...
    @staticmethod
    def ocv() -> LutType: ...
    @staticmethod
    def uneg() -> LutType: ...
    @staticmethod
    def from_str(name: str) -> LutType: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...

class BatteryChemistry:
    Nmc: BatteryChemistry
    Lfp: BatteryChemistry
    Nca: BatteryChemistry
    Lto: BatteryChemistry
    @staticmethod
    def nmc() -> BatteryChemistry: ...
    @staticmethod
    def lfp() -> BatteryChemistry: ...
    @staticmethod
    def nca() -> BatteryChemistry: ...
    @staticmethod
    def lto() -> BatteryChemistry: ...
    @staticmethod
    def from_str(name: str) -> BatteryChemistry: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...

class ChargingLevel:
    L1: ChargingLevel
    L2: ChargingLevel
    DcFast: ChargingLevel
    @staticmethod
    def l1() -> ChargingLevel: ...
    @staticmethod
    def l2() -> ChargingLevel: ...
    @staticmethod
    def dc_fast() -> ChargingLevel: ...
    @staticmethod
    def from_str(name: str) -> ChargingLevel: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...

class DriverArchetype:
    Commuter: DriverArchetype
    WorkFromHome: DriverArchetype
    ShiftWorker: DriverArchetype
    WeekendWarrior: DriverArchetype
    SeniorRetiree: DriverArchetype
    SchoolRunFamily: DriverArchetype
    @staticmethod
    def commuter() -> DriverArchetype: ...
    @staticmethod
    def work_from_home() -> DriverArchetype: ...
    @staticmethod
    def shift_worker() -> DriverArchetype: ...
    @staticmethod
    def weekend_warrior() -> DriverArchetype: ...
    @staticmethod
    def senior_retiree() -> DriverArchetype: ...
    @staticmethod
    def school_run_family() -> DriverArchetype: ...
    @staticmethod
    def from_str(name: str) -> DriverArchetype: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...

class PySimulationMetrics:
    @property
    def annual_energy_kwh(self) -> PyAnnualEnergyKwh: ...
    @property
    def peak_power_kw(self) -> PyPeakPowerKw: ...
    @property
    def comfort_hours(self) -> float | None: ...
    @property
    def unmet_load_hours(self) -> float | None: ...
    @property
    def renewable_energy_fraction(self) -> float | None: ...
    @property
    def grid_interaction(self) -> PyGridInteractionMetrics: ...
    @property
    def envelope_loads_kwh(self) -> PyEnvelopeComponentLoadsKwh | None: ...
    @property
    def efficiency(self) -> PyEfficiencyMetrics: ...
    @property
    def gas_energy(self) -> PyGasEnergyMetrics | None: ...
    def __repr__(self) -> str: ...

class PyAnnualEnergyKwh:
    @property
    def total(self) -> float: ...
    @property
    def per_end_use(self) -> dict[str, float]: ...
    def __repr__(self) -> str: ...

class PyRollingPeakKw:
    @property
    def peak_15min_kw(self) -> float: ...
    @property
    def peak_30min_kw(self) -> float: ...
    @property
    def peak_60min_kw(self) -> float: ...
    def __repr__(self) -> str: ...

class PyPeakPowerKw:
    @property
    def per_end_use(self) -> dict[str, float]: ...
    @property
    def rolling_15min_kw(self) -> float: ...
    @property
    def rolling_30min_kw(self) -> float: ...
    @property
    def rolling_60min_kw(self) -> float: ...
    def __repr__(self) -> str: ...

class PyGridInteractionMetrics:
    @property
    def peak_import_kw(self) -> float: ...
    @property
    def peak_export_kw(self) -> float: ...
    def __repr__(self) -> str: ...

class PyEnvelopeComponentLoadsKwh:
    @property
    def window_solar_kwh(self) -> float: ...
    @property
    def opaque_solar_lwr_kwh(self) -> float: ...
    @property
    def interior_lwr_kwh(self) -> float: ...
    @property
    def infiltration_kwh(self) -> float: ...
    @property
    def ventilation_kwh(self) -> float: ...
    @property
    def hvac_heating_kwh(self) -> float: ...
    @property
    def hvac_cooling_kwh(self) -> float: ...
    @property
    def internal_gains_kwh(self) -> float: ...
    @property
    def duct_loss_kwh(self) -> float: ...
    def __repr__(self) -> str: ...

class PyEfficiencyMetrics:
    @property
    def hvac_heating_cop(self) -> float | None: ...
    @property
    def hvac_cooling_cop(self) -> float | None: ...
    @property
    def water_heater_cop(self) -> float | None: ...
    @property
    def battery_round_trip_efficiency(self) -> float | None: ...
    def __repr__(self) -> str: ...

class PyGasEnergyMetrics:
    @property
    def total_therms(self) -> float: ...
    @property
    def total_kwh_equivalent(self) -> float: ...
    def __repr__(self) -> str: ...

class WeatherTimeSeries:
    def to_polars(self) -> pl.DataFrame: ...
    def __len__(self) -> int: ...
    def __repr__(self) -> str: ...
    @property
    def location(self) -> str: ...
    @property
    def latitude(self) -> float: ...
    @property
    def longitude(self) -> float: ...
    @property
    def elevation_m(self) -> float: ...
    @property
    def timezone_offset_h(self) -> float: ...
    @property
    def source_step_secs(self) -> int: ...
    @property
    def midpoint_offset_secs(self) -> int: ...
    @property
    def surface_albedo(self) -> list[float] | None: ...

def parse_weather(path: str) -> WeatherTimeSeries: ...
def parse_epw(path: str) -> WeatherTimeSeries: ...
def parse_psm3(path: str) -> WeatherTimeSeries: ...
def parse_tmy3(path: str) -> WeatherTimeSeries: ...
def parse_resstock_csv(
    path: str,
    elevation_m: float,
    latitude: float,
    longitude: float,
    timezone_offset_h: float,
) -> WeatherTimeSeries: ...
