"""Type stubs for the HARES Rust extension module."""

from __future__ import annotations

import datetime
from abc import abstractmethod
from collections.abc import Callable, Iterator
from typing import Any

import polars as pl

# ---------------------------------------------------------------------------
# Enums
# ---------------------------------------------------------------------------

class EndUse:
    HVAC_HEATING: EndUse
    HVAC_COOLING: EndUse
    WATER_HEATING: EndUse
    LIGHTING: EndUse
    PLUG_LOADS: EndUse
    REFRIGERATION: EndUse
    VENTILATION: EndUse
    BATTERY: EndUse
    PV: EndUse
    EV: EndUse
    GENERATOR: EndUse
    DEHUMIDIFIER: EndUse
    OTHER: EndUse
    @staticmethod
    def custom(name: str) -> EndUse: ...
    def as_str(self) -> str: ...
    def is_standard(self) -> bool: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...

class FuelType:
    Electric: FuelType
    Gas: FuelType
    Propane: FuelType
    Oil: FuelType
    NoFuel: FuelType
    @staticmethod
    def electric() -> FuelType: ...
    @staticmethod
    def gas() -> FuelType: ...
    @staticmethod
    def propane() -> FuelType: ...
    @staticmethod
    def oil() -> FuelType: ...
    @staticmethod
    def no_fuel() -> FuelType: ...
    @staticmethod
    def from_str(name: str) -> FuelType: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...

class Mode:
    Off: Mode
    Heating: Mode
    Cooling: Mode
    Standby: Mode
    Defrost: Mode
    Charging: Mode
    Discharging: Mode
    HeatingHP: Mode
    HeatingER: Mode
    HeatingHPAndER: Mode
    HeatPumpWH: Mode
    BackupElement: Mode
    @staticmethod
    def off() -> Mode: ...
    @staticmethod
    def heating() -> Mode: ...
    @staticmethod
    def cooling() -> Mode: ...
    @staticmethod
    def standby() -> Mode: ...
    @staticmethod
    def defrost() -> Mode: ...
    @staticmethod
    def charging() -> Mode: ...
    @staticmethod
    def discharging() -> Mode: ...
    @staticmethod
    def heating_hp() -> Mode: ...
    @staticmethod
    def heating_er() -> Mode: ...
    @staticmethod
    def heating_hp_and_er() -> Mode: ...
    @staticmethod
    def heat_pump_wh() -> Mode: ...
    @staticmethod
    def backup_element() -> Mode: ...
    @staticmethod
    def from_str(name: str) -> Mode: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...

OperatingMode = Mode
PyMode = Mode

class DRLevel:
    Normal: DRLevel
    Moderate: DRLevel
    High: DRLevel
    Critical: DRLevel
    GridEmergency: DRLevel
    @staticmethod
    def normal() -> DRLevel: ...
    @staticmethod
    def moderate() -> DRLevel: ...
    @staticmethod
    def high() -> DRLevel: ...
    @staticmethod
    def critical() -> DRLevel: ...
    @staticmethod
    def grid_emergency() -> DRLevel: ...
    @staticmethod
    def from_str(name: str) -> DRLevel: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...

class ExecutionStage:
    Independent: ExecutionStage
    Electrical: ExecutionStage
    Thermal: ExecutionStage
    EnvelopeResolution: ExecutionStage
    @staticmethod
    def independent() -> ExecutionStage: ...
    @staticmethod
    def electrical() -> ExecutionStage: ...
    @staticmethod
    def thermal() -> ExecutionStage: ...
    @staticmethod
    def envelope_resolution() -> ExecutionStage: ...
    @staticmethod
    def from_str(name: str) -> ExecutionStage: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...

class FluidType:
    Water: FluidType
    Glycol: FluidType
    Refrigerant: FluidType
    @staticmethod
    def water() -> FluidType: ...
    @staticmethod
    def glycol() -> FluidType: ...
    @staticmethod
    def refrigerant() -> FluidType: ...
    @staticmethod
    def from_str(name: str) -> FluidType: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...

class InverterPriority:
    Watt: InverterPriority
    Var: InverterPriority
    Cpf: InverterPriority
    @staticmethod
    def watt() -> InverterPriority: ...
    @staticmethod
    def var() -> InverterPriority: ...
    @staticmethod
    def cpf() -> InverterPriority: ...
    @staticmethod
    def from_str(name: str) -> InverterPriority: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...

class DutyCycleComponent:
    Compressor: DutyCycleComponent
    BackupElement: DutyCycleComponent
    @staticmethod
    def compressor() -> DutyCycleComponent: ...
    @staticmethod
    def backup_element() -> DutyCycleComponent: ...
    @staticmethod
    def from_str(name: str) -> DutyCycleComponent: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...

class SimStatus:
    @staticmethod
    def ok() -> SimStatus: ...
    @staticmethod
    def flagged(message: str | None = ...) -> SimStatus: ...
    @staticmethod
    def failed(message: str | None = ...) -> SimStatus: ...
    @staticmethod
    def from_str(name: str) -> SimStatus: ...
    @property
    def message(self) -> str | None: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...

class AggregationResolution:
    FifteenMin: AggregationResolution
    Hourly: AggregationResolution
    @staticmethod
    def fifteen_min() -> AggregationResolution: ...
    @staticmethod
    def hourly() -> AggregationResolution: ...
    @staticmethod
    def from_str(name: str) -> AggregationResolution: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...

class ResStockVersion:
    V2024_1: ResStockVersion
    V2024_2: ResStockVersion
    V2025_1: ResStockVersion
    @staticmethod
    def v2024_1() -> ResStockVersion: ...
    @staticmethod
    def v2024_2() -> ResStockVersion: ...
    @staticmethod
    def v2025_1() -> ResStockVersion: ...
    @staticmethod
    def from_str(name: str) -> ResStockVersion: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...

class ControlCapabilities:
    POWER_SETPOINT: ControlCapabilities
    SOC_TARGET: ControlCapabilities
    THERMAL_SETPOINT: ControlCapabilities
    POWER_LIMIT: ControlCapabilities
    MODE_OVERRIDE: ControlCapabilities
    DUTY_CYCLE: ControlCapabilities
    LOAD_FRACTION: ControlCapabilities
    GRID_CONNECT: ControlCapabilities
    SELF_CONSUMPTION: ControlCapabilities
    DEMAND_RESPONSE: ControlCapabilities
    PROTOCOL_NATIVE: ControlCapabilities
    HUMIDITY_SETPOINT: ControlCapabilities
    CURTAILMENT_PERCENT: ControlCapabilities
    REACTIVE_SETPOINT: ControlCapabilities
    POWER_FACTOR_SETPOINT: ControlCapabilities
    INVERTER_PRIORITY_MODE: ControlCapabilities
    @staticmethod
    def from_list(names: list[str]) -> ControlCapabilities: ...
    def __or__(self, other: ControlCapabilities) -> ControlCapabilities: ...
    def __contains__(self, other: ControlCapabilities) -> bool: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...

class LutType:
    ChargingCurve: LutType
    Ocv: LutType
    UNeg: LutType
    @staticmethod
    def charging_curve() -> LutType: ...
    @staticmethod
    def ocv() -> LutType: ...
    @staticmethod
    def uneg() -> LutType: ...
    @staticmethod
    def from_str(name: str) -> LutType: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...

class BatteryProductId:
    TeslaPw3: BatteryProductId
    TeslaPw2: BatteryProductId
    TeslaPw3X2: BatteryProductId
    EnphaseIq5p: BatteryProductId
    EnphaseIq5pX2: BatteryProductId
    EnphaseIq10c: BatteryProductId
    FranklinApower: BatteryProductId
    FranklinApower2: BatteryProductId
    FranklinApower2X2: BatteryProductId
    SolaredgeHome: BatteryProductId
    LgResu10h: BatteryProductId
    @staticmethod
    def tesla_pw3() -> BatteryProductId: ...
    @staticmethod
    def tesla_pw2() -> BatteryProductId: ...
    @staticmethod
    def tesla_pw3_x2() -> BatteryProductId: ...
    @staticmethod
    def enphase_iq5p() -> BatteryProductId: ...
    @staticmethod
    def enphase_iq5p_x2() -> BatteryProductId: ...
    @staticmethod
    def enphase_iq10c() -> BatteryProductId: ...
    @staticmethod
    def franklin_apower() -> BatteryProductId: ...
    @staticmethod
    def franklin_apower2() -> BatteryProductId: ...
    @staticmethod
    def franklin_apower2_x2() -> BatteryProductId: ...
    @staticmethod
    def solaredge_home() -> BatteryProductId: ...
    @staticmethod
    def lg_resu10h() -> BatteryProductId: ...
    @staticmethod
    def from_str(name: str) -> BatteryProductId: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...

class BatteryChemistry:
    Nmc: BatteryChemistry
    Lfp: BatteryChemistry
    Nca: BatteryChemistry
    Lto: BatteryChemistry
    @staticmethod
    def nmc() -> BatteryChemistry: ...
    @staticmethod
    def lfp() -> BatteryChemistry: ...
    @staticmethod
    def nca() -> BatteryChemistry: ...
    @staticmethod
    def lto() -> BatteryChemistry: ...
    @staticmethod
    def from_str(name: str) -> BatteryChemistry: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...

class ChargingLevel:
    L1: ChargingLevel
    L2: ChargingLevel
    @staticmethod
    def l1() -> ChargingLevel: ...
    @staticmethod
    def l2() -> ChargingLevel: ...
    @staticmethod
    def from_str(name: str) -> ChargingLevel: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...

class VehicleType:
    Bev: VehicleType
    Phev: VehicleType
    @staticmethod
    def bev() -> VehicleType: ...
    @staticmethod
    def phev() -> VehicleType: ...
    @staticmethod
    def from_str(name: str) -> VehicleType: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...

class EvConnectionState:
    HomePluggedIn: EvConnectionState
    AwayPluggedIn: EvConnectionState
    Disconnected: EvConnectionState
    @staticmethod
    def home_plugged_in() -> EvConnectionState: ...
    @staticmethod
    def away_plugged_in() -> EvConnectionState: ...
    @staticmethod
    def disconnected() -> EvConnectionState: ...
    @staticmethod
    def from_str(name: str) -> EvConnectionState: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...

class PlugInPolicy:
    @staticmethod
    def always() -> PlugInPolicy: ...
    @staticmethod
    def low_soc(threshold: float) -> PlugInPolicy: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...
    def __eq__(self, other: object) -> bool: ...

class ChargingStrategy:
    @staticmethod
    def immediate(target_soc: float) -> ChargingStrategy: ...
    @staticmethod
    def nightly(off_peak_start_hour: float, off_peak_end_hour: float, target_soc: float) -> ChargingStrategy: ...
    @staticmethod
    def low_soc(threshold: float, target_soc: float) -> ChargingStrategy: ...
    @staticmethod
    def quick_then_wait(partial_soc: float) -> ChargingStrategy: ...
    @staticmethod
    def pre_departure(target_soc: float) -> ChargingStrategy: ...
    @staticmethod
    def tou_aware(target_soc: float) -> ChargingStrategy: ...
    @staticmethod
    def v2h(discharge_threshold_soc: float, min_soc: float) -> ChargingStrategy: ...
    @staticmethod
    def v2g(min_soc: float, max_export_kw: float, price_threshold: float) -> ChargingStrategy: ...
    @staticmethod
    def solar_surplus(min_charge_rate_kw: float) -> ChargingStrategy: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...
    def __eq__(self, other: object) -> bool: ...

# ---------------------------------------------------------------------------
# Control signals
# ---------------------------------------------------------------------------

class ControlSignal:
    @staticmethod
    def power_setpoint(
        kw: float, reactive_kvar: float | None = ...
    ) -> ControlSignal: ...
    @staticmethod
    def thermal_setpoint(
        heat_c: float | None = ...,
        cool_c: float | None = ...,
        deadband_c: float | None = ...,
    ) -> ControlSignal: ...
    @staticmethod
    def thermal_setpoint_delta(
        heating_delta_c: float | None = ...,
        cooling_delta_c: float | None = ...,
    ) -> ControlSignal: ...
    @staticmethod
    def soc_target(
        target: float,
        min: float | None = ...,
        max: float | None = ...,
    ) -> ControlSignal: ...
    @staticmethod
    def humidity_setpoint(
        target_rh: float,
        min_rh: float | None = ...,
        max_rh: float | None = ...,
    ) -> ControlSignal: ...
    @staticmethod
    def power_limit(
        max_power_kw: float,
        ramp_rate_kw_per_s: float | None = ...,
    ) -> ControlSignal: ...
    @staticmethod
    def duty_cycle(
        on_fraction: float,
        period_s: float | None = ...,
        component: DutyCycleComponent | None = ...,
    ) -> ControlSignal: ...
    @staticmethod
    def grid_connect(connected: bool) -> ControlSignal: ...
    @staticmethod
    def self_consumption(
        enabled: bool, solar_only_charging: bool
    ) -> ControlSignal: ...
    @staticmethod
    def curtailment_percent(percent: float) -> ControlSignal: ...
    @staticmethod
    def reactive_setpoint(kvar: float) -> ControlSignal: ...
    @staticmethod
    def power_factor_setpoint(power_factor: float) -> ControlSignal: ...
    @staticmethod
    def inverter_priority_mode(priority: InverterPriority) -> ControlSignal: ...
    @staticmethod
    def protocol_native(protocol_id: int, payload: bytes) -> ControlSignal: ...
    @staticmethod
    def ideal_capacity_mode_override(mode: str) -> ControlSignal: ...
    @staticmethod
    def ideal_capacity(capacity_w: float) -> ControlSignal: ...
    @staticmethod
    def load_fraction(fraction: float) -> ControlSignal: ...
    @staticmethod
    def mode_override(mode: Mode) -> ControlSignal: ...
    @staticmethod
    def mode_override_str(mode: str) -> ControlSignal: ...
    @staticmethod
    def demand_response(
        level: DRLevel, duration_s: float | None = ...
    ) -> ControlSignal: ...
    @staticmethod
    def demand_response_str(
        level: str, duration_s: float | None = ...
    ) -> ControlSignal: ...
    @staticmethod
    def ev_plug_in(state: EvConnectionState) -> ControlSignal: ...
    @staticmethod
    def ev_drive(kwh: float) -> ControlSignal: ...
    @staticmethod
    def ev_away_charge(power_kw: float) -> ControlSignal: ...
    @staticmethod
    def ev_set_ready_by(departure_hour: float, target_soc: float) -> ControlSignal: ...
    @classmethod
    def from_dict(cls, d: dict[str, Any]) -> ControlSignal: ...
    def to_dict(self) -> dict[str, Any]: ...
    def __repr__(self) -> str: ...

# ---------------------------------------------------------------------------
# Actor system
# ---------------------------------------------------------------------------

class Priority:
    @staticmethod
    def schedule() -> Priority: ...
    @staticmethod
    def user_override() -> Priority: ...
    @staticmethod
    def grid() -> Priority: ...
    @staticmethod
    def safety() -> Priority: ...
    def __repr__(self) -> str: ...

class Signal:
    @staticmethod
    def thermal_setpoint(
        heating_c: float | None = ...,
        cooling_c: float | None = ...,
        deadband_c: float | None = ...,
    ) -> Signal: ...
    @staticmethod
    def thermal_setpoint_delta(
        heating_delta_c: float | None = ...,
        cooling_delta_c: float | None = ...,
    ) -> Signal: ...
    @staticmethod
    def mode_override(mode: Mode) -> Signal: ...
    @staticmethod
    def load_fraction(fraction: float) -> Signal: ...
    @staticmethod
    def power_limit(max_kw: float) -> Signal: ...
    @staticmethod
    def power_setpoint(
        active_power_kw: float, reactive_power_kvar: float | None = ...
    ) -> Signal: ...
    @staticmethod
    def soc_target(
        target_soc: float,
        min_soc: float | None = ...,
        max_soc: float | None = ...,
    ) -> Signal: ...
    @staticmethod
    def duty_cycle(
        on_fraction: float, period_s: float | None = ...
    ) -> Signal: ...
    @staticmethod
    def demand_response(
        level: DRLevel, duration_s: float | None = ...
    ) -> Signal: ...
    @staticmethod
    def ideal_capacity(capacity_w: float) -> Signal: ...
    def __repr__(self) -> str: ...

class DispatchRequest:
    @property
    def target(self) -> str: ...
    @property
    def signal(self) -> Signal: ...
    @property
    def priority(self) -> Priority: ...
    @staticmethod
    def thermal_setpoint(
        target: str,
        heating_c: float | None = ...,
        cooling_c: float | None = ...,
        deadband_c: float | None = ...,
        priority: Priority | None = ...,
    ) -> DispatchRequest: ...
    @staticmethod
    def thermal_setpoint_delta(
        target: str,
        heating_delta_c: float | None = ...,
        cooling_delta_c: float | None = ...,
        priority: Priority | None = ...,
    ) -> DispatchRequest: ...
    @staticmethod
    def mode_override(
        target: str, mode: Mode, priority: Priority | None = ...
    ) -> DispatchRequest: ...
    @staticmethod
    def load_fraction(
        target: str, fraction: float, priority: Priority | None = ...
    ) -> DispatchRequest: ...
    @staticmethod
    def power_limit(
        target: str, max_kw: float, priority: Priority | None = ...
    ) -> DispatchRequest: ...
    @staticmethod
    def power_setpoint(
        target: str,
        active_power_kw: float,
        reactive_power_kvar: float | None = ...,
        priority: Priority | None = ...,
    ) -> DispatchRequest: ...
    @staticmethod
    def soc_target(
        target: str,
        target_soc: float,
        min_soc: float | None = ...,
        max_soc: float | None = ...,
        priority: Priority | None = ...,
    ) -> DispatchRequest: ...
    @staticmethod
    def duty_cycle(
        target: str,
        on_fraction: float,
        period_s: float | None = ...,
        priority: Priority | None = ...,
    ) -> DispatchRequest: ...
    @staticmethod
    def demand_response(
        target: str,
        level: DRLevel,
        duration_s: float | None = ...,
        priority: Priority | None = ...,
    ) -> DispatchRequest: ...
    @staticmethod
    def ideal_capacity(
        target: str, capacity_w: float, priority: Priority | None = ...
    ) -> DispatchRequest: ...
    def __repr__(self) -> str: ...

class Actor:
    def __init__(self) -> None: ...
    @property
    def name(self) -> str: ...
    @name.setter
    def name(self, value: str) -> None: ...
    @abstractmethod
    def decide(self, env: dict[str, Any]) -> list[DispatchRequest]: ...

# ---------------------------------------------------------------------------
# Telemetry
# ---------------------------------------------------------------------------

class Telemetry:
    def zone(self) -> dict[str, Any]: ...
    def equipment(self) -> dict[str, Any]: ...
    def total_power_kw(self) -> float: ...
    def __repr__(self) -> str: ...

# ---------------------------------------------------------------------------
# Equipment introspection
# ---------------------------------------------------------------------------

class TelemetryField:
    @property
    def name(self) -> str: ...
    @property
    def unit(self) -> str: ...
    @property
    def description(self) -> str: ...
    def __repr__(self) -> str: ...

class EquipmentDescriptor:
    @property
    def id(self) -> int: ...
    @property
    def name(self) -> str: ...
    @property
    def end_use(self) -> EndUse: ...
    @property
    def equipment_type(self) -> str: ...
    @property
    def zone(self) -> int | None: ...
    @property
    def fuel_type(self) -> FuelType: ...
    @property
    def stage(self) -> ExecutionStage: ...
    @property
    def control_capabilities(self) -> ControlCapabilities: ...
    @property
    def telemetry_fields(self) -> list[TelemetryField]: ...
    def __repr__(self) -> str: ...

# ---------------------------------------------------------------------------
# Equipment types
# ---------------------------------------------------------------------------

class Battery:
    @property
    def name(self) -> str: ...
    @property
    def capacity_kwh(self) -> float: ...
    @property
    def max_charge_kw(self) -> float | None: ...
    @property
    def max_discharge_kw(self) -> float | None: ...
    @property
    def chemistry(self) -> BatteryChemistry | None: ...
    @property
    def initial_soc(self) -> float | None: ...
    @property
    def min_soc(self) -> float | None: ...
    @property
    def max_soc(self) -> float | None: ...
    @property
    def inverter_efficiency(self) -> float | None: ...
    @property
    def charge_efficiency(self) -> float | None: ...
    @property
    def discharge_efficiency(self) -> float | None: ...
    @property
    def self_discharge_pct_per_day(self) -> float | None: ...
    @property
    def standby_power_w(self) -> float | None: ...
    @property
    def import_limit_w(self) -> float | None: ...
    @property
    def export_limit_w(self) -> float | None: ...
    @property
    def n_series(self) -> int | None: ...
    @property
    def n_parallel(self) -> int | None: ...
    @property
    def cell_resistance_ohm(self) -> float | None: ...
    @property
    def heater_power_w(self) -> float | None: ...
    @property
    def heater_threshold_c(self) -> float | None: ...
    @property
    def min_charge_temp_c(self) -> float | None: ...
    @property
    def full_power_temp_c(self) -> float | None: ...
    @property
    def cell_thermal_mass_j_per_k(self) -> float | None: ...
    @property
    def cell_ua_w_per_k(self) -> float | None: ...
    def __init__(
        self,
        name: str,
        capacity_kwh: float,
        max_charge_kw: float | None = ...,
        max_discharge_kw: float | None = ...,
        chemistry: BatteryChemistry | None = ...,
        initial_soc: float | None = ...,
        min_soc: float | None = ...,
        max_soc: float | None = ...,
        inverter_efficiency: float | None = ...,
        charge_efficiency: float | None = ...,
        discharge_efficiency: float | None = ...,
        self_discharge_pct_per_day: float | None = ...,
        standby_power_w: float | None = ...,
        import_limit_w: float | None = ...,
        export_limit_w: float | None = ...,
        n_series: int | None = ...,
        n_parallel: int | None = ...,
        cell_resistance_ohm: float | None = ...,
        heater_power_w: float | None = ...,
        heater_threshold_c: float | None = ...,
        min_charge_temp_c: float | None = ...,
        full_power_temp_c: float | None = ...,
        cell_thermal_mass_j_per_k: float | None = ...,
        cell_ua_w_per_k: float | None = ...,
        charging_curve_lut: str | dict[str, Any] | None = ...,
        ocv_table: list[tuple[float, float]]
        | dict[str, Any]
        | None = ...,
        uneg_table: list[tuple[float, float]]
        | dict[str, Any]
        | None = ...,
    ) -> None: ...
    @staticmethod
    def from_product(product_id: BatteryProductId) -> Battery: ...
    @staticmethod
    def by_product_id(id: str) -> Battery: ...
    @staticmethod
    def product_catalog() -> list[BatteryProductId]: ...
    @staticmethod
    def tesla_pw3() -> Battery: ...
    @staticmethod
    def tesla_pw2() -> Battery: ...
    @staticmethod
    def tesla_pw3_x2() -> Battery: ...
    @staticmethod
    def enphase_iq5p() -> Battery: ...
    @staticmethod
    def enphase_iq5p_x2() -> Battery: ...
    @staticmethod
    def enphase_iq10c() -> Battery: ...
    @staticmethod
    def franklin_apower() -> Battery: ...
    @staticmethod
    def franklin_apower2() -> Battery: ...
    @staticmethod
    def franklin_apower2_x2() -> Battery: ...
    @staticmethod
    def solaredge_home() -> Battery: ...
    @staticmethod
    def lg_resu10h() -> Battery: ...
    def __repr__(self) -> str: ...

class PvSoilingConfig:
    @property
    def cleaning_threshold_mm(self) -> float: ...
    @property
    def loss_rate_per_day(self) -> float: ...
    @property
    def grace_period_days(self) -> float: ...
    @property
    def max_loss(self) -> float: ...
    @property
    def initial_loss(self) -> float: ...
    @property
    def rain_accum_hours(self) -> float: ...
    def __init__(
        self,
        cleaning_threshold_mm: float = ...,
        loss_rate_per_day: float = ...,
        grace_period_days: float = ...,
        max_loss: float = ...,
        initial_loss: float = ...,
        rain_accum_hours: float = ...,
    ) -> None: ...
    def __repr__(self) -> str: ...

class PV:
    @property
    def name(self) -> str: ...
    @property
    def capacity_kw(self) -> float: ...
    @property
    def tilt(self) -> float: ...
    @property
    def azimuth(self) -> float: ...
    @property
    def soiling(self) -> PvSoilingConfig | None: ...
    def __init__(
        self,
        name: str,
        capacity_kw: float,
        tilt: float,
        azimuth: float,
        soiling: PvSoilingConfig | None = ...,
    ) -> None: ...
    def __repr__(self) -> str: ...

class EvArchetypeId:
    DailyCommuterL2: EvArchetypeId
    DailyCommuterL1: EvArchetypeId
    LongCommuterL2: EvArchetypeId
    WfhOccasional: EvArchetypeId
    WfhL1Minimal: EvArchetypeId
    HeavyUseSuv: EvArchetypeId
    ShiftWorker: EvArchetypeId
    WeekendWarrior: EvArchetypeId
    WorkplaceCharger: EvArchetypeId
    RetireeL1: EvArchetypeId
    PhevCommuter: EvArchetypeId
    TouOptimizerCa: EvArchetypeId
    @staticmethod
    def daily_commuter_l2() -> EvArchetypeId: ...
    @staticmethod
    def daily_commuter_l1() -> EvArchetypeId: ...
    @staticmethod
    def long_commuter_l2() -> EvArchetypeId: ...
    @staticmethod
    def wfh_occasional() -> EvArchetypeId: ...
    @staticmethod
    def wfh_l1_minimal() -> EvArchetypeId: ...
    @staticmethod
    def heavy_use_suv() -> EvArchetypeId: ...
    @staticmethod
    def shift_worker() -> EvArchetypeId: ...
    @staticmethod
    def weekend_warrior() -> EvArchetypeId: ...
    @staticmethod
    def workplace_charger() -> EvArchetypeId: ...
    @staticmethod
    def retiree_l1() -> EvArchetypeId: ...
    @staticmethod
    def phev_commuter() -> EvArchetypeId: ...
    @staticmethod
    def tou_optimizer_ca() -> EvArchetypeId: ...
    @staticmethod
    def from_str(name: str) -> EvArchetypeId: ...
    @staticmethod
    def archetype_catalog() -> list[EvArchetypeId]: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...

class VehicleId:
    TeslaModelYLr: VehicleId
    TeslaModelYSr: VehicleId
    TeslaModel3Lr: VehicleId
    ChevyBoltEv: VehicleId
    ChevyBoltEuv: VehicleId
    FordMacheSr: VehicleId
    FordMacheEr: VehicleId
    FordLightningEr: VehicleId
    HyundaiIoniq5Lr: VehicleId
    NissanLeaf30: VehicleId
    Jeep4xe: VehicleId
    ToyotaRav4Prime: VehicleId
    ChevyVoltGen1: VehicleId
    @staticmethod
    def tesla_model_y_lr() -> VehicleId: ...
    @staticmethod
    def tesla_model_y_sr() -> VehicleId: ...
    @staticmethod
    def tesla_model_3_lr() -> VehicleId: ...
    @staticmethod
    def chevy_bolt_ev() -> VehicleId: ...
    @staticmethod
    def chevy_bolt_euv() -> VehicleId: ...
    @staticmethod
    def ford_mache_sr() -> VehicleId: ...
    @staticmethod
    def ford_mache_er() -> VehicleId: ...
    @staticmethod
    def ford_lightning_er() -> VehicleId: ...
    @staticmethod
    def hyundai_ioniq5_lr() -> VehicleId: ...
    @staticmethod
    def nissan_leaf30() -> VehicleId: ...
    @staticmethod
    def jeep_4xe() -> VehicleId: ...
    @staticmethod
    def toyota_rav4_prime() -> VehicleId: ...
    @staticmethod
    def chevy_volt_gen1() -> VehicleId: ...
    @staticmethod
    def from_str(name: str) -> VehicleId: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...

class EV:
    @property
    def name(self) -> str: ...
    @property
    def capacity_kwh(self) -> float | None: ...
    @property
    def max_charging_kw(self) -> float | None: ...
    @property
    def initial_soc(self) -> float | None: ...
    @property
    def initial_connection_state(self) -> EvConnectionState | None: ...
    def __init__(
        self,
        name: str,
        capacity_kwh: float | None = ...,
        max_charging_kw: float | None = ...,
        initial_soc: float | None = ...,
        initial_connection_state: EvConnectionState | None = ...,
        charging_curve_lut: str | dict[str, Any] | None = ...,
    ) -> None: ...
    @staticmethod
    def from_vehicle(vehicle_id: VehicleId) -> EV: ...
    @staticmethod
    def from_vehicle_with_archetype(
        vehicle_id: VehicleId,
        archetype_id: EvArchetypeId,
        seed: int,
    ) -> EV: ...
    @staticmethod
    def by_vehicle_id(id: str) -> EV: ...
    @staticmethod
    def vehicle_catalog() -> list[VehicleId]: ...
    @staticmethod
    def tesla_model_y_lr() -> EV: ...
    @staticmethod
    def tesla_model_y_sr() -> EV: ...
    @staticmethod
    def tesla_model_3_lr() -> EV: ...
    @staticmethod
    def chevy_bolt_ev() -> EV: ...
    @staticmethod
    def chevy_bolt_euv() -> EV: ...
    @staticmethod
    def ford_mache_sr() -> EV: ...
    @staticmethod
    def ford_mache_er() -> EV: ...
    @staticmethod
    def ford_lightning_er() -> EV: ...
    @staticmethod
    def hyundai_ioniq5_lr() -> EV: ...
    @staticmethod
    def nissan_leaf30() -> EV: ...
    @staticmethod
    def jeep_4xe() -> EV: ...
    @staticmethod
    def toyota_rav4_prime() -> EV: ...
    @staticmethod
    def chevy_volt_gen1() -> EV: ...
    def __repr__(self) -> str: ...

# ---------------------------------------------------------------------------
# PV sizing (frozen, not constructable from Python)
# ---------------------------------------------------------------------------

class RoofPlane:
    @property
    def index(self) -> int: ...
    @property
    def area_m2(self) -> float: ...
    @property
    def tilt_deg(self) -> float: ...
    @property
    def azimuth_deg(self) -> float | None: ...
    @property
    def material(self) -> str | None: ...
    @property
    def boundary_index(self) -> int | None: ...

class PvCandidate:
    @property
    def plane_idx(self) -> int: ...
    @property
    def azimuth_deg(self) -> float: ...
    @property
    def tilt_deg(self) -> float: ...
    @property
    def usable_m2(self) -> float: ...
    @property
    def max_panels(self) -> int: ...
    @property
    def max_capacity_kw(self) -> float: ...
    @property
    def solar_score(self) -> float: ...
    @property
    def boundary_index(self) -> int | None: ...

class PvSizingResult:
    @property
    def capacity_kw(self) -> float: ...
    @property
    def num_panels(self) -> int: ...
    @property
    def collector_area_m2(self) -> float: ...
    @property
    def array_azimuth_deg(self) -> float: ...
    @property
    def array_tilt_deg(self) -> float: ...
    @property
    def system_losses_fraction(self) -> float: ...
    @property
    def max_roof_capacity_kw(self) -> float: ...
    @property
    def panel_watts(self) -> int: ...

# ---------------------------------------------------------------------------
# Configuration
# ---------------------------------------------------------------------------

class SimulationConfig:
    def __init__(
        self,
        start_time: str | None = ...,
        duration_s: int | None = ...,
        time_res_s: int | None = ...,
        output_verbosity: int | None = ...,
        output_path: str | None = ...,
        output_to_parquet: bool | None = ...,
        output_chunk_size: int | None = ...,
        master_seed: int | None = ...,
        civil_timezone: str | None = ...,
        setpoint_deadband_c: float | None = ...,
    ) -> None: ...
    @property
    def start_time(self) -> str: ...
    @start_time.setter
    def start_time(self, value: str) -> None: ...
    @property
    def duration_s(self) -> int: ...
    @duration_s.setter
    def duration_s(self, value: int) -> None: ...
    @property
    def time_res_s(self) -> int: ...
    @time_res_s.setter
    def time_res_s(self, value: int) -> None: ...
    @property
    def output_verbosity(self) -> int: ...
    @property
    def output_path(self) -> str | None: ...
    @property
    def output_to_parquet(self) -> bool: ...
    @property
    def output_chunk_size(self) -> int: ...
    @property
    def setpoint_deadband_c(self) -> float | None: ...
    @property
    def master_seed(self) -> int: ...
    @property
    def civil_timezone(self) -> str | None: ...
    def __repr__(self) -> str: ...

class DwellingConfig:
    def __init__(
        self,
        hpxml: str,
        schedule: str,
        weather: str,
        config: SimulationConfig | None = ...,
        defaults_path: str | None = ...,
        bldg_id: int | None = ...,
        initialization_duration: int | None = ...,
        resample_overrides: dict[str, str] | None = ...,
        overrides: dict[str, Any] | None = ...,
    ) -> None: ...
    @property
    def hpxml(self) -> str: ...
    @property
    def schedule(self) -> str: ...
    @property
    def weather(self) -> str: ...
    @property
    def config(self) -> SimulationConfig | None: ...
    @property
    def defaults_path(self) -> str | None: ...
    @property
    def bldg_id(self) -> int: ...
    @property
    def initialization_duration(self) -> int | None: ...
    @property
    def resample_overrides(self) -> dict[str, str] | None: ...
    @property
    def overrides(self) -> dict[str, Any] | None: ...
    def __repr__(self) -> str: ...

# ---------------------------------------------------------------------------
# Metrics (frozen)
# ---------------------------------------------------------------------------

class AnnualEnergyKwh:
    @property
    def total(self) -> float: ...
    @property
    def per_end_use(self) -> dict[str, float]: ...
    def __repr__(self) -> str: ...

class RollingPeakKw:
    @property
    def peak_15min_kw(self) -> float: ...
    @property
    def peak_30min_kw(self) -> float: ...
    @property
    def peak_60min_kw(self) -> float: ...
    def __repr__(self) -> str: ...

class PeakPowerKw:
    @property
    def per_end_use(self) -> dict[str, float]: ...
    @property
    def rolling_15min_kw(self) -> float: ...
    @property
    def rolling_30min_kw(self) -> float: ...
    @property
    def rolling_60min_kw(self) -> float: ...
    def __repr__(self) -> str: ...

class GridInteractionMetrics:
    @property
    def peak_import_kw(self) -> float: ...
    @property
    def peak_export_kw(self) -> float: ...
    def __repr__(self) -> str: ...

class EnvelopeComponentLoadsKwh:
    @property
    def window_solar_kwh(self) -> float: ...
    @property
    def opaque_solar_lwr_kwh(self) -> float: ...
    @property
    def interior_lwr_kwh(self) -> float: ...
    @property
    def infiltration_kwh(self) -> float: ...
    @property
    def ventilation_kwh(self) -> float: ...
    @property
    def hvac_heating_kwh(self) -> float: ...
    @property
    def hvac_cooling_kwh(self) -> float: ...
    @property
    def internal_gains_kwh(self) -> float: ...
    @property
    def duct_loss_kwh(self) -> float: ...
    def __repr__(self) -> str: ...

class EfficiencyMetrics:
    @property
    def hvac_heating_cop(self) -> float | None: ...
    @property
    def hvac_cooling_cop(self) -> float | None: ...
    @property
    def water_heater_cop(self) -> float | None: ...
    @property
    def battery_round_trip_efficiency(self) -> float | None: ...
    def __repr__(self) -> str: ...

class GasEnergyMetrics:
    @property
    def total_therms(self) -> float: ...
    @property
    def total_kwh_equivalent(self) -> float: ...
    def __repr__(self) -> str: ...

class SimulationMetrics:
    @property
    def annual_energy_kwh(self) -> AnnualEnergyKwh: ...
    @property
    def peak_power_kw(self) -> PeakPowerKw: ...
    @property
    def comfort_hours(self) -> float | None: ...
    @property
    def unmet_load_hours(self) -> float | None: ...
    @property
    def renewable_energy_fraction(self) -> float | None: ...
    @property
    def grid_interaction(self) -> GridInteractionMetrics: ...
    @property
    def envelope_loads_kwh(self) -> EnvelopeComponentLoadsKwh | None: ...
    @property
    def efficiency(self) -> EfficiencyMetrics: ...
    @property
    def gas_energy(self) -> GasEnergyMetrics | None: ...
    def __repr__(self) -> str: ...

# ---------------------------------------------------------------------------
# Weather
# ---------------------------------------------------------------------------

class WeatherTimeSeries:
    def to_polars(self) -> pl.DataFrame: ...
    def __len__(self) -> int: ...
    def __repr__(self) -> str: ...
    @property
    def location(self) -> str: ...
    @property
    def latitude(self) -> float: ...
    @property
    def longitude(self) -> float: ...
    @property
    def elevation_m(self) -> float: ...
    @property
    def timezone_offset_h(self) -> float: ...
    @property
    def source_step_secs(self) -> int: ...
    @property
    def midpoint_offset_secs(self) -> int: ...
    @property
    def surface_albedo(self) -> list[float] | None: ...

def parse_weather(path: str) -> WeatherTimeSeries: ...
def parse_epw(path: str) -> WeatherTimeSeries: ...
def parse_psm3(path: str) -> WeatherTimeSeries: ...
def parse_tmy3(path: str) -> WeatherTimeSeries: ...
def parse_resstock_csv(
    path: str,
    elevation_m: float,
    latitude: float,
    longitude: float,
    timezone_offset_h: float,
) -> WeatherTimeSeries: ...

# ---------------------------------------------------------------------------
# Fleet
# ---------------------------------------------------------------------------

class Fleet:
    @classmethod
    def from_buildings(
        cls,
        configs: list[DwellingConfig],
        sample_weights: list[float] | None = ...,
    ) -> Fleet: ...
    @classmethod
    def from_resstock(
        cls,
        metadata_path: str,
        hpxml_dir: str,
        weather_dir: str,
        filter: dict[str, str] | None = ...,
        resstock_version: ResStockVersion | str | None = ...,
    ) -> Fleet: ...
    def simulate(
        self,
        n_threads: int | None = ...,
        resolution: AggregationResolution | str | None = ...,
        raise_on_failure: bool | None = ...,
        progress: Callable[[int, int], None] | None = ...,
    ) -> FleetResults: ...
    def __len__(self) -> int: ...
    def __repr__(self) -> str: ...

class FleetResults:
    @property
    def per_dwelling_metrics(self) -> pl.DataFrame: ...
    @property
    def aggregate_timeseries(self) -> pl.DataFrame: ...
    @property
    def failures(self) -> list[dict[str, Any]]: ...
    @property
    def n_succeeded(self) -> int: ...
    @property
    def n_failed(self) -> int: ...
    def __repr__(self) -> str: ...

# ---------------------------------------------------------------------------
# Dwelling
# ---------------------------------------------------------------------------

class TimestepsIter:
    def __iter__(self) -> Iterator[Any]: ...
    def __next__(self) -> Any: ...
    def __repr__(self) -> str: ...

class Dwelling:
    @classmethod
    def from_hpxml(
        cls,
        hpxml: str,
        schedule: str,
        weather: str,
        *,
        start_time: str | datetime.datetime | None = ...,
        duration_s: int | float | datetime.timedelta = ...,
        time_res_s: int | float | datetime.timedelta = ...,
        defaults_path: str | None = ...,
        bldg_id: int = ...,
        master_seed: int = ...,
        output_verbosity: int = ...,
        output_path: str | None = ...,
        output_to_parquet: bool = ...,
        output_chunk_size: int = ...,
        civil_timezone: str | None = ...,
        setpoint_deadband_c: float | None = ...,
        **kwargs: Any,
    ) -> Dwelling: ...
    def initialize(self) -> None: ...
    def timesteps(self) -> TimestepsIter: ...
    def simulate(self) -> pl.DataFrame: ...
    def step(self) -> dict[str, Any]: ...
    def apply_control(self, name: str, signal: ControlSignal) -> None: ...
    def add_actor(self, actor: Actor) -> None: ...
    def add_actor_by_name(
        self,
        actor_type: str,
        name: str,
        params: dict[str, Any] | None = ...,
    ) -> None: ...
    def set_price_signal(self, signal: dict[str, float | None]) -> None: ...
    def set_grid_voltage(self, voltage_pu: float) -> None: ...
    # Available only when compiled with the "observe" feature.
    def enable_observer(self, capacity: int) -> None: ...
    def drain_observations(self) -> list[dict[str, Any]]: ...
    def telemetry(self) -> Telemetry: ...
    def equipment_descriptors(self) -> list[EquipmentDescriptor]: ...
    def equipment_names(self) -> list[str]: ...
    def add_battery(self, battery: Battery) -> None: ...
    def add_pv(self, pv: PV) -> None: ...
    def add_ev(self, ev: EV) -> None: ...
    def add_ev_with_driver(
        self,
        vehicle_id: VehicleId,
        archetype_id: EvArchetypeId,
        seed: int,
    ) -> None: ...
    def remove_equipment(self, name: str) -> None: ...
    def replace_equipment(self, name: str, equipment: Battery | PV | EV) -> None: ...
    def update_equipment(
        self,
        name: str,
        *,
        charging_curve: str | dict[str, Any] | None = ...,
        ocv_table: list[tuple[float, float]]
        | dict[str, Any]
        | pl.DataFrame
        | None = ...,
        uneg_table: list[tuple[float, float]]
        | dict[str, Any]
        | pl.DataFrame
        | None = ...,
    ) -> None: ...
    def set_equipment_lut(
        self, name: str, lut_type: LutType, data: Any
    ) -> None: ...
    def clear_equipment_lut(self, name: str, lut_type: LutType) -> None: ...
    def has_equipment_lut(self, name: str, lut_type: LutType) -> bool: ...
    def validate_control(self, name: str, signal: ControlSignal) -> bool: ...
    def results(self) -> pl.DataFrame: ...
    def metrics(self) -> SimulationMetrics: ...
    def reset_with_seed(self, seed: int) -> None: ...
    def save_state(self) -> bytes: ...
    def load_state(self, state: bytes) -> None: ...
    def set_solar_override(
        self,
        data: str
        | pl.DataFrame
        | dict[int, dict[str, Any]]
        | list[list[dict[str, Any]]],
    ) -> None: ...
    def clear_solar_override(self) -> None: ...
    def has_solar_override(self) -> bool: ...
    def surface_ids(self) -> list[int]: ...
    def roof_planes(self) -> list[RoofPlane]: ...
    def pv_candidates(self) -> list[PvCandidate]: ...
    def estimate_pv_capacity(
        self,
        target_kw: float,
        min_kw: float = ...,
        max_kw: float = ...,
    ) -> PvSizingResult: ...
    @property
    def config(self) -> SimulationConfig: ...
    def __repr__(self) -> str: ...

# ---------------------------------------------------------------------------
# Gym / RL
# ---------------------------------------------------------------------------

def batch_step(
    dwellings: list[Dwelling],
    actions: list[list[float]],
    observation_fields: list[str],
) -> list[dict[str, Any]]: ...
