"""Type stubs for the HARES Rust extension module."""

from __future__ import annotations

import datetime
from abc import abstractmethod
from collections.abc import Callable, Iterator
from typing import Any, NotRequired, TypedDict

import polars as pl

class StepResult(TypedDict):
    """Result from ``Dwelling.step()``.

    Zone temperatures are flattened as ``"Temperature - Indoor (C)"`` for zone 0,
    and ``"Temperature - Zone_N (C)"`` for other zones.
    """

    timestamp: datetime.datetime
    net_electric_power_kw: float
    hvac_heating_w: float
    hvac_cooling_w: float
    gas_power_w: float

class SteppableStepResult(StepResult):
    reactive_power_kvar: NotRequired[float]

class FleetStepEntry(TypedDict):
    """Single per-dwelling entry returned by ``SteppableFleet.step()``."""

    ok: bool
    bldg_id: int
    result: NotRequired[SteppableStepResult]
    error: NotRequired[str]

class SteppableBuildError(TypedDict):
    bldg_id: int
    error: str

# ---------------------------------------------------------------------------
# Enums
# ---------------------------------------------------------------------------

class EndUse:
    HVAC_HEATING: EndUse
    HVAC_COOLING: EndUse
    WATER_HEATING: EndUse
    LIGHTING: EndUse
    PLUG_LOADS: EndUse
    REFRIGERATION: EndUse
    VENTILATION: EndUse
    BATTERY: EndUse
    PV: EndUse
    EV: EndUse
    GENERATOR: EndUse
    DEHUMIDIFIER: EndUse
    OTHER: EndUse
    @staticmethod
    def custom(name: str) -> EndUse: ...
    def as_str(self) -> str: ...
    def is_standard(self) -> bool: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...

class FuelType:
    Electric: FuelType
    Gas: FuelType
    Propane: FuelType
    Oil: FuelType
    Wood: FuelType
    Coal: FuelType
    WoodPellet: FuelType
    NoFuel: FuelType
    @staticmethod
    def electric() -> FuelType: ...
    @staticmethod
    def gas() -> FuelType: ...
    @staticmethod
    def propane() -> FuelType: ...
    @staticmethod
    def oil() -> FuelType: ...
    @staticmethod
    def wood() -> FuelType: ...
    @staticmethod
    def coal() -> FuelType: ...
    @staticmethod
    def wood_pellet() -> FuelType: ...
    @staticmethod
    def no_fuel() -> FuelType: ...
    @staticmethod
    def from_str(name: str) -> FuelType: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...

class Mode:
    Off: Mode
    Heating: Mode
    Cooling: Mode
    Standby: Mode
    Defrost: Mode
    Charging: Mode
    Discharging: Mode
    HeatingHP: Mode
    HeatingER: Mode
    HeatingHPAndER: Mode
    HeatPumpWH: Mode
    BackupElement: Mode
    @staticmethod
    def off() -> Mode: ...
    @staticmethod
    def heating() -> Mode: ...
    @staticmethod
    def cooling() -> Mode: ...
    @staticmethod
    def standby() -> Mode: ...
    @staticmethod
    def defrost() -> Mode: ...
    @staticmethod
    def charging() -> Mode: ...
    @staticmethod
    def discharging() -> Mode: ...
    @staticmethod
    def heating_hp() -> Mode: ...
    @staticmethod
    def heating_er() -> Mode: ...
    @staticmethod
    def heating_hp_and_er() -> Mode: ...
    @staticmethod
    def heat_pump_wh() -> Mode: ...
    @staticmethod
    def backup_element() -> Mode: ...
    @staticmethod
    def from_str(name: str) -> Mode: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...

OperatingMode = Mode
PyMode = Mode

class DRLevel:
    Normal: DRLevel
    Moderate: DRLevel
    High: DRLevel
    Critical: DRLevel
    GridEmergency: DRLevel
    @staticmethod
    def normal() -> DRLevel: ...
    @staticmethod
    def moderate() -> DRLevel: ...
    @staticmethod
    def high() -> DRLevel: ...
    @staticmethod
    def critical() -> DRLevel: ...
    @staticmethod
    def grid_emergency() -> DRLevel: ...
    @staticmethod
    def from_str(name: str) -> DRLevel: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...

class ExecutionStage:
    Independent: ExecutionStage
    Electrical: ExecutionStage
    Thermal: ExecutionStage
    EnvelopeResolution: ExecutionStage
    @staticmethod
    def independent() -> ExecutionStage: ...
    @staticmethod
    def electrical() -> ExecutionStage: ...
    @staticmethod
    def thermal() -> ExecutionStage: ...
    @staticmethod
    def envelope_resolution() -> ExecutionStage: ...
    @staticmethod
    def from_str(name: str) -> ExecutionStage: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...

class FluidType:
    Water: FluidType
    Glycol: FluidType
    Refrigerant: FluidType
    @staticmethod
    def water() -> FluidType: ...
    @staticmethod
    def glycol() -> FluidType: ...
    @staticmethod
    def refrigerant() -> FluidType: ...
    @staticmethod
    def from_str(name: str) -> FluidType: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...

class InverterPriority:
    Watt: InverterPriority
    Var: InverterPriority
    Cpf: InverterPriority
    @staticmethod
    def watt() -> InverterPriority: ...
    @staticmethod
    def var() -> InverterPriority: ...
    @staticmethod
    def cpf() -> InverterPriority: ...
    @staticmethod
    def from_str(name: str) -> InverterPriority: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...

class IdealCapacityMode:
    Auto: IdealCapacityMode
    On: IdealCapacityMode
    Off: IdealCapacityMode
    @staticmethod
    def auto() -> IdealCapacityMode: ...
    @staticmethod
    def on() -> IdealCapacityMode: ...
    @staticmethod
    def off() -> IdealCapacityMode: ...
    @staticmethod
    def from_str(name: str) -> IdealCapacityMode: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...

class DutyCycleComponent:
    Compressor: DutyCycleComponent
    BackupElement: DutyCycleComponent
    @staticmethod
    def compressor() -> DutyCycleComponent: ...
    @staticmethod
    def backup_element() -> DutyCycleComponent: ...
    @staticmethod
    def from_str(name: str) -> DutyCycleComponent: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...

class SimStatus:
    @staticmethod
    def ok() -> SimStatus: ...
    @staticmethod
    def flagged(message: str | None = ...) -> SimStatus: ...
    @staticmethod
    def failed(message: str | None = ...) -> SimStatus: ...
    @staticmethod
    def from_str(name: str) -> SimStatus: ...
    @property
    def message(self) -> str | None: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...

class ExtrapolationStrategy:
    CLAMP: ExtrapolationStrategy
    NAN: ExtrapolationStrategy
    LINEAR: ExtrapolationStrategy
    NEAREST_NEIGHBOR: ExtrapolationStrategy
    def __repr__(self) -> str: ...
    def __eq__(self, other: object) -> bool: ...

class AggregationResolution:
    FifteenMin: AggregationResolution
    Hourly: AggregationResolution
    @staticmethod
    def fifteen_min() -> AggregationResolution: ...
    @staticmethod
    def hourly() -> AggregationResolution: ...
    @staticmethod
    def from_str(name: str) -> AggregationResolution: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...

class ResStockVersion:
    V2024_1: ResStockVersion
    V2024_2: ResStockVersion
    V2025_1: ResStockVersion
    @staticmethod
    def v2024_1() -> ResStockVersion: ...
    @staticmethod
    def v2024_2() -> ResStockVersion: ...
    @staticmethod
    def v2025_1() -> ResStockVersion: ...
    @staticmethod
    def from_str(name: str) -> ResStockVersion: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...

class ControlCapabilities:
    POWER_SETPOINT: ControlCapabilities
    SOC_TARGET: ControlCapabilities
    THERMAL_SETPOINT: ControlCapabilities
    POWER_LIMIT: ControlCapabilities
    MODE_OVERRIDE: ControlCapabilities
    DUTY_CYCLE: ControlCapabilities
    LOAD_FRACTION: ControlCapabilities
    GRID_CONNECT: ControlCapabilities
    SELF_CONSUMPTION: ControlCapabilities
    DEMAND_RESPONSE: ControlCapabilities
    PROTOCOL_NATIVE: ControlCapabilities
    HUMIDITY_SETPOINT: ControlCapabilities
    CURTAILMENT_PERCENT: ControlCapabilities
    REACTIVE_SETPOINT: ControlCapabilities
    POWER_FACTOR_SETPOINT: ControlCapabilities
    INVERTER_PRIORITY_MODE: ControlCapabilities
    IDEAL_CAPACITY: ControlCapabilities
    IDEAL_CAPACITY_MODE_OVERRIDE: ControlCapabilities
    EV_PLUG_IN: ControlCapabilities
    EV_DRIVE: ControlCapabilities
    EV_AWAY_CHARGE: ControlCapabilities
    EV_SET_READY_BY: ControlCapabilities
    @staticmethod
    def from_list(names: list[str]) -> ControlCapabilities: ...
    def __or__(self, other: ControlCapabilities) -> ControlCapabilities: ...
    def __contains__(self, other: ControlCapabilities) -> bool: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...

class LutType:
    ChargingCurve: LutType
    Ocv: LutType
    UNeg: LutType
    @staticmethod
    def charging_curve() -> LutType: ...
    @staticmethod
    def ocv() -> LutType: ...
    @staticmethod
    def uneg() -> LutType: ...
    @staticmethod
    def from_str(name: str) -> LutType: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...

class BatteryProductId:
    TeslaPw3: BatteryProductId
    TeslaPw2: BatteryProductId
    TeslaPw2Nca: BatteryProductId
    TeslaPw3X2: BatteryProductId
    EnphaseIq5p: BatteryProductId
    EnphaseIq5pX2: BatteryProductId
    EnphaseIq10c: BatteryProductId
    FranklinApower: BatteryProductId
    FranklinApower2: BatteryProductId
    FranklinApower2X2: BatteryProductId
    SolaredgeHome: BatteryProductId
    LgResu10h: BatteryProductId
    @staticmethod
    def tesla_pw3() -> BatteryProductId: ...
    @staticmethod
    def tesla_pw2() -> BatteryProductId: ...
    @staticmethod
    def tesla_pw2_nca() -> BatteryProductId: ...
    @staticmethod
    def tesla_pw3_x2() -> BatteryProductId: ...
    @staticmethod
    def enphase_iq5p() -> BatteryProductId: ...
    @staticmethod
    def enphase_iq5p_x2() -> BatteryProductId: ...
    @staticmethod
    def enphase_iq10c() -> BatteryProductId: ...
    @staticmethod
    def franklin_apower() -> BatteryProductId: ...
    @staticmethod
    def franklin_apower2() -> BatteryProductId: ...
    @staticmethod
    def franklin_apower2_x2() -> BatteryProductId: ...
    @staticmethod
    def solaredge_home() -> BatteryProductId: ...
    @staticmethod
    def lg_resu10h() -> BatteryProductId: ...
    @staticmethod
    def from_str(name: str) -> BatteryProductId: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...

class BatteryChemistry:
    Nmc: BatteryChemistry
    Lfp: BatteryChemistry
    Nca: BatteryChemistry
    Lto: BatteryChemistry
    @staticmethod
    def nmc() -> BatteryChemistry: ...
    @staticmethod
    def lfp() -> BatteryChemistry: ...
    @staticmethod
    def nca() -> BatteryChemistry: ...
    @staticmethod
    def lto() -> BatteryChemistry: ...
    @staticmethod
    def from_str(name: str) -> BatteryChemistry: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...

class ChargingLevel:
    L1: ChargingLevel
    L2: ChargingLevel
    @staticmethod
    def l1() -> ChargingLevel: ...
    @staticmethod
    def l2() -> ChargingLevel: ...
    @staticmethod
    def from_str(name: str) -> ChargingLevel: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...

class VehicleType:
    Bev: VehicleType
    Phev: VehicleType
    @staticmethod
    def bev() -> VehicleType: ...
    @staticmethod
    def phev() -> VehicleType: ...
    @staticmethod
    def from_str(name: str) -> VehicleType: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...

class EvConnectionState:
    HomePluggedIn: EvConnectionState
    AwayPluggedIn: EvConnectionState
    Disconnected: EvConnectionState
    @staticmethod
    def home_plugged_in() -> EvConnectionState: ...
    @staticmethod
    def away_plugged_in() -> EvConnectionState: ...
    @staticmethod
    def disconnected() -> EvConnectionState: ...
    @staticmethod
    def from_str(name: str) -> EvConnectionState: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...

class PlugInPolicy:
    @staticmethod
    def always() -> PlugInPolicy: ...
    @staticmethod
    def low_soc(threshold: float) -> PlugInPolicy: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...
    def __eq__(self, other: object) -> bool: ...

class DepartureConstraint:
    def __init__(
        self,
        day_filter: str = "weekdays",
        departure_minute: int = 480,
        target_soc: float = 0.8,
    ) -> None: ...
    @property
    def day_filter(self) -> str: ...
    @property
    def departure_minute(self) -> int: ...
    @property
    def target_soc(self) -> float: ...
    def __repr__(self) -> str: ...
    def __eq__(self, other: object) -> bool: ...

class ChargingStrategy:
    @staticmethod
    def immediate(target_soc: float) -> ChargingStrategy: ...
    @staticmethod
    def nightly(
        off_peak_start_hour: float, off_peak_end_hour: float, target_soc: float
    ) -> ChargingStrategy: ...
    @staticmethod
    def low_soc(threshold: float, target_soc: float) -> ChargingStrategy: ...
    @staticmethod
    def quick_then_wait(partial_soc: float) -> ChargingStrategy: ...
    @staticmethod
    def pre_departure(
        target_soc: float, departure_schedule: list[DepartureConstraint] | None = None
    ) -> ChargingStrategy: ...
    @staticmethod
    def tou_aware(
        target_soc: float,
        departure_schedule: list[DepartureConstraint] | None = None,
        charge_buffer_hours: float = 2.0,
    ) -> ChargingStrategy: ...
    @staticmethod
    def v2h(discharge_threshold_soc: float, min_soc: float) -> ChargingStrategy: ...
    @staticmethod
    def v2g(
        min_soc: float, max_export_kw: float, price_threshold: float
    ) -> ChargingStrategy: ...
    @staticmethod
    def solar_surplus(
        min_charge_rate_kw: float,
        departure_schedule: list[DepartureConstraint] | None = None,
    ) -> ChargingStrategy: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...
    def __eq__(self, other: object) -> bool: ...

class GridExportRule:
    SolarOnly: GridExportRule
    Unrestricted: GridExportRule
    Disabled: GridExportRule
    def __repr__(self) -> str: ...
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...

class StormWatchTrigger:
    ManualEnable: StormWatchTrigger
    WeatherSignal: StormWatchTrigger
    def __repr__(self) -> str: ...
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...

class RoofShape:
    Gable: RoofShape
    Hip: RoofShape
    Flat: RoofShape
    FlatEastWest: RoofShape
    def __repr__(self) -> str: ...
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...

class BmsAction:
    @staticmethod
    def charge(rate_fraction: float = 1.0) -> BmsAction: ...
    @staticmethod
    def discharge(rate_fraction: float = 1.0) -> BmsAction: ...
    @staticmethod
    def idle() -> BmsAction: ...
    @staticmethod
    def hold(target_soc: float = 0.5) -> BmsAction: ...
    def __repr__(self) -> str: ...
    def __eq__(self, other: object) -> bool: ...

class BmsScheduleWindow:
    def __init__(
        self,
        day: str,
        start_minute: int,
        end_minute: int,
        action: BmsAction,
    ) -> None: ...
    @property
    def day(self) -> str: ...
    @property
    def start_minute(self) -> int: ...
    @property
    def end_minute(self) -> int: ...
    @property
    def action(self) -> BmsAction: ...
    def __repr__(self) -> str: ...
    def __eq__(self, other: object) -> bool: ...

class BmsMode:
    @staticmethod
    def self_consumption(
        min_soc: float = 0.1,
        max_soc: float = 1.0,
        solar_only_charging: bool = False,
    ) -> BmsMode: ...
    @staticmethod
    def time_of_use_optimization(
        reserve_soc: float = 0.2,
        charge_threshold_percentile: float = 25.0,
        discharge_threshold_percentile: float = 75.0,
        solar_only_charging: bool = False,
    ) -> BmsMode: ...
    @staticmethod
    def backup_reserve(
        target_soc: float = 0.8,
        charge_from_grid: bool = True,
        charge_rate_fraction: float = 1.0,
    ) -> BmsMode: ...
    @staticmethod
    def demand_response(
        base_mode: BmsMode,
        dr_discharge_rate: float = 1.0,
        min_soc_during_dr: float = 0.1,
    ) -> BmsMode: ...
    @staticmethod
    def scheduled(windows: list[BmsScheduleWindow]) -> BmsMode: ...
    @staticmethod
    def storm_watch(
        target_soc: float = 1.0,
        trigger: str = "manual",
        base_mode: BmsMode | None = None,
        wind_speed_threshold_m_s: float = 25.0,
    ) -> BmsMode: ...
    @staticmethod
    def manual() -> BmsMode: ...
    def __repr__(self) -> str: ...
    def __eq__(self, other: object) -> bool: ...

# ---------------------------------------------------------------------------
# Control signals
# ---------------------------------------------------------------------------

class ControlSignal:
    @staticmethod
    def power_setpoint(
        kw: float, reactive_kvar: float | None = ...
    ) -> ControlSignal: ...
    @staticmethod
    def thermal_setpoint(
        heat_c: float | None = ...,
        cool_c: float | None = ...,
        deadband_c: float | None = ...,
    ) -> ControlSignal: ...
    @staticmethod
    def thermal_setpoint_delta(
        heating_delta_c: float | None = ...,
        cooling_delta_c: float | None = ...,
    ) -> ControlSignal: ...
    @staticmethod
    def soc_target(
        target: float,
        min: float | None = ...,
        max: float | None = ...,
    ) -> ControlSignal: ...
    @staticmethod
    def humidity_setpoint(
        target_rh: float,
        min_rh: float | None = ...,
        max_rh: float | None = ...,
    ) -> ControlSignal: ...
    @staticmethod
    def power_limit(
        max_power_kw: float,
        ramp_rate_kw_per_s: float | None = ...,
    ) -> ControlSignal: ...
    @staticmethod
    def duty_cycle(
        on_fraction: float,
        period_s: float | None = ...,
        component: DutyCycleComponent | None = ...,
    ) -> ControlSignal: ...
    @staticmethod
    def grid_connect(connected: bool) -> ControlSignal: ...
    @staticmethod
    def self_consumption(enabled: bool, solar_only_charging: bool) -> ControlSignal: ...
    @staticmethod
    def curtailment_percent(percent: float) -> ControlSignal: ...
    @staticmethod
    def reactive_setpoint(kvar: float) -> ControlSignal: ...
    @staticmethod
    def power_factor_setpoint(power_factor: float) -> ControlSignal: ...
    @staticmethod
    def inverter_priority_mode(priority: InverterPriority) -> ControlSignal: ...
    @staticmethod
    def protocol_native(protocol_id: int, payload: bytes) -> ControlSignal: ...
    @staticmethod
    def ideal_capacity_mode_override(mode: str) -> ControlSignal: ...
    @staticmethod
    def ideal_capacity(capacity_w: float) -> ControlSignal: ...
    @staticmethod
    def load_fraction(fraction: float) -> ControlSignal: ...
    @staticmethod
    def mode_override(mode: Mode) -> ControlSignal: ...
    @staticmethod
    def mode_override_str(mode: str) -> ControlSignal: ...
    @staticmethod
    def demand_response(
        level: DRLevel, duration_s: float | None = ...
    ) -> ControlSignal: ...
    @staticmethod
    def demand_response_str(
        level: str, duration_s: float | None = ...
    ) -> ControlSignal: ...
    @staticmethod
    def ev_plug_in(state: EvConnectionState) -> ControlSignal: ...
    @staticmethod
    def ev_drive(kwh: float) -> ControlSignal: ...
    @staticmethod
    def ev_away_charge(power_kw: float) -> ControlSignal: ...
    @staticmethod
    def ev_set_ready_by(departure_hour: float, target_soc: float) -> ControlSignal: ...
    @staticmethod
    def max_capacity_fraction(fraction: float) -> ControlSignal: ...
    @staticmethod
    def event_delay(delay_s: float) -> ControlSignal: ...
    @classmethod
    def from_dict(cls, d: dict[str, Any]) -> ControlSignal: ...
    def to_dict(self) -> dict[str, Any]: ...
    def __repr__(self) -> str: ...

# ---------------------------------------------------------------------------
# Actor system
# ---------------------------------------------------------------------------

class Priority:
    @staticmethod
    def schedule() -> Priority: ...
    @staticmethod
    def user_override() -> Priority: ...
    @staticmethod
    def grid() -> Priority: ...
    @staticmethod
    def safety() -> Priority: ...
    def __repr__(self) -> str: ...

class Signal:
    @staticmethod
    def thermal_setpoint(
        heating_c: float | None = ...,
        cooling_c: float | None = ...,
        deadband_c: float | None = ...,
    ) -> Signal: ...
    @staticmethod
    def thermal_setpoint_delta(
        heating_delta_c: float | None = ...,
        cooling_delta_c: float | None = ...,
    ) -> Signal: ...
    @staticmethod
    def mode_override(mode: Mode) -> Signal: ...
    @staticmethod
    def load_fraction(fraction: float) -> Signal: ...
    @staticmethod
    def power_limit(max_kw: float) -> Signal: ...
    @staticmethod
    def power_setpoint(
        active_power_kw: float, reactive_power_kvar: float | None = ...
    ) -> Signal: ...
    @staticmethod
    def soc_target(
        target_soc: float,
        min_soc: float | None = ...,
        max_soc: float | None = ...,
    ) -> Signal: ...
    @staticmethod
    def duty_cycle(on_fraction: float, period_s: float | None = ...) -> Signal: ...
    @staticmethod
    def demand_response(level: DRLevel, duration_s: float | None = ...) -> Signal: ...
    @staticmethod
    def ideal_capacity(capacity_w: float) -> Signal: ...
    @staticmethod
    def ev_plug_in(state: EvConnectionState) -> Signal: ...
    @staticmethod
    def ev_drive(kwh: float) -> Signal: ...
    @staticmethod
    def ev_set_ready_by(departure_hour: float, target_soc: float) -> Signal: ...
    @staticmethod
    def ev_away_charge(power_kw: float) -> Signal: ...
    @staticmethod
    def event_delay(delay_s: float) -> Signal: ...
    @staticmethod
    def humidity_setpoint(
        target_rh: float,
        min_rh: float | None = ...,
        max_rh: float | None = ...,
    ) -> Signal: ...
    @staticmethod
    def grid_connect(connected: bool) -> Signal: ...
    @staticmethod
    def self_consumption(enabled: bool, solar_only_charging: bool) -> Signal: ...
    @staticmethod
    def protocol_native(protocol_id: int, payload: bytes) -> Signal: ...
    @staticmethod
    def curtailment_percent(percent: float) -> Signal: ...
    @staticmethod
    def reactive_setpoint(kvar: float) -> Signal: ...
    @staticmethod
    def power_factor_setpoint(power_factor: float) -> Signal: ...
    @staticmethod
    def inverter_priority_mode(priority: InverterPriority) -> Signal: ...
    @staticmethod
    def ideal_capacity_mode_override(mode: IdealCapacityMode) -> Signal: ...
    @staticmethod
    def max_capacity_fraction(fraction: float) -> Signal: ...
    def __repr__(self) -> str: ...

class DispatchRequest:
    @property
    def target(self) -> str: ...
    @property
    def signal(self) -> Signal: ...
    @property
    def priority(self) -> Priority: ...
    @staticmethod
    def thermal_setpoint(
        target: str,
        heating_c: float | None = ...,
        cooling_c: float | None = ...,
        deadband_c: float | None = ...,
        priority: Priority | None = ...,
    ) -> DispatchRequest: ...
    @staticmethod
    def thermal_setpoint_delta(
        target: str,
        heating_delta_c: float | None = ...,
        cooling_delta_c: float | None = ...,
        priority: Priority | None = ...,
    ) -> DispatchRequest: ...
    @staticmethod
    def mode_override(
        target: str, mode: Mode, priority: Priority | None = ...
    ) -> DispatchRequest: ...
    @staticmethod
    def load_fraction(
        target: str, fraction: float, priority: Priority | None = ...
    ) -> DispatchRequest: ...
    @staticmethod
    def power_limit(
        target: str, max_kw: float, priority: Priority | None = ...
    ) -> DispatchRequest: ...
    @staticmethod
    def power_setpoint(
        target: str,
        active_power_kw: float,
        reactive_power_kvar: float | None = ...,
        priority: Priority | None = ...,
    ) -> DispatchRequest: ...
    @staticmethod
    def soc_target(
        target: str,
        target_soc: float,
        min_soc: float | None = ...,
        max_soc: float | None = ...,
        priority: Priority | None = ...,
    ) -> DispatchRequest: ...
    @staticmethod
    def duty_cycle(
        target: str,
        on_fraction: float,
        period_s: float | None = ...,
        priority: Priority | None = ...,
    ) -> DispatchRequest: ...
    @staticmethod
    def demand_response(
        target: str,
        level: DRLevel,
        duration_s: float | None = ...,
        priority: Priority | None = ...,
    ) -> DispatchRequest: ...
    @staticmethod
    def ideal_capacity(
        target: str, capacity_w: float, priority: Priority | None = ...
    ) -> DispatchRequest: ...
    @staticmethod
    def ev_plug_in(
        target: str, state: EvConnectionState, priority: Priority | None = ...
    ) -> DispatchRequest: ...
    @staticmethod
    def ev_drive(
        target: str, kwh: float, priority: Priority | None = ...
    ) -> DispatchRequest: ...
    @staticmethod
    def ev_away_charge(
        target: str, power_kw: float, priority: Priority | None = ...
    ) -> DispatchRequest: ...
    @staticmethod
    def ev_set_ready_by(
        target: str,
        departure_hour: float,
        target_soc: float,
        priority: Priority | None = ...,
    ) -> DispatchRequest: ...
    @staticmethod
    def event_delay(
        target: str, delay_s: float, priority: Priority | None = ...
    ) -> DispatchRequest: ...
    @staticmethod
    def humidity_setpoint(
        target: str,
        target_rh: float,
        min_rh: float | None = ...,
        max_rh: float | None = ...,
        priority: Priority | None = ...,
    ) -> DispatchRequest: ...
    @staticmethod
    def grid_connect(
        target: str, connected: bool, priority: Priority | None = ...
    ) -> DispatchRequest: ...
    @staticmethod
    def self_consumption(
        target: str,
        enabled: bool,
        solar_only_charging: bool,
        priority: Priority | None = ...,
    ) -> DispatchRequest: ...
    @staticmethod
    def protocol_native(
        target: str,
        protocol_id: int,
        payload: bytes,
        priority: Priority | None = ...,
    ) -> DispatchRequest: ...
    @staticmethod
    def curtailment_percent(
        target: str, percent: float, priority: Priority | None = ...
    ) -> DispatchRequest: ...
    @staticmethod
    def reactive_setpoint(
        target: str, kvar: float, priority: Priority | None = ...
    ) -> DispatchRequest: ...
    @staticmethod
    def power_factor_setpoint(
        target: str, power_factor: float, priority: Priority | None = ...
    ) -> DispatchRequest: ...
    @staticmethod
    def inverter_priority_mode(
        target: str,
        priority_enum: InverterPriority,
        priority: Priority | None = ...,
    ) -> DispatchRequest: ...
    @staticmethod
    def ideal_capacity_mode_override(
        target: str, mode: IdealCapacityMode, priority: Priority | None = ...
    ) -> DispatchRequest: ...
    @staticmethod
    def max_capacity_fraction(
        target: str, fraction: float, priority: Priority | None = ...
    ) -> DispatchRequest: ...
    def __repr__(self) -> str: ...

class Actor:
    def __init__(self) -> None: ...
    @property
    def name(self) -> str: ...
    @name.setter
    def name(self, value: str) -> None: ...
    @abstractmethod
    def decide(self, env: dict[str, Any]) -> list[DispatchRequest]: ...

# ---------------------------------------------------------------------------
# Telemetry
# ---------------------------------------------------------------------------

class Telemetry:
    def zone(self) -> dict[str, Any]: ...
    # Non-authoritative diagnostics dict; use Dwelling.equipment()[...].core_output
    # for simulation-critical typed values.
    def equipment(self) -> dict[str, Any]: ...
    @property
    def timestep_index(self) -> int: ...
    @property
    def current_time(self) -> datetime.datetime: ...
    @property
    def total_power_kw(self) -> float: ...
    @property
    def reactive_power_kvar(self) -> float: ...
    def __repr__(self) -> str: ...

class CoreOutput:
    @property
    def electric_kw(self) -> float | None: ...
    @property
    def electric_convention(self) -> str | None: ...
    @property
    def reactive_power_kvar(self) -> float | None: ...
    @property
    def fuel_w(self) -> float | None: ...
    @property
    def fuel_type(self) -> str | None: ...
    @property
    def operating_mode(self) -> str | None: ...
    @property
    def soc(self) -> float | None: ...
    def __repr__(self) -> str: ...

class Equipment:
    @property
    def name(self) -> str: ...
    @property
    def descriptor(self) -> EquipmentDescriptor: ...
    @property
    def core_output(self) -> CoreOutput: ...
    def telemetry(self) -> dict[str, float]: ...
    def __repr__(self) -> str: ...

# ---------------------------------------------------------------------------
# Equipment introspection
# ---------------------------------------------------------------------------

class TelemetryField:
    @property
    def name(self) -> str: ...
    @property
    def unit(self) -> str: ...
    @property
    def description(self) -> str: ...
    def __repr__(self) -> str: ...

class EquipmentDescriptor:
    @property
    def id(self) -> int: ...
    @property
    def name(self) -> str: ...
    @property
    def end_use(self) -> EndUse: ...
    @property
    def equipment_type(self) -> str: ...
    @property
    def zone(self) -> int | None: ...
    @property
    def fuel_type(self) -> FuelType: ...
    @property
    def stage(self) -> ExecutionStage: ...
    @property
    def control_capabilities(self) -> ControlCapabilities: ...
    @property
    def telemetry_fields(self) -> list[TelemetryField]: ...
    def __repr__(self) -> str: ...

# ---------------------------------------------------------------------------
# Equipment types
# ---------------------------------------------------------------------------

class Battery:
    @property
    def name(self) -> str: ...
    @property
    def capacity_kwh(self) -> float: ...
    @property
    def max_charge_kw(self) -> float | None: ...
    @property
    def max_discharge_kw(self) -> float | None: ...
    @property
    def chemistry(self) -> BatteryChemistry | None: ...
    @property
    def initial_soc(self) -> float | None: ...
    @property
    def min_soc(self) -> float | None: ...
    @property
    def max_soc(self) -> float | None: ...
    @property
    def inverter_efficiency(self) -> float | None: ...
    @property
    def charge_efficiency(self) -> float | None: ...
    @property
    def discharge_efficiency(self) -> float | None: ...
    @property
    def self_discharge_pct_per_day(self) -> float | None: ...
    @property
    def standby_power_w(self) -> float | None: ...
    @property
    def import_limit_w(self) -> float | None: ...
    @property
    def export_limit_w(self) -> float | None: ...
    @property
    def n_series(self) -> int | None: ...
    @property
    def n_parallel(self) -> int | None: ...
    @property
    def cell_resistance_ohm(self) -> float | None: ...
    @property
    def heater_power_w(self) -> float | None: ...
    @property
    def heater_threshold_c(self) -> float | None: ...
    @property
    def min_charge_temp_c(self) -> float | None: ...
    @property
    def full_power_temp_c(self) -> float | None: ...
    @property
    def cell_thermal_mass_j_per_k(self) -> float | None: ...
    @property
    def cell_ua_w_per_k(self) -> float | None: ...
    def __init__(
        self,
        name: str,
        capacity_kwh: float,
        max_charge_kw: float | None = ...,
        max_discharge_kw: float | None = ...,
        chemistry: BatteryChemistry | None = ...,
        initial_soc: float | None = ...,
        min_soc: float | None = ...,
        max_soc: float | None = ...,
        inverter_efficiency: float | None = ...,
        charge_efficiency: float | None = ...,
        discharge_efficiency: float | None = ...,
        self_discharge_pct_per_day: float | None = ...,
        standby_power_w: float | None = ...,
        import_limit_w: float | None = ...,
        export_limit_w: float | None = ...,
        n_series: int | None = ...,
        n_parallel: int | None = ...,
        cell_resistance_ohm: float | None = ...,
        heater_power_w: float | None = ...,
        heater_threshold_c: float | None = ...,
        min_charge_temp_c: float | None = ...,
        full_power_temp_c: float | None = ...,
        cell_thermal_mass_j_per_k: float | None = ...,
        cell_ua_w_per_k: float | None = ...,
        charging_curve_lut: str | dict[str, Any] | None = ...,
        ocv_table: list[tuple[float, float]] | dict[str, Any] | None = ...,
        uneg_table: list[tuple[float, float]] | dict[str, Any] | None = ...,
    ) -> None: ...
    @staticmethod
    def from_product(product_id: BatteryProductId) -> Battery: ...
    @staticmethod
    def by_product_id(id: str) -> Battery: ...
    @staticmethod
    def product_catalog() -> list[BatteryProductId]: ...
    @staticmethod
    def tesla_pw3() -> Battery: ...
    @staticmethod
    def tesla_pw2() -> Battery: ...
    @staticmethod
    def tesla_pw3_x2() -> Battery: ...
    @staticmethod
    def enphase_iq5p() -> Battery: ...
    @staticmethod
    def enphase_iq5p_x2() -> Battery: ...
    @staticmethod
    def enphase_iq10c() -> Battery: ...
    @staticmethod
    def franklin_apower() -> Battery: ...
    @staticmethod
    def franklin_apower2() -> Battery: ...
    @staticmethod
    def franklin_apower2_x2() -> Battery: ...
    @staticmethod
    def solaredge_home() -> Battery: ...
    @staticmethod
    def lg_resu10h() -> Battery: ...
    def __repr__(self) -> str: ...

class PvSoilingConfig:
    @property
    def cleaning_threshold_mm(self) -> float: ...
    @property
    def loss_rate_per_day(self) -> float: ...
    @property
    def grace_period_days(self) -> float: ...
    @property
    def max_loss(self) -> float: ...
    @property
    def initial_loss(self) -> float: ...
    @property
    def rain_accum_hours(self) -> float: ...
    def __init__(
        self,
        cleaning_threshold_mm: float = ...,
        loss_rate_per_day: float = ...,
        grace_period_days: float = ...,
        max_loss: float = ...,
        initial_loss: float = ...,
        rain_accum_hours: float = ...,
    ) -> None: ...
    def __repr__(self) -> str: ...

class PV:
    @property
    def name(self) -> str: ...
    @property
    def capacity_kw(self) -> float: ...
    @property
    def tilt(self) -> float: ...
    @property
    def azimuth(self) -> float: ...
    @property
    def soiling(self) -> PvSoilingConfig | None: ...
    def __init__(
        self,
        name: str,
        capacity_kw: float,
        tilt: float,
        azimuth: float,
        soiling: PvSoilingConfig | None = ...,
    ) -> None: ...
    def __repr__(self) -> str: ...

class EvArchetypeId:
    DailyCommuterL2: EvArchetypeId
    DailyCommuterL1: EvArchetypeId
    LongCommuterL2: EvArchetypeId
    WfhOccasional: EvArchetypeId
    WfhL1Minimal: EvArchetypeId
    HeavyUseSuv: EvArchetypeId
    ShiftWorker: EvArchetypeId
    WeekendWarrior: EvArchetypeId
    WorkplaceCharger: EvArchetypeId
    RetireeL1: EvArchetypeId
    PhevCommuter: EvArchetypeId
    TouOptimizerCa: EvArchetypeId
    @staticmethod
    def daily_commuter_l2() -> EvArchetypeId: ...
    @staticmethod
    def daily_commuter_l1() -> EvArchetypeId: ...
    @staticmethod
    def long_commuter_l2() -> EvArchetypeId: ...
    @staticmethod
    def wfh_occasional() -> EvArchetypeId: ...
    @staticmethod
    def wfh_l1_minimal() -> EvArchetypeId: ...
    @staticmethod
    def heavy_use_suv() -> EvArchetypeId: ...
    @staticmethod
    def shift_worker() -> EvArchetypeId: ...
    @staticmethod
    def weekend_warrior() -> EvArchetypeId: ...
    @staticmethod
    def workplace_charger() -> EvArchetypeId: ...
    @staticmethod
    def retiree_l1() -> EvArchetypeId: ...
    @staticmethod
    def phev_commuter() -> EvArchetypeId: ...
    @staticmethod
    def tou_optimizer_ca() -> EvArchetypeId: ...
    @staticmethod
    def from_str(name: str) -> EvArchetypeId: ...
    @staticmethod
    def archetype_catalog() -> list[EvArchetypeId]: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...

class VehicleId:
    TeslaModelYLr: VehicleId
    TeslaModelYSr: VehicleId
    TeslaModel3Lr: VehicleId
    ChevyBoltEv: VehicleId
    ChevyBoltEuv: VehicleId
    FordMacheSr: VehicleId
    FordMacheEr: VehicleId
    FordLightningEr: VehicleId
    HyundaiIoniq5Lr: VehicleId
    NissanLeaf30: VehicleId
    Jeep4xe: VehicleId
    ToyotaRav4Prime: VehicleId
    ChevyVoltGen1: VehicleId
    @staticmethod
    def tesla_model_y_lr() -> VehicleId: ...
    @staticmethod
    def tesla_model_y_sr() -> VehicleId: ...
    @staticmethod
    def tesla_model_3_lr() -> VehicleId: ...
    @staticmethod
    def chevy_bolt_ev() -> VehicleId: ...
    @staticmethod
    def chevy_bolt_euv() -> VehicleId: ...
    @staticmethod
    def ford_mache_sr() -> VehicleId: ...
    @staticmethod
    def ford_mache_er() -> VehicleId: ...
    @staticmethod
    def ford_lightning_er() -> VehicleId: ...
    @staticmethod
    def hyundai_ioniq5_lr() -> VehicleId: ...
    @staticmethod
    def nissan_leaf30() -> VehicleId: ...
    @staticmethod
    def jeep_4xe() -> VehicleId: ...
    @staticmethod
    def toyota_rav4_prime() -> VehicleId: ...
    @staticmethod
    def chevy_volt_gen1() -> VehicleId: ...
    @staticmethod
    def from_str(name: str) -> VehicleId: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...

class EV:
    @property
    def name(self) -> str: ...
    @property
    def capacity_kwh(self) -> float | None: ...
    @property
    def max_charging_kw(self) -> float | None: ...
    @property
    def initial_soc(self) -> float | None: ...
    @property
    def initial_connection_state(self) -> EvConnectionState | None: ...
    def __init__(
        self,
        name: str,
        capacity_kwh: float | None = ...,
        max_charging_kw: float | None = ...,
        initial_soc: float | None = ...,
        initial_connection_state: EvConnectionState | None = ...,
        charging_curve_lut: str | dict[str, Any] | None = ...,
    ) -> None: ...
    @staticmethod
    def from_vehicle(vehicle_id: VehicleId) -> EV: ...
    @staticmethod
    def from_vehicle_with_archetype(
        vehicle_id: VehicleId,
        archetype_id: EvArchetypeId,
        seed: int,
    ) -> EV: ...
    @staticmethod
    def by_vehicle_id(id: str) -> EV: ...
    @staticmethod
    def vehicle_catalog() -> list[VehicleId]: ...
    @staticmethod
    def tesla_model_y_lr() -> EV: ...
    @staticmethod
    def tesla_model_y_sr() -> EV: ...
    @staticmethod
    def tesla_model_3_lr() -> EV: ...
    @staticmethod
    def chevy_bolt_ev() -> EV: ...
    @staticmethod
    def chevy_bolt_euv() -> EV: ...
    @staticmethod
    def ford_mache_sr() -> EV: ...
    @staticmethod
    def ford_mache_er() -> EV: ...
    @staticmethod
    def ford_lightning_er() -> EV: ...
    @staticmethod
    def hyundai_ioniq5_lr() -> EV: ...
    @staticmethod
    def nissan_leaf30() -> EV: ...
    @staticmethod
    def jeep_4xe() -> EV: ...
    @staticmethod
    def toyota_rav4_prime() -> EV: ...
    @staticmethod
    def chevy_volt_gen1() -> EV: ...
    def __repr__(self) -> str: ...

class ProtocolBridge:
    """Protocol-native control signal bridge.

    Receives ``ProtocolNative`` control signals and either records their
    dispatch in telemetry or routes them through configured handlers.
    Registers protocol IDs the bridge should recognise; an empty or omitted
    ``registered_protocols`` means accept-all.

    ``json_handlers`` specifies protocol IDs for which a JSON payload handler
    is configured. Each entry creates a ``JsonHandler`` that parses UTF-8 JSON
    payloads of the form ``[{"target": "...", "signal": {...}}]``. Without at
    least one handler the bridge records dispatch in telemetry but never routes
    commands to target equipment.
    """

    @property
    def name(self) -> str: ...
    @property
    def registered_protocols(self) -> list[int]: ...
    @property
    def json_handlers(self) -> list[int]: ...
    def __init__(
        self,
        name: str,
        registered_protocols: list[int] | None = ...,
        json_handlers: list[int] | None = ...,
    ) -> None: ...

# ---------------------------------------------------------------------------
# HVAC equipment types
# ---------------------------------------------------------------------------

class GasFurnace:
    def __init__(
        self,
        name: str,
        autosize: bool = ...,
        capacity_w: float | None = ...,
        afue: float | None = ...,
        zone_id: int | None = ...,
        fan_power_w: float | None = ...,
        number_of_speeds: int | None = ...,
        heating_setpoint_c: float | None = ...,
        cooling_setpoint_c: float | None = ...,
        oversizing_factor: float | None = ...,
    ) -> None: ...
    @property
    def name(self) -> str: ...
    @property
    def autosize(self) -> bool: ...
    @property
    def capacity_w(self) -> float | None: ...
    @property
    def afue(self) -> float | None: ...
    @property
    def zone_id(self) -> int | None: ...
    @property
    def fan_power_w(self) -> float | None: ...
    @property
    def number_of_speeds(self) -> int | None: ...
    @property
    def heating_setpoint_c(self) -> float | None: ...
    @property
    def cooling_setpoint_c(self) -> float | None: ...
    @property
    def oversizing_factor(self) -> float | None: ...
    def __repr__(self) -> str: ...

class AirConditioner:
    def __init__(
        self,
        name: str,
        autosize: bool = ...,
        capacity_w: float | None = ...,
        eir: float | None = ...,
        seer: float | None = ...,
        zone_id: int | None = ...,
        shr: float | None = ...,
        number_of_speeds: int | None = ...,
        fan_power_w: float | None = ...,
        heating_setpoint_c: float | None = ...,
        cooling_setpoint_c: float | None = ...,
        oversizing_factor: float | None = ...,
    ) -> None: ...
    @property
    def name(self) -> str: ...
    @property
    def autosize(self) -> bool: ...
    @property
    def capacity_w(self) -> float | None: ...
    @property
    def eir(self) -> float | None: ...
    @property
    def seer(self) -> float | None: ...
    @property
    def zone_id(self) -> int | None: ...
    @property
    def shr(self) -> float | None: ...
    @property
    def number_of_speeds(self) -> int | None: ...
    @property
    def fan_power_w(self) -> float | None: ...
    @property
    def heating_setpoint_c(self) -> float | None: ...
    @property
    def cooling_setpoint_c(self) -> float | None: ...
    @property
    def oversizing_factor(self) -> float | None: ...
    def __repr__(self) -> str: ...

class ASHPHeater:
    def __init__(
        self,
        name: str,
        autosize: bool = ...,
        capacity_w: float | None = ...,
        hspf: float | None = ...,
        zone_id: int | None = ...,
        is_mini_split: bool | None = ...,
        backup_capacity_w: float | None = ...,
        backup_fuel: str | None = ...,
        fan_power_w: float | None = ...,
        heating_setpoint_c: float | None = ...,
        cooling_setpoint_c: float | None = ...,
        oversizing_factor: float | None = ...,
    ) -> None: ...
    @property
    def name(self) -> str: ...
    @property
    def autosize(self) -> bool: ...
    @property
    def capacity_w(self) -> float | None: ...
    @property
    def hspf(self) -> float | None: ...
    @property
    def zone_id(self) -> int | None: ...
    @property
    def is_mini_split(self) -> bool | None: ...
    @property
    def backup_capacity_w(self) -> float | None: ...
    @property
    def backup_fuel(self) -> str | None: ...
    @property
    def fan_power_w(self) -> float | None: ...
    @property
    def heating_setpoint_c(self) -> float | None: ...
    @property
    def cooling_setpoint_c(self) -> float | None: ...
    @property
    def oversizing_factor(self) -> float | None: ...
    def __repr__(self) -> str: ...

class ASHPCooler:
    def __init__(
        self,
        name: str,
        autosize: bool = ...,
        capacity_w: float | None = ...,
        seer: float | None = ...,
        zone_id: int | None = ...,
        is_mini_split: bool | None = ...,
        shr: float | None = ...,
        fan_power_w: float | None = ...,
        heating_setpoint_c: float | None = ...,
        cooling_setpoint_c: float | None = ...,
        oversizing_factor: float | None = ...,
    ) -> None: ...
    @property
    def name(self) -> str: ...
    @property
    def autosize(self) -> bool: ...
    @property
    def capacity_w(self) -> float | None: ...
    @property
    def seer(self) -> float | None: ...
    @property
    def zone_id(self) -> int | None: ...
    @property
    def is_mini_split(self) -> bool | None: ...
    @property
    def shr(self) -> float | None: ...
    @property
    def fan_power_w(self) -> float | None: ...
    @property
    def heating_setpoint_c(self) -> float | None: ...
    @property
    def cooling_setpoint_c(self) -> float | None: ...
    @property
    def oversizing_factor(self) -> float | None: ...
    def __repr__(self) -> str: ...

class ElectricBaseboard:
    def __init__(
        self,
        name: str,
        autosize: bool = ...,
        capacity_w: float | None = ...,
        eir: float | None = ...,
        zone_id: int | None = ...,
        heating_setpoint_c: float | None = ...,
        cooling_setpoint_c: float | None = ...,
        oversizing_factor: float | None = ...,
    ) -> None: ...
    @property
    def name(self) -> str: ...
    @property
    def autosize(self) -> bool: ...
    @property
    def capacity_w(self) -> float | None: ...
    @property
    def eir(self) -> float | None: ...
    @property
    def zone_id(self) -> int | None: ...
    @property
    def heating_setpoint_c(self) -> float | None: ...
    @property
    def cooling_setpoint_c(self) -> float | None: ...
    @property
    def oversizing_factor(self) -> float | None: ...
    def __repr__(self) -> str: ...

class IdealHVAC:
    def __init__(
        self,
        name: str,
        autosize: bool = ...,
        zone_id: int | None = ...,
        heating_capacity_w: float | None = ...,
        cooling_capacity_w: float | None = ...,
        heating_setpoint_c: float | None = ...,
        cooling_setpoint_c: float | None = ...,
        deadband_c: float | None = ...,
        oversizing_factor: float | None = ...,
    ) -> None: ...
    @property
    def name(self) -> str: ...
    @property
    def autosize(self) -> bool: ...
    @property
    def zone_id(self) -> int | None: ...
    @property
    def heating_capacity_w(self) -> float | None: ...
    @property
    def cooling_capacity_w(self) -> float | None: ...
    @property
    def heating_setpoint_c(self) -> float | None: ...
    @property
    def cooling_setpoint_c(self) -> float | None: ...
    @property
    def deadband_c(self) -> float | None: ...
    @property
    def oversizing_factor(self) -> float | None: ...
    def __repr__(self) -> str: ...

# ---------------------------------------------------------------------------
# Water heater equipment types
# ---------------------------------------------------------------------------

class GasWaterHeater:
    def __init__(
        self,
        name: str,
        autosize: bool = ...,
        tank_volume_m3: float | None = ...,
        uniform_energy_factor: float | None = ...,
        heating_capacity_w: float | None = ...,
        setpoint_c: float | None = ...,
        zone_id: int | None = ...,
        avg_water_draw_l_per_day: float | None = ...,
        oversizing_factor: float | None = ...,
    ) -> None: ...
    @property
    def name(self) -> str: ...
    @property
    def autosize(self) -> bool: ...
    @property
    def tank_volume_m3(self) -> float | None: ...
    @property
    def uniform_energy_factor(self) -> float | None: ...
    @property
    def heating_capacity_w(self) -> float | None: ...
    @property
    def setpoint_c(self) -> float | None: ...
    @property
    def zone_id(self) -> int | None: ...
    @property
    def avg_water_draw_l_per_day(self) -> float | None: ...
    @property
    def oversizing_factor(self) -> float | None: ...
    def __repr__(self) -> str: ...

class ElectricResistanceWH:
    def __init__(
        self,
        name: str,
        autosize: bool = ...,
        tank_volume_m3: float | None = ...,
        uniform_energy_factor: float | None = ...,
        heating_capacity_w: float | None = ...,
        setpoint_c: float | None = ...,
        zone_id: int | None = ...,
        avg_water_draw_l_per_day: float | None = ...,
        oversizing_factor: float | None = ...,
    ) -> None: ...
    @property
    def name(self) -> str: ...
    @property
    def autosize(self) -> bool: ...
    @property
    def tank_volume_m3(self) -> float | None: ...
    @property
    def uniform_energy_factor(self) -> float | None: ...
    @property
    def heating_capacity_w(self) -> float | None: ...
    @property
    def setpoint_c(self) -> float | None: ...
    @property
    def zone_id(self) -> int | None: ...
    @property
    def avg_water_draw_l_per_day(self) -> float | None: ...
    @property
    def oversizing_factor(self) -> float | None: ...
    def __repr__(self) -> str: ...

class HeatPumpWH:
    def __init__(
        self,
        name: str,
        autosize: bool = ...,
        tank_volume_m3: float | None = ...,
        cop: float | None = ...,
        backup_capacity_w: float | None = ...,
        compressor_power_w: float | None = ...,
        setpoint_c: float | None = ...,
        zone_id: int | None = ...,
        avg_water_draw_l_per_day: float | None = ...,
        oversizing_factor: float | None = ...,
    ) -> None: ...
    @property
    def name(self) -> str: ...
    @property
    def autosize(self) -> bool: ...
    @property
    def tank_volume_m3(self) -> float | None: ...
    @property
    def cop(self) -> float | None: ...
    @property
    def backup_capacity_w(self) -> float | None: ...
    @property
    def compressor_power_w(self) -> float | None: ...
    @property
    def setpoint_c(self) -> float | None: ...
    @property
    def zone_id(self) -> int | None: ...
    @property
    def avg_water_draw_l_per_day(self) -> float | None: ...
    @property
    def oversizing_factor(self) -> float | None: ...
    def __repr__(self) -> str: ...

# ---------------------------------------------------------------------------
# Tariff types
# ---------------------------------------------------------------------------

class ElectricTariff:
    @classmethod
    def from_urdb_json(cls, path: str) -> ElectricTariff: ...
    @classmethod
    def from_json(cls, json_str: str) -> ElectricTariff: ...
    @classmethod
    def from_dict(cls, dict: dict[str, Any]) -> ElectricTariff: ...
    @classmethod
    def builder(cls) -> TariffBuilder: ...
    def to_dict(self) -> dict[str, Any]: ...
    @property
    def name(self) -> str | None: ...
    def __repr__(self) -> str: ...
    def __eq__(self, other: object) -> bool: ...

class TariffBuilder:
    def set_name(self, name: str) -> TariffBuilder: ...
    def add_tou_period(
        self, name: str, windows: list[dict[str, Any]], season: str
    ) -> TariffBuilder: ...
    def add_energy_rate(
        self, period_name: str, season: str, rate: float
    ) -> TariffBuilder: ...
    def add_demand_rate(
        self,
        rate_per_kw: float,
        season: str,
        period_name: str | None = None,
        ratchet_fraction: float | None = None,
        lookback_months: int | None = None,
    ) -> TariffBuilder: ...
    def set_tiered_rates(
        self, season: str, thresholds_kwh: list[float], rates_per_kwh: list[float]
    ) -> TariffBuilder: ...
    def set_fixed_charges(
        self, monthly_usd: float = 0.0, daily_usd: float = 0.0
    ) -> TariffBuilder: ...
    def set_export_net_metering(self) -> TariffBuilder: ...
    def set_export_net_billing(
        self, tou_credits: list[dict[str, Any]]
    ) -> TariffBuilder: ...
    def set_export_flat_rate(self, rate: float) -> TariffBuilder: ...
    def set_minimum_charge(self, amount: float) -> TariffBuilder: ...
    def add_demand_tou_period(
        self, name: str, windows: list[dict[str, Any]], season: str
    ) -> TariffBuilder: ...
    def set_billing_cycle(self, cycle_days: int | None = ...) -> TariffBuilder: ...
    def set_seasonal_split(
        self, summer_start_month: int, summer_end_month: int
    ) -> TariffBuilder: ...
    def set_demand_window_minutes(self, minutes: int = 15) -> TariffBuilder: ...
    def build(self) -> ElectricTariff: ...
    def __repr__(self) -> str: ...

class GasTariff:
    @classmethod
    def from_dict(cls, dict: dict[str, Any]) -> GasTariff: ...
    @classmethod
    def from_json(cls, json_str: str) -> GasTariff: ...
    @classmethod
    def builder(cls) -> GasTariffBuilder: ...
    def to_dict(self) -> dict[str, Any]: ...
    @property
    def name(self) -> str | None: ...
    def __repr__(self) -> str: ...
    def __eq__(self, other: object) -> bool: ...

class GasTariffBuilder:
    def set_name(self, name: str) -> GasTariffBuilder: ...
    def set_tiered_rates(
        self, season: str, thresholds_therms: list[float], rates_per_therm: list[float]
    ) -> GasTariffBuilder: ...
    def set_fixed_charges(
        self, monthly_usd: float = 0.0, daily_usd: float = 0.0
    ) -> GasTariffBuilder: ...
    def set_billing_cycle(self, cycle_days: int | None = ...) -> GasTariffBuilder: ...
    def set_seasonal_split(
        self, summer_start_month: int, summer_end_month: int
    ) -> GasTariffBuilder: ...
    def build(self) -> GasTariff: ...
    def __repr__(self) -> str: ...

class BillingPeriodSummary:
    @property
    def period_start(self) -> datetime.datetime: ...
    @property
    def period_end(self) -> datetime.datetime: ...
    @property
    def energy_charge_usd(self) -> float: ...
    @property
    def demand_charge_usd(self) -> float: ...
    @property
    def fixed_charge_usd(self) -> float: ...
    @property
    def export_credit_usd(self) -> float: ...
    @property
    def net_bill_usd(self) -> float: ...
    @property
    def peak_demand_kw(self) -> float: ...
    @property
    def total_import_kwh(self) -> float: ...
    @property
    def total_export_kwh(self) -> float: ...
    def to_dict(self) -> dict[str, Any]: ...
    def __repr__(self) -> str: ...

class TariffTelemetry:
    @property
    def period_name(self) -> str: ...
    @property
    def current_rate_usd_per_kwh(self) -> float: ...
    @property
    def export_rate_usd_per_kwh(self) -> float: ...
    @property
    def cumulative_import_kwh(self) -> float: ...
    @property
    def cumulative_export_kwh(self) -> float: ...
    @property
    def peak_demand_kw(self) -> float: ...
    @property
    def cumulative_energy_cost_usd(self) -> float: ...
    def to_dict(self) -> dict[str, Any]: ...
    def __repr__(self) -> str: ...

# ---------------------------------------------------------------------------
# PV sizing
# ---------------------------------------------------------------------------

class RoofPlane:
    def __init__(
        self,
        area_m2: float,
        tilt_deg: float = 0.0,
        azimuth_deg: float | None = None,
        material: str | None = None,
        boundary_index: int | None = None,
        index: int = 0,
    ) -> None: ...
    @property
    def index(self) -> int: ...
    @property
    def area_m2(self) -> float: ...
    @property
    def tilt_deg(self) -> float: ...
    @property
    def azimuth_deg(self) -> float | None: ...
    @property
    def material(self) -> str | None: ...
    @property
    def boundary_index(self) -> int | None: ...

class UsableRoofArea:
    @property
    def best_plane_idx(self) -> int: ...
    @property
    def usable_m2(self) -> float: ...
    @property
    def max_panels(self) -> int: ...
    @property
    def max_capacity_kw(self) -> float: ...
    @property
    def roof_shape(self) -> RoofShape: ...
    @property
    def azimuth_deg(self) -> float: ...
    @property
    def tilt_deg(self) -> float: ...

class PvCandidate:
    @property
    def plane_idx(self) -> int: ...
    @property
    def azimuth_deg(self) -> float: ...
    @property
    def tilt_deg(self) -> float: ...
    @property
    def usable_m2(self) -> float: ...
    @property
    def max_panels(self) -> int: ...
    @property
    def max_capacity_kw(self) -> float: ...
    @property
    def solar_score(self) -> float: ...
    @property
    def roof_shape(self) -> RoofShape: ...
    @property
    def boundary_index(self) -> int | None: ...

class PvSizingResult:
    @property
    def capacity_kw(self) -> float: ...
    @property
    def num_panels(self) -> int: ...
    @property
    def collector_area_m2(self) -> float: ...
    @property
    def array_azimuth_deg(self) -> float: ...
    @property
    def array_tilt_deg(self) -> float: ...
    @property
    def system_losses_fraction(self) -> float: ...
    @property
    def max_roof_capacity_kw(self) -> float: ...
    @property
    def panel_watts(self) -> int: ...
    @property
    def electrical_constraint_binding(self) -> bool: ...
    @property
    def max_ac_kw(self) -> float | None: ...
    @property
    def max_backfeed_amps(self) -> float | None: ...

def compute_annual_diffuse_fraction(ghi: list[float], dhi: list[float]) -> float: ...
def default_diffuse_fraction() -> float: ...
def is_north_facing(azimuth_deg: float) -> bool: ...
def infer_roof_shape(
    roof_planes: list[RoofPlane],
    facility_type: str | None = None,
    latitude: float | None = None,
    wall_azimuths: list[float] | None = None,
) -> RoofShape: ...
def compute_usable_area(
    roof_planes: list[RoofPlane],
    roof_shape: RoofShape,
    *,
    wall_azimuths: list[float] | None = None,
    latitude: float | None = None,
    panel_watts: int | None = None,
    panel_area_m2: float | None = None,
    diffuse_fraction: float | None = None,
    roof_shape_user_override: bool = False,
) -> UsableRoofArea: ...
def enumerate_pv_candidates(
    roof_planes: list[RoofPlane],
    roof_shape: RoofShape,
    *,
    wall_azimuths: list[float] | None = None,
    latitude: float | None = None,
    panel_watts: int | None = None,
    panel_area_m2: float | None = None,
    diffuse_fraction: float | None = None,
    roof_shape_user_override: bool = False,
) -> list[PvCandidate]: ...
def size_pv_system(
    usable: UsableRoofArea,
    target_kw: float,
    *,
    min_kw: float = 2.0,
    max_kw: float = 14.0,
    system_losses: float | None = None,
    panel_watts: int | None = None,
    panel_area_m2: float | None = None,
    inverter_kw_ac: float | None = None,
    max_dc_ac_ratio: float | None = None,
    main_panel_ampacity: int | None = None,
    main_breaker_ampacity: int | None = None,
) -> PvSizingResult: ...

def required_main_panel_ampacity(
    target_ac_kw: float,
    *,
    main_breaker_amps: int | None = None,
) -> int: ...

# ---------------------------------------------------------------------------
# Configuration
# ---------------------------------------------------------------------------

class SimulationConfig:
    def __init__(
        self,
        start_time: str | None = ...,
        duration_s: int | None = ...,
        time_res_s: int | None = ...,
        output_verbosity: int | None = ...,
        output_path: str | None = ...,
        write_output: bool | None = ...,
        output_to_parquet: bool | None = ...,
        output_chunk_size: int | None = ...,
        master_seed: int | None = ...,
        civil_timezone: str | None = ...,
        setpoint_deadband_c: float | None = ...,
    ) -> None: ...
    @property
    def start_time(self) -> str: ...
    @start_time.setter
    def start_time(self, value: str) -> None: ...
    @property
    def duration_s(self) -> int: ...
    @duration_s.setter
    def duration_s(self, value: int) -> None: ...
    @property
    def time_res_s(self) -> int: ...
    @time_res_s.setter
    def time_res_s(self, value: int) -> None: ...
    @property
    def output_verbosity(self) -> int: ...
    @property
    def output_path(self) -> str | None: ...
    @property
    def write_output(self) -> bool: ...
    @property
    def output_to_parquet(self) -> bool: ...
    @property
    def output_chunk_size(self) -> int: ...
    @property
    def setpoint_deadband_c(self) -> float | None: ...
    @property
    def master_seed(self) -> int: ...
    @property
    def civil_timezone(self) -> str | None: ...
    def __repr__(self) -> str: ...

class DwellingConfig:
    def __init__(
        self,
        hpxml: str,
        schedule: str,
        weather: str,
        config: SimulationConfig | None = ...,
        defaults_path: str | None = ...,
        bldg_id: int | None = ...,
        initialization_duration: int | None = ...,
        resample_overrides: dict[str, str] | None = ...,
        overrides: dict[str, Any] | None = ...,
    ) -> None: ...
    @property
    def hpxml(self) -> str: ...
    @property
    def schedule(self) -> str: ...
    @property
    def weather(self) -> str: ...
    @property
    def config(self) -> SimulationConfig | None: ...
    @property
    def defaults_path(self) -> str | None: ...
    @property
    def bldg_id(self) -> int: ...
    @property
    def initialization_duration(self) -> int | None: ...
    @property
    def resample_overrides(self) -> dict[str, str] | None: ...
    @property
    def overrides(self) -> dict[str, Any] | None: ...
    def __repr__(self) -> str: ...

# ---------------------------------------------------------------------------
# Metrics (frozen)
# ---------------------------------------------------------------------------

class TotalEnergyKwh:
    @property
    def net_energy_kwh(self) -> float: ...
    @property
    def gross_consumption_kwh(self) -> float: ...
    @property
    def gross_pv_generation_kwh(self) -> float: ...
    @property
    def per_end_use(self) -> dict[str, float]: ...
    @property
    def duration_hours(self) -> float: ...
    def __repr__(self) -> str: ...

class RollingPeakKw:
    @property
    def peak_15min_kw(self) -> float: ...
    @property
    def peak_30min_kw(self) -> float: ...
    @property
    def peak_60min_kw(self) -> float: ...
    def __repr__(self) -> str: ...

class PeakPowerKw:
    @property
    def per_end_use(self) -> dict[str, float]: ...
    @property
    def rolling_15min_kw(self) -> float: ...
    @property
    def rolling_30min_kw(self) -> float: ...
    @property
    def rolling_60min_kw(self) -> float: ...
    def __repr__(self) -> str: ...

class GridInteractionMetrics:
    @property
    def peak_import_kw(self) -> float: ...
    @property
    def peak_export_kw(self) -> float: ...
    def __repr__(self) -> str: ...

class EnvelopeComponentLoadsKwh:
    @property
    def window_solar_kwh(self) -> float: ...
    @property
    def opaque_solar_lwr_kwh(self) -> float: ...
    @property
    def interior_lwr_kwh(self) -> float: ...
    @property
    def infiltration_kwh(self) -> float: ...
    @property
    def ventilation_kwh(self) -> float: ...
    @property
    def hvac_heating_kwh(self) -> float: ...
    @property
    def hvac_cooling_kwh(self) -> float: ...
    @property
    def internal_gains_kwh(self) -> float: ...
    @property
    def duct_loss_kwh(self) -> float: ...
    def __repr__(self) -> str: ...

class EfficiencyMetrics:
    @property
    def hvac_heating_cop(self) -> float | None: ...
    @property
    def hvac_cooling_cop(self) -> float | None: ...
    @property
    def water_heater_cop(self) -> float | None: ...
    @property
    def battery_round_trip_efficiency(self) -> float | None: ...
    def __repr__(self) -> str: ...

class GasEnergyMetrics:
    @property
    def total_therms(self) -> float: ...
    @property
    def total_kwh_equivalent(self) -> float: ...
    def __repr__(self) -> str: ...

class SimulationMetrics:
    @property
    def total_energy_kwh(self) -> TotalEnergyKwh: ...
    @property
    def peak_power_kw(self) -> PeakPowerKw: ...
    @property
    def comfort_hours(self) -> float | None: ...
    @property
    def unmet_load_hours(self) -> float | None: ...
    @property
    def renewable_energy_fraction(self) -> float | None: ...
    @property
    def grid_interaction(self) -> GridInteractionMetrics: ...
    @property
    def envelope_loads_kwh(self) -> EnvelopeComponentLoadsKwh | None: ...
    @property
    def efficiency(self) -> EfficiencyMetrics: ...
    @property
    def rows_with_partial_setpoint_data_fraction(self) -> float | None: ...
    @property
    def simulation_duration_hours(self) -> float: ...
    @property
    def coverage(self) -> str: ...
    @property
    def nan_step_count(self) -> int: ...
    @property
    def metrics_reliability(self) -> str: ...
    @property
    def combined_total_energy_kwh(self) -> float: ...
    @property
    def gas_energy(self) -> GasEnergyMetrics | None: ...
    def __repr__(self) -> str: ...

# ---------------------------------------------------------------------------
# Weather
# ---------------------------------------------------------------------------

class WeatherTimeSeries:
    def to_polars(self) -> pl.DataFrame: ...
    def __len__(self) -> int: ...
    def __repr__(self) -> str: ...
    @property
    def location(self) -> str: ...
    @property
    def latitude(self) -> float: ...
    @property
    def longitude(self) -> float: ...
    @property
    def elevation_m(self) -> float: ...
    @property
    def timezone_offset_h(self) -> float: ...
    @property
    def source_step_secs(self) -> int: ...
    @property
    def midpoint_offset_secs(self) -> int: ...
    @property
    def surface_albedo(self) -> list[float] | None: ...

def parse_weather(path: str) -> WeatherTimeSeries: ...
def parse_epw(path: str) -> WeatherTimeSeries: ...
def parse_psm3(path: str) -> WeatherTimeSeries: ...
def parse_tmy3(path: str) -> WeatherTimeSeries: ...
def parse_resstock_csv(
    path: str,
    elevation_m: float,
    latitude: float,
    longitude: float,
    timezone_offset_h: float,
) -> WeatherTimeSeries: ...

# ---------------------------------------------------------------------------
# Fleet
# ---------------------------------------------------------------------------

class Fleet:
    @classmethod
    def from_buildings(
        cls,
        configs: list[DwellingConfig],
        sample_weights: list[float] | None = ...,
    ) -> Fleet: ...
    @classmethod
    def from_resstock(
        cls,
        metadata_path: str,
        hpxml_dir: str,
        weather_dir: str,
        filter: dict[str, str] | None = ...,
        resstock_version: ResStockVersion | str | None = ...,
    ) -> Fleet: ...
    def simulate(
        self,
        n_threads: int | None = ...,
        resolution: AggregationResolution | str | None = ...,
        raise_on_failure: bool | None = ...,
        progress: Callable[[int, int], None] | None = ...,
    ) -> FleetResults: ...
    def __len__(self) -> int: ...
    def __repr__(self) -> str: ...

class SteppableFleet:
    @classmethod
    def from_configs(
        cls,
        configs: list[DwellingConfig],
        n_threads: int = ...,
    ) -> SteppableFleet: ...
    def step(self) -> list[FleetStepEntry]: ...
    @property
    def build_errors(self) -> list[SteppableBuildError]: ...
    def set_grid_voltage(self, dwelling_index: int, voltage_pu: float) -> None: ...
    def set_grid_voltage_all(self, voltage_pu: float) -> None: ...
    def apply_control(
        self,
        dwelling_index: int,
        name: str,
        signal: ControlSignal,
    ) -> None: ...
    def telemetry(self, dwelling_index: int) -> Telemetry: ...
    def is_finished(self) -> bool: ...
    def time_res_s(self) -> float: ...
    def total_steps(self) -> int: ...
    def current_step(self) -> int: ...
    def __len__(self) -> int: ...
    def __repr__(self) -> str: ...

class FleetResults:
    @property
    def per_dwelling_metrics(self) -> pl.DataFrame: ...
    @property
    def aggregate_timeseries(self) -> pl.DataFrame: ...
    @property
    def failures(self) -> list[dict[str, Any]]: ...
    @property
    def n_succeeded(self) -> int: ...
    @property
    def n_failed(self) -> int: ...
    def __repr__(self) -> str: ...

# ---------------------------------------------------------------------------
# Exceptions
# ---------------------------------------------------------------------------

class FatalDwellingError(Exception):
    """Raised when a Dwelling is fatally poisoned (irrecoverable internal state)."""

# ---------------------------------------------------------------------------
# DwellingBlueprint
# ---------------------------------------------------------------------------

class DwellingBlueprint:
    @classmethod
    def from_hpxml(
        cls,
        hpxml: str,
        schedule: str,
        weather: str,
        *,
        start_time: str | datetime.datetime | None = ...,
        duration_s: int | float | datetime.timedelta = ...,
        time_res_s: int | float | datetime.timedelta = ...,
        defaults_path: str | None = ...,
        bldg_id: int = ...,
        master_seed: int = ...,
        output_verbosity: int = ...,
        output_path: str | None = ...,
        write_output: bool = ...,
        output_to_parquet: bool = ...,
        output_chunk_size: int = ...,
        civil_timezone: str | None = ...,
        setpoint_deadband_c: float | None = ...,
        initialization_duration: int | float | datetime.timedelta | None = ...,
        resample_overrides: dict[str, str] | None = ...,
        overrides: dict[str, Any] | None = ...,
        config: SimulationConfig | None = ...,
    ) -> DwellingBlueprint: ...
    def equipment_names(self) -> list[str]: ...
    def remove_equipment(self, name: str) -> None: ...
    def remove_equipment_by_end_use(self, end_uses: EndUse | list[EndUse]) -> int: ...
    def add_equipment(self, obj: Any) -> None: ...
    def build(self) -> Dwelling: ...
    def __repr__(self) -> str: ...

# ---------------------------------------------------------------------------
# Dwelling
# ---------------------------------------------------------------------------

class TimestepsIter:
    def __iter__(self) -> Iterator[Any]: ...
    def __next__(self) -> Any: ...
    def __repr__(self) -> str: ...

class Dwelling:
    @classmethod
    def from_hpxml(
        cls,
        hpxml: str,
        schedule: str,
        weather: str,
        *,
        start_time: str | datetime.datetime | None = ...,
        duration_s: int | float | datetime.timedelta = ...,
        time_res_s: int | float | datetime.timedelta = ...,
        defaults_path: str | None = ...,
        bldg_id: int = ...,
        master_seed: int = ...,
        output_verbosity: int = ...,
        output_path: str | None = ...,
        write_output: bool = ...,
        output_to_parquet: bool = ...,
        output_chunk_size: int = ...,
        civil_timezone: str | None = ...,
        setpoint_deadband_c: float | None = ...,
        initialization_duration: int | float | datetime.timedelta | None = ...,
        resample_overrides: dict[str, str] | None = ...,
        overrides: dict[str, Any] | None = ...,
        config: SimulationConfig | None = ...,
    ) -> Dwelling: ...
    def initialize(self) -> None: ...
    def timesteps(self) -> TimestepsIter: ...
    def simulate(self) -> pl.DataFrame: ...
    def step(self) -> StepResult: ...
    def apply_control(self, name: str, signal: ControlSignal) -> None: ...
    def add_actor(self, actor: Actor) -> None: ...
    def add_actor_by_name(
        self,
        actor_type: str,
        name: str,
        params: dict[str, Any] | None = ...,
    ) -> None: ...
    def set_price_signal(self, signal: dict[str, float | None]) -> None: ...
    def set_grid_voltage(self, voltage_pu: float) -> None: ...
    # Available only when compiled with the "observe" feature.
    def enable_observer(self, capacity: int) -> None: ...
    def drain_observations(self) -> list[dict[str, Any]]: ...
    def telemetry(self) -> Telemetry: ...
    def equipment_descriptors(self) -> list[EquipmentDescriptor]: ...
    def equipment(self) -> list[Equipment]: ...
    def equipment_names(self) -> list[str]: ...
    def add_battery(self, battery: Battery) -> None: ...
    def add_pv(self, pv: PV) -> None: ...
    def add_ev(self, ev: EV) -> None: ...
    def add_protocol_bridge(self, bridge: ProtocolBridge) -> None: ...
    def add_ev_with_driver(
        self,
        vehicle_id: VehicleId,
        archetype_id: EvArchetypeId,
        seed: int,
    ) -> None: ...
    def remove_equipment(self, name: str) -> None: ...
    def replace_equipment(self, name: str, equipment: Battery | PV | EV) -> None: ...
    def update_equipment(
        self,
        name: str,
        *,
        charging_curve: str | dict[str, Any] | None = ...,
        ocv_table: list[tuple[float, float]]
        | dict[str, Any]
        | pl.DataFrame
        | None = ...,
        uneg_table: list[tuple[float, float]]
        | dict[str, Any]
        | pl.DataFrame
        | None = ...,
    ) -> None: ...
    def set_equipment_lut(self, name: str, lut_type: LutType, data: Any) -> None: ...
    def clear_equipment_lut(self, name: str, lut_type: LutType) -> None: ...
    def has_equipment_lut(self, name: str, lut_type: LutType) -> bool: ...
    def validate_control(self, name: str, signal: ControlSignal) -> bool: ...
    def results(self) -> pl.DataFrame: ...
    def metrics(self) -> SimulationMetrics: ...
    def reset_with_seed(self, seed: int) -> None: ...
    def save_state(self) -> bytes: ...
    def load_state(self, state: bytes) -> None: ...
    def save_checkpoint(self) -> bytes: ...
    def restore_building_state(self, state: bytes) -> None: ...
    def set_solar_override(
        self,
        data: str
        | pl.DataFrame
        | dict[int, dict[str, Any]]
        | list[list[dict[str, Any]]],
    ) -> None: ...
    def clear_solar_override(self) -> None: ...
    def has_solar_override(self) -> bool: ...
    def surface_ids(self) -> list[int]: ...
    def roof_planes(self) -> list[RoofPlane]: ...
    def pv_candidates(self) -> list[PvCandidate]: ...
    def estimate_pv_capacity(
        self,
        target_kw: float,
        min_kw: float = ...,
        max_kw: float = ...,
        main_panel_ampacity: int | None = ...,
        main_breaker_ampacity: int | None = ...,
    ) -> PvSizingResult: ...
    def set_electric_tariff(
        self,
        tariff: ElectricTariff,
        timezone: str | None = ...,
    ) -> None: ...
    def set_gas_tariff(self, tariff: GasTariff) -> None: ...
    def finalize_billing(self) -> None: ...
    def billing_summaries(self) -> list[BillingPeriodSummary]: ...
    def tariff_telemetry(self) -> TariffTelemetry | None: ...
    @property
    def dwelling_fatal(self) -> bool: ...
    @property
    def config(self) -> SimulationConfig: ...
    def __repr__(self) -> str: ...

# ---------------------------------------------------------------------------
# Gym / RL
# ---------------------------------------------------------------------------

def batch_step(
    dwellings: list[Dwelling],
    actions: list[list[float]],
    observation_fields: list[str],
) -> list[dict[str, Any]]: ...
