"""Typed surface of the optional ``helics`` package used by HARES.

The published ``helics`` wheel ships no py.typed marker, so pyright cannot
resolve any of its attributes. This stub models the HELICS 3.6.x Python API
surface HARES uses. Handle types are the structural protocols defined in
``ochre_next.helics._types`` so values flow between the real bindings and
the HARES wrappers without casts.
"""

from typing import Protocol

from ochre_next.helics._types import (
    HelicsBrokerLike,
    HelicsCoreLike,
    HelicsFederateInfoLike,
    HelicsFederateLike,
    HelicsPublicationLike,
    HelicsSubscriptionLike,
)

HELICS_TIME_MAXTIME: float
HELICS_FLAG_TERMINATE_ON_ERROR: int
HELICS_PROPERTY_TIME_PERIOD: int
HELICS_PROPERTY_TIME_OFFSET: int


class _Cli:
    def run(self, config_path: str) -> None: ...


# The helics 3.6.1 wheel does not expose ``cli`` at all (runners reach it on
# builds that bundle the HELICS CLI); callers must go through ``getattr``.
cli: _Cli | None


class HelicsFederateInfo:
    # The 3.6.1 wheel requires the raw C handle, which only
    # ``helicsCreateFederateInfo()`` produces, and registers a finalizer for it.
    def __init__(self, handle: int, cleanup: bool = True) -> None: ...
    core_type: str
    core_init: str
    core_init_string: str
    property: dict[int, float]


def helicsCreateFederateInfo() -> HelicsFederateInfoLike: ...
def helicsCreateValueFederate(name: str, info: HelicsFederateInfoLike) -> HelicsFederateLike: ...
def helicsFederateInfoSetCoreTypeFromString(info: HelicsFederateInfoLike, core_type: str) -> None: ...
def helicsFederateInfoSetCoreName(info: HelicsFederateInfoLike, name: str) -> None: ...
def helicsFederateInfoSetCoreInitString(info: HelicsFederateInfoLike, init_string: str) -> None: ...
def helicsFederateInfoSetTimeProperty(info: HelicsFederateInfoLike, property_key: int, value: float) -> None: ...
def helicsFederateSetFlagOption(fed: HelicsFederateLike, flag: int, value: int) -> None: ...
def helicsFederateDisconnectAsync(fed: HelicsFederateLike) -> None: ...
def helicsFederateGetPublicationCount(fed: HelicsFederateLike) -> int: ...
def helicsFederateGetInputCount(fed: HelicsFederateLike) -> int: ...
def helicsFederateLocalError(fed: HelicsFederateLike, error_code: int, message: str) -> None: ...
def helicsPublicationSetInfo(pub: HelicsPublicationLike, info: str) -> None: ...
def helicsPublicationGetInfo(pub: HelicsPublicationLike) -> str: ...
def helicsCreateBroker(core_type: str, name: str, init_string: str) -> HelicsBrokerLike: ...
def helicsCreateCore(type: str, name: str = "", init_string: str = "") -> HelicsCoreLike: ...
def helicsCoreConnect(core: HelicsCoreLike) -> bool: ...
def helicsCoreDisconnect(core: HelicsCoreLike) -> None: ...
def helicsCoreWaitForDisconnect(core: HelicsCoreLike, ms_to_wait: int) -> bool: ...
def helicsCoreFree(core: HelicsCoreLike) -> None: ...
def helicsBrokerDisconnect(broker: HelicsBrokerLike) -> None: ...
def helicsBrokerIsConnected(broker: HelicsBrokerLike) -> bool: ...
def helicsBrokerGetAddress(broker: HelicsBrokerLike) -> str: ...
def helicsCloseLibrary() -> None: ...
def helicsCleanupLibrary() -> None: ...


class HelicsException(Exception): ...


class HelicsBroker:
    def __init__(self, core_type: str, name: str, init_string: str) -> None: ...
    def disconnect(self) -> None: ...
    def is_connected(self) -> bool: ...
    def get_address(self) -> str: ...
    address: str
