//! Conditioned HVAC oracle tests: compare HARES HVAC behavior against
//! OCHRE reference output with equipment active.
//!
//! Two modes per scenario:
//! - Ideal mode: HARES clears all equipment, injects IdealHvac with solver
//!   back-calculated capacity. Temperature should track setpoint tightly (< 0.5°C MAE).
//! - Dynamic mode: HARES keeps native ASHP equipment with on/off thermostat cycling,
//!   stripping non-HVAC equipment to match OCHRE fixture.
//!   Temperature oscillates within deadband (< 2.0°C MAE from OCHRE).
//!
//! OCHRE fixtures generated by tests/python/generate_conditioned_oracle.py.

#[cfg(feature = "observe")]
#[cfg(test)]
mod tests {
    use std::collections::BTreeMap;
    use std::fs;
    use std::path::PathBuf;

    use chrono::{Duration, FixedOffset, TimeZone};
    use hares_core::{Dwelling, DwellingConfig, SimulationConfig};
    use hares_equipment::config::ConfigValue;
    use hares_equipment::{EquipmentConfig, EquipmentRegistry};
    use hares_io::OutputFormat;
    use hares_physics::solar::GlazingCurve;
    use hares_types::{EndUse, ZoneId};

    fn examples_dir() -> PathBuf {
        PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("../../data/examples")
    }

    fn project_root() -> PathBuf {
        PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("../..")
    }

    fn fixture_dir(mode: &str, scenario: &str) -> PathBuf {
        project_root().join(format!("tests/fixtures/conditioned_{mode}/{scenario}"))
    }

    fn beopt_conditioned_config(scenario: &str, output_path: PathBuf) -> DwellingConfig {
        // Both HARES and OCHRE treat timestamps as local time internally —
        // .hour() is used directly for schedule evaluation regardless of offset.
        // We use Denver's real offset for clarity, but only the wall-clock
        // digits (hour, minute) actually affect behavior.
        let denver = FixedOffset::west_opt(7 * 3600).expect("Denver UTC-7 offset");
        let (start_time, duration) = match scenario {
            "beopt_spring_72h" => (
                denver.with_ymd_and_hms(2019, 5, 5, 12, 0, 0).unwrap(),
                Duration::hours(72),
            ),
            "beopt_summer_48h" => (
                denver.with_ymd_and_hms(2019, 7, 15, 12, 0, 0).unwrap(),
                Duration::hours(48),
            ),
            "beopt_winter_48h" => (
                denver.with_ymd_and_hms(2019, 1, 15, 12, 0, 0).unwrap(),
                Duration::hours(48),
            ),
            other => panic!("unknown conditioned scenario: {other}"),
        };

        DwellingConfig {
            hpxml_path: examples_dir().join("BEopt_example.xml"),
            schedule_path: examples_dir().join("BEopt_example_schedule.csv"),
            weather_path: examples_dir().join("USA_CO_Denver.Intl.AP.725650_TMY3.epw"),
            defaults_path: Some(project_root().join("defaults")),
            sim_config: SimulationConfig {
                start_time,
                duration,
                time_res: Duration::minutes(1),
                output_verbosity: 6,
                output_path: Some(output_path),
                output_format: OutputFormat::Csv,
                output_chunk_size: 1024,
                setpoint_deadband_c: None,
                master_seed: 42,
                civil_timezone: None,
            },
            overrides: None,
            bldg_id: 1,
            initialization_duration: None,
            resample_overrides: Some(hares_io::ResampleOverrides::ochre_compat()),
        }
    }

    fn parse_csv_columns(path: &PathBuf) -> BTreeMap<String, Vec<f64>> {
        let contents = fs::read_to_string(path).expect("read CSV");
        let mut lines = contents.lines();
        let header = lines.next().expect("header line");
        let columns: Vec<&str> = header.split(',').map(|s| s.trim()).collect();

        let mut data: BTreeMap<String, Vec<f64>> = BTreeMap::new();
        for col in &columns {
            data.insert(col.to_string(), Vec::new());
        }

        for line in lines {
            if line.trim().is_empty() {
                continue;
            }
            let fields: Vec<&str> = line.split(',').collect();
            for (i, field) in fields.iter().enumerate() {
                if i < columns.len() {
                    if let Ok(v) = field.trim().parse::<f64>() {
                        data.get_mut(columns[i]).unwrap().push(v);
                    }
                }
            }
        }
        data
    }

    fn fahrenheit_to_celsius(f: f64) -> f64 {
        (f - 32.0) * 5.0 / 9.0
    }

    /// BEopt_example setpoints: 65°F night (0-5, 23), 71°F day (6-22) heating;
    /// 76°F constant cooling.
    fn beopt_setpoints_c() -> (Vec<f64>, Vec<f64>) {
        let heating_f: [f64; 24] = [
            65.0, 65.0, 65.0, 65.0, 65.0, 65.0, 71.0, 71.0, 71.0, 71.0, 71.0, 71.0, 71.0, 71.0,
            71.0, 71.0, 71.0, 71.0, 71.0, 71.0, 71.0, 71.0, 71.0, 65.0,
        ];
        let cooling_f: [f64; 24] = [76.0; 24];
        let heating_c: Vec<f64> = heating_f
            .iter()
            .map(|f| fahrenheit_to_celsius(*f))
            .collect();
        let cooling_c: Vec<f64> = cooling_f
            .iter()
            .map(|f| fahrenheit_to_celsius(*f))
            .collect();
        (heating_c, cooling_c)
    }

    fn create_ideal_hvac_config(
        zone_id: ZoneId,
        heating_setpoints_c: &[f64],
        cooling_setpoints_c: &[f64],
    ) -> EquipmentConfig {
        let mut raw_config = std::collections::HashMap::new();
        raw_config.insert("zone_id".to_string(), ConfigValue::Float(zone_id.0 as f64));
        raw_config.insert(
            "ideal_capacity_mode".to_string(),
            ConfigValue::Text("on".to_string()),
        );
        raw_config.insert(
            "heating_capacity_w".to_string(),
            ConfigValue::Float(10_000.0),
        );
        raw_config.insert(
            "cooling_capacity_w".to_string(),
            ConfigValue::Float(10_000.0),
        );
        raw_config.insert(
            "heating_weekday_setpoints_c".to_string(),
            ConfigValue::FloatArray(heating_setpoints_c.to_vec()),
        );
        raw_config.insert(
            "heating_weekend_setpoints_c".to_string(),
            ConfigValue::FloatArray(heating_setpoints_c.to_vec()),
        );
        raw_config.insert(
            "cooling_weekday_setpoints_c".to_string(),
            ConfigValue::FloatArray(cooling_setpoints_c.to_vec()),
        );
        raw_config.insert(
            "cooling_weekend_setpoints_c".to_string(),
            ConfigValue::FloatArray(cooling_setpoints_c.to_vec()),
        );

        EquipmentConfig {
            name: "Ideal HVAC".to_string(),
            ochre_class: "Ideal HVAC".to_string(),
            raw_config,
        }
    }

    struct Check {
        name: String,
        ochre: f64,
        hares: f64,
        passed: bool,
        note: String,
    }

    impl Check {
        fn compare_mae(name: &str, mae: f64, max_mae: f64, note: &str) -> Self {
            let passed = mae <= max_mae;
            let note = if passed {
                format!("OK (MAE={mae:.3}) — {note}")
            } else {
                format!("DEVIATION MAE={mae:.3} > {max_mae:.3} — {note}")
            };
            Check {
                name: name.to_string(),
                ochre: 0.0,
                hares: mae,
                passed,
                note,
            }
        }

        fn compare_mean(
            name: &str,
            ochre_mean: f64,
            hares_mean: Option<f64>,
            tolerance_abs: f64,
            tolerance_pct: f64,
            note: &str,
        ) -> Self {
            let hares = hares_mean.unwrap_or(f64::NAN);
            let delta = (hares - ochre_mean).abs();
            let deviation_pct = if ochre_mean.abs() > 1.0 {
                delta / ochre_mean.abs() * 100.0
            } else {
                f64::INFINITY
            };
            let passed = hares.is_nan() || delta <= tolerance_abs || deviation_pct <= tolerance_pct;
            let note = if hares.is_nan() {
                format!("MISSING — {note}")
            } else if passed {
                if delta <= tolerance_abs {
                    format!("OK (Δ={delta:.1}W < {tolerance_abs:.0}W) — {note}")
                } else {
                    format!("OK ({deviation_pct:+.1}%) — {note}")
                }
            } else {
                format!("DEVIATION Δ={delta:.1}W ({deviation_pct:+.1}%) — {note}")
            };
            Check {
                name: name.to_string(),
                ochre: ochre_mean,
                hares,
                passed,
                note,
            }
        }
    }

    fn run_conditioned_scenario(scenario: &str, use_ideal: bool) {
        let mode_name = if use_ideal { "ideal" } else { "dynamic" };
        let output_path =
            std::env::temp_dir().join(format!("hares_conditioned_{mode_name}_{scenario}.csv"));
        let _ = fs::remove_file(&output_path);

        let config = beopt_conditioned_config(scenario, output_path.clone());
        let n_steps = {
            let dur = config.sim_config.duration;
            let res = config.sim_config.time_res;
            (dur.num_seconds() / res.num_seconds()) as usize
        };

        let mut dwelling = Dwelling::from_config(config).expect("Dwelling::from_config");

        let initial_equipment: Vec<String> = dwelling
            .equipment()
            .iter()
            .map(|e| e.descriptor().name.clone())
            .collect();
        eprintln!("[{mode_name}] Initial equipment: {initial_equipment:?}");

        if use_ideal {
            // Ideal mode: replace all equipment with IdealHvac.
            // IdealHvac uses solver back-calculation (IdealCapacityMode::On)
            // to compute exact capacity needed to track setpoint.
            let (heating_c, cooling_c) = beopt_setpoints_c();

            dwelling.clear_equipment();

            let ideal_config = create_ideal_hvac_config(ZoneId(1), &heating_c, &cooling_c);
            let registry = EquipmentRegistry::new();
            let mut ideal_hvac = registry
                .create("Ideal HVAC", ideal_config.clone())
                .expect("create Ideal HVAC");

            // Init with dwelling's actual environment state (real zone temps,
            // weather, time) — NOT a dummy environment.
            ideal_hvac
                .init(&ideal_config, dwelling.latest_env())
                .expect("init Ideal HVAC");

            dwelling.add_equipment(ideal_hvac);

            eprintln!(
                "[{mode_name}] Equipment after IdealHvac injection: {:?}",
                dwelling
                    .equipment()
                    .iter()
                    .map(|e| format!(
                        "{} ({})",
                        e.descriptor().name,
                        e.descriptor().end_use.as_str()
                    ))
                    .collect::<Vec<_>>()
            );
        } else {
            // Dynamic mode: keep ASHP Heater/Cooler, strip non-HVAC equipment
            // to match the OCHRE fixture (which stripped appliances, lighting, etc.)
            // We cannot selectively remove equipment from dwelling, so we log what's present.
            let hvac_info: Vec<String> = dwelling
                .equipment()
                .iter()
                .filter(|e| {
                    let eu = &e.descriptor().end_use;
                    *eu == EndUse::HVAC_HEATING || *eu == EndUse::HVAC_COOLING
                })
                .map(|e| {
                    format!(
                        "{} ({})",
                        e.descriptor().name,
                        e.descriptor().end_use.as_str()
                    )
                })
                .collect();
            let non_hvac: Vec<String> = dwelling
                .equipment()
                .iter()
                .filter(|e| {
                    let eu = &e.descriptor().end_use;
                    *eu != EndUse::HVAC_HEATING && *eu != EndUse::HVAC_COOLING
                })
                .map(|e| e.descriptor().name.clone())
                .collect();
            eprintln!("[{mode_name}] HVAC equipment: {hvac_info:?}");
            if !non_hvac.is_empty() {
                eprintln!(
                    "[{mode_name}] WARNING: non-HVAC equipment present (not stripped): {non_hvac:?}"
                );
            }
        }

        // Collect per-step telemetry from IdealHvac for debugging
        struct StepTelemetry {
            mode: f64,
            target_c: f64,
            ideal_cap_w: f64,
            output_w: f64,
        }
        let mut step_telemetry: Vec<StepTelemetry> = Vec::with_capacity(n_steps);

        eprintln!(
            "[{mode_name}] Boundary diagnostics configured: {}",
            dwelling.thermal_solver.boundary_diagnostics_count()
        );

        dwelling.enable_observer(n_steps);

        // Window parameter dump for solar investigation.
        {
            let cfg = dwelling.thermal_solver.config();
            if !cfg.window_properties.is_empty() {
                eprintln!(
                    "\n  [{mode_name}] Window properties ({} windows):",
                    cfg.window_properties.len()
                );
                eprintln!(
                    "    {:>6} {:>7} {:>7} {:>7} {:>7} {:>7} {:>8}",
                    "SurfID", "SHGC", "W_SHGC", "U", "Area", "Trans", "Curve"
                );
                for (&sid, wp) in &cfg.window_properties {
                    let curve = GlazingCurve::from_u_shgc(wp.u_factor_w_m2_k, wp.shgc);
                    eprintln!(
                        "    {:>6} {:>7.4} {:>7.4} {:>7.3} {:>7.2} {:>7.4} {:>8?}",
                        sid,
                        wp.shgc,
                        wp.winter_shgc,
                        wp.u_factor_w_m2_k,
                        wp.area_m2,
                        wp.transmittance,
                        curve,
                    );
                }
            }
        }

        for _ in 0..n_steps {
            dwelling.step().expect("dwelling.step");
            // Read IdealHvac telemetry after each step
            if use_ideal {
                if let Some(eq) = dwelling.equipment().first() {
                    let t = eq.telemetry();
                    step_telemetry.push(StepTelemetry {
                        mode: t.get("operating_mode").unwrap_or(f64::NAN),
                        target_c: t.get("current_target_c").unwrap_or(f64::NAN),
                        ideal_cap_w: t.get("ideal_capacity_w").unwrap_or(f64::NAN),
                        output_w: t.get("thermal_output_w").unwrap_or(f64::NAN),
                    });
                }
            }
        }
        let _ = fs::remove_file(&output_path);

        let snapshots = dwelling.drain_observations();
        assert_eq!(
            snapshots.len(),
            n_steps,
            "expected {n_steps} observer snapshots, got {}",
            snapshots.len()
        );

        // One-shot interior LWR surface diagnostic from last timestep.
        if let Some(last) = snapshots.last() {
            if let Some(solver) = last.phases.post_solvers.as_ref() {
                let diags = &solver.envelope_gains.int_surface_diag;
                if !diags.is_empty() {
                    eprintln!(
                        "\n  [{mode_name}] Interior LWR surface diagnostics (last step, {} surfaces):",
                        diags.len()
                    );
                    eprintln!("    {:>4} {:>10} {:>10}", "Idx", "T_surf(°C)", "LWR(W)");
                    let mut total_lwr = 0.0_f64;
                    for (i, d) in diags.iter().enumerate() {
                        eprintln!(
                            "    {:>4} {:>10.2} {:>10.1}",
                            i, d.surface_temp_c, d.lwr_flux_w
                        );
                        total_lwr += d.lwr_flux_w;
                    }
                    eprintln!("    Total LWR to zone air: {total_lwr:.1} W");
                }

                // Also dump interior LWR by zone.
                for (zid, lwr) in &solver.envelope_gains.interior_lwr_by_zone {
                    eprintln!("    Zone {:?} interior LWR total: {:.1} W", zid, lwr);
                }
            }
        }

        // Dump LWR zone config: how many surfaces per zone, which have driving_temp.
        {
            let cfg = dwelling.thermal_solver.config();
            for zone_cfg in &cfg.interior_lwr_zones {
                let n_driven = zone_cfg
                    .surfaces
                    .iter()
                    .filter(|s| s.driving_temp.is_some())
                    .count();
                let n_total = zone_cfg.surfaces.len();
                eprintln!(
                    "  [{mode_name}] LWR zone {:?}: {} surfaces ({} driven/window, {} RC-noded)",
                    zone_cfg.zone_id,
                    n_total,
                    n_driven,
                    n_total - n_driven
                );
                for (i, s) in zone_cfg.surfaces.iter().enumerate() {
                    eprintln!(
                        "    surf[{i}]: area={:.2} ε={:.2} rad_frac={:.4} solar_abs={:.2} floor={} driving={:?} state={} input={}",
                        s.area_m2,
                        s.emissivity,
                        s.radiation_frac,
                        s.solar_absorptance,
                        s.is_floor,
                        s.driving_temp,
                        s.state_index,
                        s.input_index,
                    );
                }
            }
        }

        let zone_indoor = ZoneId(1);
        let zone_attic = ZoneId(2);

        let mut hares_indoor_temp: Vec<f64> = Vec::with_capacity(n_steps);
        let mut hares_attic_temp: Vec<f64> = Vec::with_capacity(n_steps);
        let mut hares_hvac_heating_w: Vec<f64> = Vec::with_capacity(n_steps);
        let mut hares_hvac_cooling_w: Vec<f64> = Vec::with_capacity(n_steps);
        let mut hares_outdoor_temp: Vec<f64> = Vec::with_capacity(n_steps);

        for snap in &snapshots {
            let (indoor_t, attic_t) = snap
                .phases
                .post_zone_update
                .as_ref()
                .map(|zu| {
                    let ind = zu
                        .zone_temps_c
                        .iter()
                        .find(|(z, _)| *z == zone_indoor)
                        .map(|(_, t)| *t)
                        .unwrap_or(f64::NAN);
                    let att = zu
                        .zone_temps_c
                        .iter()
                        .find(|(z, _)| *z == zone_attic)
                        .map(|(_, t)| *t)
                        .unwrap_or(f64::NAN);
                    (ind, att)
                })
                .unwrap_or((f64::NAN, f64::NAN));

            let outdoor_t = snap
                .phases
                .post_environment
                .as_ref()
                .map(|e| e.outdoor_temp_c)
                .unwrap_or(f64::NAN);

            hares_indoor_temp.push(indoor_t);
            hares_attic_temp.push(attic_t);
            hares_outdoor_temp.push(outdoor_t);

            if let Some(solver) = snap.phases.post_solvers.as_ref() {
                let g = &solver.envelope_gains;
                hares_hvac_heating_w.push(g.hvac_heating_w.max(0.0));
                hares_hvac_cooling_w.push(g.hvac_cooling_w.abs());
            } else {
                hares_hvac_heating_w.push(f64::NAN);
                hares_hvac_cooling_w.push(f64::NAN);
            }
        }

        let ochre_csv = fixture_dir(mode_name, scenario).join("ochre_reference.csv");
        if !ochre_csv.exists() {
            panic!(
                "OCHRE reference fixture not found: {}\nRun: uv run tests/python/generate_conditioned_oracle.py",
                ochre_csv.display()
            );
        }
        let ochre = parse_csv_columns(&ochre_csv);

        let ochre_indoor = ochre
            .get("Temperature - Indoor (C)")
            .cloned()
            .unwrap_or_default();
        let ochre_attic = ochre
            .get("Temperature - Attic (C)")
            .cloned()
            .unwrap_or_default();
        let ochre_outdoor = ochre
            .get("Temperature - Outdoor (C)")
            .cloned()
            .unwrap_or_default();
        let ochre_heating_delivered = ochre
            .get("HVAC Heating Delivered (W)")
            .cloned()
            .unwrap_or_default();
        let ochre_cooling_delivered = ochre
            .get("HVAC Cooling Delivered (W)")
            .cloned()
            .unwrap_or_default();

        assert_eq!(
            hares_indoor_temp.len(),
            ochre_indoor.len(),
            "step count mismatch: HARES={} vs OCHRE={}",
            hares_indoor_temp.len(),
            ochre_indoor.len()
        );

        let mae = |a: &[f64], b: &[f64]| -> f64 {
            let finite_diffs: Vec<f64> = a
                .iter()
                .zip(b.iter())
                .filter(|(x, y)| x.is_finite() && y.is_finite())
                .map(|(x, y)| (x - y).abs())
                .collect();
            if finite_diffs.is_empty() {
                f64::INFINITY
            } else {
                finite_diffs.iter().sum::<f64>() / finite_diffs.len() as f64
            }
        };

        let finite_mean = |v: &[f64]| -> Option<f64> {
            let vals: Vec<f64> = v.iter().copied().filter(|x| x.is_finite()).collect();
            if vals.is_empty() {
                None
            } else {
                Some(vals.iter().sum::<f64>() / vals.len() as f64)
            }
        };

        let indoor_mae = mae(&hares_indoor_temp, &ochre_indoor);
        let attic_mae = mae(&hares_attic_temp, &ochre_attic);

        let ochre_indoor_mean = finite_mean(&ochre_indoor).unwrap_or(f64::NAN);
        let ochre_attic_mean = finite_mean(&ochre_attic).unwrap_or(f64::NAN);
        let ochre_heating_mean = finite_mean(&ochre_heating_delivered).unwrap_or(f64::NAN);
        let ochre_cooling_mean = finite_mean(&ochre_cooling_delivered).unwrap_or(f64::NAN);

        let hares_indoor_mean = finite_mean(&hares_indoor_temp);
        let hares_attic_mean = finite_mean(&hares_attic_temp);
        let hares_heating_mean = finite_mean(&hares_hvac_heating_w);
        let hares_cooling_mean = finite_mean(&hares_hvac_cooling_w);

        let mode_upper = mode_name.to_uppercase();
        eprintln!(
            "\n{:=^70}",
            format!(" CONDITIONED {mode_upper}: {scenario} ")
        );
        eprintln!(
            "  Steps: HARES={} OCHRE={}",
            hares_indoor_temp.len(),
            ochre_indoor.len()
        );
        eprintln!(
            "  Indoor temp  — HARES mean: {:.2} C  OCHRE mean: {:.2} C  MAE: {:.3} C",
            hares_indoor_mean.unwrap_or(f64::NAN),
            ochre_indoor_mean,
            indoor_mae
        );
        eprintln!(
            "  Attic temp   — HARES mean: {:.2} C  OCHRE mean: {:.2} C  MAE: {:.3} C",
            hares_attic_mean.unwrap_or(f64::NAN),
            ochre_attic_mean,
            attic_mae
        );
        eprintln!(
            "  HVAC heating — HARES mean: {:.1} W   OCHRE mean: {:.1} W",
            hares_heating_mean.unwrap_or(f64::NAN),
            ochre_heating_mean
        );
        eprintln!(
            "  HVAC cooling — HARES mean: {:.1} W   OCHRE mean: {:.1} W",
            hares_cooling_mean.unwrap_or(f64::NAN),
            ochre_cooling_mean
        );

        // Hourly comparison table
        if use_ideal && !step_telemetry.is_empty() {
            eprintln!("\n  Hourly comparison (first 48h) — with IdealHvac internals:");
            eprintln!(
                "  {:>4} {:>8} {:>8} {:>8} {:>8} {:>10} {:>10} {:>8}  {:>4} {:>8} {:>10} {:>10}",
                "Hour",
                "H_ind",
                "O_ind",
                "Δ_ind",
                "O_out",
                "H_heat",
                "O_heat",
                "O_cool",
                "Mode",
                "Target",
                "IdealCap",
                "Output"
            );
            for hour in 0..48 {
                let step = hour * 60;
                if step >= hares_indoor_temp.len() {
                    break;
                }
                let hi = hares_indoor_temp[step];
                let oi = ochre_indoor.get(step).copied().unwrap_or(f64::NAN);
                let oo = ochre_outdoor.get(step).copied().unwrap_or(f64::NAN);
                let oh = ochre_heating_delivered
                    .get(step)
                    .copied()
                    .unwrap_or(f64::NAN);
                let oc = ochre_cooling_delivered
                    .get(step)
                    .copied()
                    .unwrap_or(f64::NAN);
                let hh = hares_hvac_heating_w.get(step).copied().unwrap_or(0.0);
                let telem = step_telemetry.get(step);
                let mode_str = match telem.map(|t| t.mode as i32) {
                    Some(1) => "HEAT",
                    Some(2) => "COOL",
                    Some(0) => "OFF",
                    _ => "?",
                };
                let target = telem.map(|t| t.target_c).unwrap_or(f64::NAN);
                let icap = telem.map(|t| t.ideal_cap_w).unwrap_or(f64::NAN);
                let out = telem.map(|t| t.output_w).unwrap_or(f64::NAN);
                eprintln!(
                    "  {:>4} {:>8.2} {:>8.2} {:>+8.2} {:>8.1} {:>10.0} {:>10.0} {:>8.0}  {:>4} {:>8.2} {:>10.0} {:>10.0}",
                    hour,
                    hi,
                    oi,
                    hi - oi,
                    oo,
                    hh,
                    oh,
                    oc,
                    mode_str,
                    target,
                    icap,
                    out
                );
            }
        } else {
            eprintln!("\n  Hourly comparison (first 24h):");
            eprintln!(
                "  {:>4} {:>8} {:>8} {:>8} {:>8} {:>10} {:>10} {:>8}",
                "Hour", "H_ind", "O_ind", "Δ_ind", "O_out", "H_heat", "O_heat", "O_cool"
            );
            for hour in 0..24 {
                let step = hour * 60;
                if step >= hares_indoor_temp.len() {
                    break;
                }
                let hi = hares_indoor_temp[step];
                let oi = ochre_indoor.get(step).copied().unwrap_or(f64::NAN);
                let oo = ochre_outdoor.get(step).copied().unwrap_or(f64::NAN);
                let oh = ochre_heating_delivered
                    .get(step)
                    .copied()
                    .unwrap_or(f64::NAN);
                let oc = ochre_cooling_delivered
                    .get(step)
                    .copied()
                    .unwrap_or(f64::NAN);
                let hh = hares_hvac_heating_w.get(step).copied().unwrap_or(0.0);
                eprintln!(
                    "  {:>4} {:>8.2} {:>8.2} {:>+8.2} {:>8.1} {:>10.0} {:>10.0} {:>8.0}",
                    hour,
                    hi,
                    oi,
                    hi - oi,
                    oo,
                    hh,
                    oh,
                    oc
                );
            }
        }

        // Mean envelope component comparison (HARES vs OCHRE)
        {
            let mut h_infiltration = 0.0_f64;
            let mut h_ventilation = 0.0_f64;
            let mut h_nat_vent = 0.0_f64;
            let mut h_window_solar = 0.0_f64;
            let mut h_window_heat = 0.0_f64;
            let mut h_wall_heat = 0.0_f64;
            let mut h_roof_heat = 0.0_f64;
            let mut h_floor_heat = 0.0_f64;
            let mut h_internal_mass = 0.0_f64;
            let mut h_internal_gain = 0.0_f64;
            let mut h_combined_airflow = 0.0_f64;
            let mut h_total_airflow_m3s = 0.0_f64;
            let mut h_raw_inf_m3s = 0.0_f64;
            let mut h_driving_outdoor_c = 0.0_f64;
            let mut h_driving_ground_c = 0.0_f64;
            let mut h_solar_beam_w = 0.0_f64;
            let mut h_solar_diffuse_w = 0.0_f64;
            let mut h_solar_absorbed_w = 0.0_f64;
            let mut n = 0usize;

            for snap in &snapshots {
                if let Some(solver) = snap.phases.post_solvers.as_ref() {
                    let g = &solver.envelope_gains;
                    h_infiltration += g.infiltration_w;
                    h_ventilation += g.ventilation_w;
                    h_nat_vent += g.natural_ventilation_w;
                    h_window_solar += g.window_solar_w;
                    h_window_heat += g.window_heat_gain_w;
                    h_wall_heat += g.wall_heat_gain_w;
                    h_roof_heat += g.roof_heat_gain_w;
                    h_floor_heat += g.floor_heat_gain_w;
                    h_internal_mass += g.internal_mass_heat_gain_w;
                    h_internal_gain += g.internal_gain_w;
                    h_combined_airflow += g.combined_airflow_sensible_w;
                    h_total_airflow_m3s += g.total_airflow_m3_s;
                    h_raw_inf_m3s += g.raw_infiltration_m3_s;
                    h_driving_outdoor_c += g.driving_outdoor_temp_c;
                    h_driving_ground_c += g.driving_ground_temp_c;
                    for wd in &g.window_solar_diag {
                        h_solar_beam_w += wd.transmitted_beam_w;
                        h_solar_diffuse_w += wd.transmitted_diffuse_w;
                        h_solar_absorbed_w += wd.absorbed_zone_w;
                    }
                    n += 1;
                }
            }
            if n > 0 {
                let d = n as f64;
                let o_inf = ochre
                    .get("Infiltration Heat Gain - Indoor (W)")
                    .map(|v| v.iter().sum::<f64>() / v.len() as f64);
                let o_forced = ochre
                    .get("Forced Ventilation Heat Gain - Indoor (W)")
                    .map(|v| v.iter().sum::<f64>() / v.len() as f64);
                let o_nat = ochre
                    .get("Natural Ventilation Heat Gain - Indoor (W)")
                    .map(|v| v.iter().sum::<f64>() / v.len() as f64);
                let o_wsolar = ochre
                    .get("Window Transmitted Solar Gain (W)")
                    .map(|v| v.iter().sum::<f64>() / v.len() as f64);
                let o_wheat = ochre
                    .get("Window Heat Gain - Indoor (W)")
                    .map(|v| v.iter().sum::<f64>() / v.len() as f64);
                let o_wall = ochre
                    .get("Wall Heat Gain - Indoor (W)")
                    .map(|v| v.iter().sum::<f64>() / v.len() as f64);
                let o_roof = ochre
                    .get("Roof Heat Gain - Indoor (W)")
                    .map(|v| v.iter().sum::<f64>() / v.len() as f64);
                let o_floor = ochre
                    .get("Floor Heat Gain - Indoor (W)")
                    .map(|v| v.iter().sum::<f64>() / v.len() as f64);
                let o_imass = ochre
                    .get("Internal Mass Heat Gain - Indoor (W)")
                    .map(|v| v.iter().sum::<f64>() / v.len() as f64);
                let o_igain = ochre
                    .get("Internal Heat Gain - Indoor (W)")
                    .map(|v| v.iter().sum::<f64>() / v.len() as f64);
                let o_inf_flow = ochre
                    .get("Infiltration Flow Rate - Indoor (m^3/s)")
                    .map(|v| v.iter().sum::<f64>() / v.len() as f64);

                let fmt = |label: &str, hares: f64, ochre: Option<f64>| {
                    if let Some(o) = ochre {
                        let delta = hares - o;
                        eprintln!(
                            "    {label:<40} HARES={hares:>10.1}  OCHRE={o:>10.1}  Δ={delta:>+10.1}"
                        );
                    } else {
                        eprintln!("    {label:<40} HARES={hares:>10.1}  OCHRE=       n/a");
                    }
                };

                eprintln!("\n  Envelope component comparison (mean W):");
                fmt("Infiltration (W)", h_infiltration / d, o_inf);
                fmt("Forced ventilation (W)", h_ventilation / d, o_forced);
                fmt("Natural ventilation (W)", h_nat_vent / d, o_nat);
                fmt(
                    "Combined airflow sensible (W)",
                    h_combined_airflow / d,
                    o_inf.and_then(|i| o_forced.map(|f| o_nat.map(|n| i + f + n).unwrap_or(i + f))),
                );
                fmt("Window solar transmitted (W)", h_window_solar / d, o_wsolar);
                fmt("Window heat gain (W)", h_window_heat / d, o_wheat);
                fmt("Wall heat gain (W)", h_wall_heat / d, o_wall);
                fmt("Roof heat gain (W)", h_roof_heat / d, o_roof);
                fmt("Floor heat gain (W)", h_floor_heat / d, o_floor);
                fmt("Internal mass heat gain (W)", h_internal_mass / d, o_imass);
                fmt("Internal/occupancy gain (W)", h_internal_gain / d, o_igain);
                eprintln!(
                    "    {:<40} HARES={:>10.5}  OCHRE={:>10.5}",
                    "Infiltration flow (m³/s)",
                    h_raw_inf_m3s / d,
                    o_inf_flow.unwrap_or(f64::NAN)
                );
                eprintln!(
                    "    {:<40} HARES={:>10.5}",
                    "Total airflow (m³/s)",
                    h_total_airflow_m3s / d
                );

                let o_outdoor = ochre
                    .get("Temperature - Outdoor (C)")
                    .map(|v| v.iter().sum::<f64>() / v.len() as f64);
                let o_ground = ochre
                    .get("Temperature - Ground (C)")
                    .map(|v| v.iter().sum::<f64>() / v.len() as f64);
                eprintln!("\n  Driving temperatures (mean °C):");
                eprintln!(
                    "    {:<40} HARES={:>10.2}  OCHRE={:>10.2}",
                    "Outdoor driving temp (°C)",
                    h_driving_outdoor_c / d,
                    o_outdoor.unwrap_or(f64::NAN)
                );
                eprintln!(
                    "    {:<40} HARES={:>10.2}  OCHRE={:>10.2}",
                    "Ground driving temp (°C)",
                    h_driving_ground_c / d,
                    o_ground.unwrap_or(f64::NAN)
                );

                // Beam vs diffuse solar breakdown.
                let beam_mean = h_solar_beam_w / d;
                let diffuse_mean = h_solar_diffuse_w / d;
                let absorbed_mean = h_solar_absorbed_w / d;
                let total_solar = beam_mean + diffuse_mean + absorbed_mean;
                let o_total_solar = o_wsolar.unwrap_or(0.0);
                eprintln!("\n  Window solar breakdown (mean W):");
                eprintln!("    Transmitted beam:      {:>8.1}", beam_mean);
                eprintln!("    Transmitted diffuse:   {:>8.1}", diffuse_mean);
                eprintln!("    Absorbed inward:       {:>8.1}", absorbed_mean);
                eprintln!(
                    "    Total window solar:    {:>8.1}  (OCHRE={:.1}  Δ={:+.1})",
                    total_solar,
                    o_total_solar,
                    total_solar - o_total_solar
                );
                if total_solar > 1.0 {
                    eprintln!(
                        "    Beam fraction:         {:>7.1}%",
                        beam_mean / total_solar * 100.0
                    );
                    eprintln!(
                        "    Diffuse fraction:      {:>7.1}%",
                        diffuse_mean / total_solar * 100.0
                    );
                    eprintln!(
                        "    Absorbed fraction:     {:>7.1}%",
                        absorbed_mean / total_solar * 100.0
                    );
                }
            }
        }

        let mut checks: Vec<Check> = Vec::new();

        // Ideal mode: tight tolerance (solver back-calculates exact capacity)
        // Dynamic mode: wider tolerance (thermostat cycling oscillation)
        let max_temp_mae = if use_ideal { 0.5 } else { 2.0 };
        checks.push(Check::compare_mae(
            "indoor_temp_mae_c",
            indoor_mae,
            max_temp_mae,
            if use_ideal {
                "ideal capacity tracks setpoint exactly"
            } else {
                "thermostat cycling oscillates within deadband"
            },
        ));

        checks.push(Check::compare_mae(
            "attic_temp_mae_c",
            attic_mae,
            3.0,
            "attic temp driven by roof solar, infiltration",
        ));

        if ochre_heating_mean > 100.0 {
            checks.push(Check::compare_mean(
                "hvac_heating_mean_w",
                ochre_heating_mean,
                hares_heating_mean,
                100.0,
                50.0,
                "heating load magnitude",
            ));
        }

        if ochre_cooling_mean > 100.0 {
            checks.push(Check::compare_mean(
                "hvac_cooling_mean_w",
                ochre_cooling_mean,
                hares_cooling_mean,
                100.0,
                50.0,
                "cooling load magnitude",
            ));
        }

        // Physical bounds sanity checks
        let (ind_mn, ind_mx) = hares_indoor_temp
            .iter()
            .copied()
            .filter(|t| t.is_finite())
            .fold((f64::INFINITY, f64::NEG_INFINITY), |(mn, mx), t| {
                (mn.min(t), mx.max(t))
            });
        assert!(
            ind_mn > -10.0 && ind_mx < 50.0,
            "Indoor temperature out of physical bounds: [{ind_mn:.1}, {ind_mx:.1}] C"
        );

        let (att_mn, att_mx) = hares_attic_temp
            .iter()
            .copied()
            .filter(|t| t.is_finite())
            .fold((f64::INFINITY, f64::NEG_INFINITY), |(mn, mx), t| {
                (mn.min(t), mx.max(t))
            });
        assert!(
            att_mn > -40.0 && att_mx < 90.0,
            "Attic temperature out of physical bounds: [{att_mn:.1}, {att_mx:.1}] C"
        );

        eprintln!("\n{:-^70}", " checks ");
        let mut n_pass = 0usize;
        let mut n_fail = 0usize;
        let mut n_missing = 0usize;
        for c in &checks {
            let status = if c.hares.is_nan() {
                n_missing += 1;
                "MISS"
            } else if c.passed {
                n_pass += 1;
                "PASS"
            } else {
                n_fail += 1;
                "FAIL"
            };
            eprintln!(
                "  {status} {:<34} OCHRE={:>10.2}  HARES={:>10.2}  {}",
                c.name, c.ochre, c.hares, c.note
            );
        }
        eprintln!("\n  Total: {n_pass} pass, {n_fail} fail, {n_missing} missing");

        let failed: Vec<&Check> = checks.iter().filter(|c| !c.passed).collect();
        if !failed.is_empty() {
            let msg: Vec<String> = failed.iter().map(|c| c.note.clone()).collect();
            panic!(
                "{} conditioned oracle check(s) exceeded tolerance for scenario '{scenario}' ({mode_name}):\n  {}",
                failed.len(),
                msg.join("\n  ")
            );
        }
    }

    #[test]
    fn conditioned_ideal_spring_72h() {
        run_conditioned_scenario("beopt_spring_72h", true);
    }

    #[test]
    fn conditioned_ideal_summer_48h() {
        run_conditioned_scenario("beopt_summer_48h", true);
    }

    #[test]
    fn conditioned_ideal_winter_48h() {
        run_conditioned_scenario("beopt_winter_48h", true);
    }

    #[test]
    fn conditioned_dynamic_spring_72h() {
        run_conditioned_scenario("beopt_spring_72h", false);
    }

    #[test]
    fn conditioned_dynamic_summer_48h() {
        run_conditioned_scenario("beopt_summer_48h", false);
    }

    #[test]
    fn conditioned_dynamic_winter_48h() {
        run_conditioned_scenario("beopt_winter_48h", false);
    }
}
