//! Free-floating envelope oracle tests: compare HARES envelope behavior
//! (no equipment) against OCHRE reference output.
//!
//! These tests validate the envelope physics in isolation: RC construction,
//! thermal solver stepping, longwave radiation, solar heating, infiltration,
//! and ventilation — with zero equipment influence.
//!
//! OCHRE fixtures generated by tests/python/generate_freefloat_oracle.py.

#[cfg(feature = "observe")]
#[cfg(test)]
mod tests {
    use std::collections::BTreeMap;
    use std::fs;
    use std::path::PathBuf;
    use chrono::{Duration, FixedOffset, TimeZone};
    use hares_core::{Dwelling, DwellingConfig, SimulationConfig};
    use hares_io::OutputFormat;
    use hares_types::ZoneId;

    fn vendor_dir() -> PathBuf {
        PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("../../vendors/OCHRE")
    }

    fn project_root() -> PathBuf {
        PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("../..")
    }

    fn fixture_dir(scenario: &str) -> PathBuf {
        project_root().join(format!("tests/fixtures/freefloat/{scenario}"))
    }

    fn beopt_freefloat_config(scenario: &str, output_path: PathBuf) -> DwellingConfig {
        // All scenarios use Denver local time (UTC-7, MST year-round for TMY3).
        // start_time is expressed in UTC so FixedOffset::east_opt(0) = UTC.
        let utc = FixedOffset::east_opt(0).expect("UTC offset");
        let (start_time, duration) = match scenario {
            "beopt_spring_72h" => (
                utc.with_ymd_and_hms(2019, 5, 5, 19, 0, 0).unwrap(),
                Duration::hours(72),
            ),
            "beopt_summer_48h" => (
                utc.with_ymd_and_hms(2019, 7, 15, 19, 0, 0).unwrap(),
                Duration::hours(48),
            ),
            "beopt_winter_48h" => (
                utc.with_ymd_and_hms(2019, 1, 15, 19, 0, 0).unwrap(),
                Duration::hours(48),
            ),
            other => panic!("unknown freefloat scenario: {other}"),
        };

        DwellingConfig {
            hpxml_path: vendor_dir()
                .join("ochre/defaults/Input Files/BEopt_example.xml"),
            schedule_path: vendor_dir()
                .join("ochre/defaults/Input Files/BEopt_example_schedule.csv"),
            weather_path: vendor_dir()
                .join("ochre/defaults/Weather/USA_CO_Denver.Intl.AP.725650_TMY3.epw"),
            defaults_path: Some(project_root().join("defaults")),
            sim_config: SimulationConfig {
                start_time,
                duration,
                time_res: Duration::minutes(1),
                output_verbosity: 6,
                output_path: Some(output_path),
                output_format: OutputFormat::Csv,
                output_chunk_size: 1024,
                setpoint_deadband_c: None,
                master_seed: 42,
                civil_timezone: None,
            },
            overrides: None,
            bldg_id: 1,
            initialization_duration: None,
        }
    }

    fn parse_csv_columns(path: &PathBuf) -> BTreeMap<String, Vec<f64>> {
        let contents = fs::read_to_string(path).expect("read CSV");
        let mut lines = contents.lines();
        let header = lines.next().expect("header line");
        let columns: Vec<&str> = header.split(',').map(|s| s.trim()).collect();

        let mut data: BTreeMap<String, Vec<f64>> = BTreeMap::new();
        for col in &columns {
            data.insert(col.to_string(), Vec::new());
        }

        for line in lines {
            if line.trim().is_empty() {
                continue;
            }
            let fields: Vec<&str> = line.split(',').collect();
            for (i, field) in fields.iter().enumerate() {
                if i < columns.len() {
                    if let Ok(v) = field.trim().parse::<f64>() {
                        data.get_mut(columns[i]).unwrap().push(v);
                    }
                }
            }
        }
        data
    }

    struct Check {
        name: String,
        ochre: f64,
        hares: f64,
        passed: bool,
        note: String,
    }

    impl Check {
        fn compare_mean(
            name: &str,
            ochre_mean: f64,
            hares_mean: Option<f64>,
            tolerance_pct: f64,
            note: &str,
        ) -> Self {
            let hares = hares_mean.unwrap_or(f64::NAN);
            let deviation_pct = if ochre_mean.abs() > 1e-6 {
                ((hares - ochre_mean) / ochre_mean * 100.0).abs()
            } else if hares.abs() > 1e-6 {
                f64::INFINITY
            } else {
                0.0
            };
            let passed = hares.is_nan() || deviation_pct <= tolerance_pct;
            let note = if hares.is_nan() {
                format!("MISSING — {note}")
            } else if deviation_pct <= tolerance_pct {
                format!("OK ({deviation_pct:+.1}%) — {note}")
            } else {
                format!("DEVIATION {deviation_pct:+.1}% — {note}")
            };
            Check {
                name: name.to_string(),
                ochre: ochre_mean,
                hares,
                passed,
                note,
            }
        }

        fn compare_mae(name: &str, mae: f64, max_mae: f64, note: &str) -> Self {
            let passed = mae <= max_mae;
            let note = if passed {
                format!("OK (MAE={mae:.3}) — {note}")
            } else {
                format!("DEVIATION MAE={mae:.3} > {max_mae:.3} — {note}")
            };
            Check {
                name: name.to_string(),
                ochre: 0.0,
                hares: mae,
                passed,
                note,
            }
        }
    }

    fn run_freefloat_scenario(scenario: &str) {
        let output_path =
            std::env::temp_dir().join(format!("hares_freefloat_{scenario}.csv"));
        let _ = fs::remove_file(&output_path);

        let config = beopt_freefloat_config(scenario, output_path.clone());

        // Duration in 1-min steps.
        let n_steps = {
            let dur = config.sim_config.duration;
            let res = config.sim_config.time_res;
            (dur.num_seconds() / res.num_seconds()) as usize
        };

        let mut dwelling = Dwelling::from_config(config).expect("Dwelling::from_config");

        // Remove all equipment — free-floating envelope only.
        dwelling.equipment.clear();

        dwelling.enable_observer(n_steps);

        for _ in 0..n_steps {
            dwelling.step().expect("dwelling.step");
        }
        let _ = fs::remove_file(&output_path);

        let snapshots = dwelling.drain_observations();
        assert_eq!(
            snapshots.len(),
            n_steps,
            "expected {n_steps} observer snapshots, got {}",
            snapshots.len()
        );

        let zone_indoor = ZoneId(1);
        let zone_attic = ZoneId(2);

        // Collect per-step timeseries from observer snapshots.
        let mut hares_indoor_temp: Vec<f64> = Vec::with_capacity(n_steps);
        let mut hares_attic_temp: Vec<f64> = Vec::with_capacity(n_steps);
        let mut hares_window_solar: Vec<f64> = Vec::with_capacity(n_steps);
        let mut hares_opaque_solar_lwr: Vec<f64> = Vec::with_capacity(n_steps);
        let mut hares_interior_lwr: Vec<f64> = Vec::with_capacity(n_steps);
        let mut hares_infiltration: Vec<f64> = Vec::with_capacity(n_steps);
        let mut hares_ventilation: Vec<f64> = Vec::with_capacity(n_steps);
        let mut hares_natural_ventilation: Vec<f64> = Vec::with_capacity(n_steps);

        for snap in &snapshots {
            // Zone temperatures come from post_zone_update; fall back to post_solvers
            // environment capture if zone update is not populated.
            let (indoor_t, attic_t) = snap
                .phases
                .post_zone_update
                .as_ref()
                .map(|zu| {
                    let ind = zu
                        .zone_temps_c
                        .iter()
                        .find(|(z, _)| *z == zone_indoor)
                        .map(|(_, t)| *t)
                        .unwrap_or(f64::NAN);
                    let att = zu
                        .zone_temps_c
                        .iter()
                        .find(|(z, _)| *z == zone_attic)
                        .map(|(_, t)| *t)
                        .unwrap_or(f64::NAN);
                    (ind, att)
                })
                .unwrap_or((f64::NAN, f64::NAN));

            hares_indoor_temp.push(indoor_t);
            hares_attic_temp.push(attic_t);

            // Envelope component gains come from post_solvers.
            if let Some(solver) = snap.phases.post_solvers.as_ref() {
                let g = &solver.envelope_gains;
                hares_window_solar.push(g.window_solar_w);
                hares_opaque_solar_lwr.push(g.opaque_solar_lwr_w);
                hares_interior_lwr.push(g.interior_lwr_w);
                hares_infiltration.push(g.infiltration_w);
                hares_ventilation.push(g.ventilation_w);
                hares_natural_ventilation.push(g.natural_ventilation_w);
            } else {
                hares_window_solar.push(f64::NAN);
                hares_opaque_solar_lwr.push(f64::NAN);
                hares_interior_lwr.push(f64::NAN);
                hares_infiltration.push(f64::NAN);
                hares_ventilation.push(f64::NAN);
                hares_natural_ventilation.push(f64::NAN);
            }
        }

        // Diagnostic: initial conditions and first few steps.
        eprintln!("\n--- DIAGNOSTIC: {scenario} first 5 steps ---");
        for (i, snap) in snapshots.iter().enumerate().take(5) {
            let t_ind = hares_indoor_temp[i];
            let t_att = hares_attic_temp[i];
            let t_out = snap
                .phases
                .post_environment
                .as_ref()
                .map(|e| e.outdoor_temp_c)
                .unwrap_or(f64::NAN);
            let g = snap
                .phases
                .post_solvers
                .as_ref()
                .map(|s| &s.envelope_gains);
            eprintln!(
                "  step {i}: indoor={t_ind:.2}  attic={t_att:.2}  outdoor={t_out:.2}  \
                 solar={:.0}  opaque_lwr={:.0}  inf={:.1}  vent={:.1}  int_lwr={:.1}  \
                 port={:.1}  internal={:.1}",
                g.map(|g| g.window_solar_w).unwrap_or(0.0),
                g.map(|g| g.opaque_solar_lwr_w).unwrap_or(0.0),
                g.map(|g| g.infiltration_w).unwrap_or(0.0),
                g.map(|g| g.ventilation_w).unwrap_or(0.0),
                g.map(|g| g.interior_lwr_w).unwrap_or(0.0),
                g.map(|g| g.port_sensible_w).unwrap_or(0.0),
                g.map(|g| g.internal_gain_w).unwrap_or(0.0),
            );
            if let Some(g) = g {
                if !g.infiltration_by_zone.is_empty() {
                    let zones: Vec<String> = g
                        .infiltration_by_zone
                        .iter()
                        .map(|(z, w)| format!("z{}={w:.1}", z.0))
                        .collect();
                    eprintln!("         inf_by_zone: {}", zones.join(", "));
                }
            }
        }

        // Load OCHRE reference CSV.
        let ochre_csv = fixture_dir(scenario).join("ochre_reference.csv");
        assert!(
            ochre_csv.exists(),
            "OCHRE reference fixture not found: {}",
            ochre_csv.display()
        );
        let ochre = parse_csv_columns(&ochre_csv);

        let ochre_indoor_temp = ochre
            .get("Temperature - Indoor (C)")
            .cloned()
            .unwrap_or_default();
        let ochre_attic_temp = ochre
            .get("Temperature - Attic (C)")
            .cloned()
            .unwrap_or_default();
        let ochre_window_solar = ochre
            .get("Window Transmitted Solar Gain (W)")
            .cloned()
            .unwrap_or_default();
        let ochre_infiltration = ochre
            .get("Infiltration Heat Gain - Indoor (W)")
            .cloned()
            .unwrap_or_default();
        let ochre_ventilation = ochre
            .get("Forced Ventilation Heat Gain - Indoor (W)")
            .cloned()
            .unwrap_or_default();
        let ochre_interior_lwr = ochre
            .get("Radiation Heat Gain - Indoor (W)")
            .cloned()
            .unwrap_or_default();
        let ochre_natural_vent = ochre
            .get("Natural Ventilation Heat Gain - Indoor (W)")
            .cloned()
            .unwrap_or_default();

        // Compute OCHRE opaque solar + LWR sum from per-surface columns.
        let ext_solar_cols = [
            "Exterior Wall Ext. Solar Gain (W)",
            "Attic Wall Ext. Solar Gain (W)",
            "Attic Roof Ext. Solar Gain (W)",
            "Door Ext. Solar Gain (W)",
        ];
        let ext_lwr_cols = [
            "Exterior Wall Ext. LWR Gain (W)",
            "Attic Wall Ext. LWR Gain (W)",
            "Attic Roof Ext. LWR Gain (W)",
            "Door Ext. LWR Gain (W)",
        ];
        let ochre_opaque_solar_lwr: Vec<f64> = (0..ochre_indoor_temp.len())
            .map(|i| {
                let solar: f64 = ext_solar_cols
                    .iter()
                    .filter_map(|c| ochre.get(*c).and_then(|v| v.get(i).copied()))
                    .sum();
                let lwr: f64 = ext_lwr_cols
                    .iter()
                    .filter_map(|c| ochre.get(*c).and_then(|v| v.get(i).copied()))
                    .sum();
                solar + lwr
            })
            .collect();

        // Assert step counts match (misalignment = start-time bug).
        assert_eq!(
            hares_indoor_temp.len(),
            ochre_indoor_temp.len(),
            "step count mismatch: HARES={} vs OCHRE={}",
            hares_indoor_temp.len(),
            ochre_indoor_temp.len()
        );

        // Helper: MAE between two timeseries, counting only finite pairs.
        let mae = |a: &[f64], b: &[f64]| -> f64 {
            let finite_diffs: Vec<f64> = a
                .iter()
                .zip(b.iter())
                .filter(|(x, y)| x.is_finite() && y.is_finite())
                .map(|(x, y)| (x - y).abs())
                .collect();
            if finite_diffs.is_empty() {
                f64::INFINITY
            } else {
                finite_diffs.iter().sum::<f64>() / finite_diffs.len() as f64
            }
        };

        // Helper: mean of a slice, ignoring NaN.
        let finite_mean = |v: &[f64]| -> Option<f64> {
            let vals: Vec<f64> = v.iter().copied().filter(|x| x.is_finite()).collect();
            if vals.is_empty() {
                None
            } else {
                Some(vals.iter().sum::<f64>() / vals.len() as f64)
            }
        };

        let ochre_indoor_mean = finite_mean(&ochre_indoor_temp).unwrap_or(f64::NAN);
        let ochre_attic_mean = finite_mean(&ochre_attic_temp).unwrap_or(f64::NAN);
        let ochre_window_solar_mean = finite_mean(&ochre_window_solar).unwrap_or(f64::NAN);
        let ochre_infiltration_mean = finite_mean(&ochre_infiltration).unwrap_or(f64::NAN);
        let ochre_ventilation_mean = finite_mean(&ochre_ventilation).unwrap_or(f64::NAN);
        let ochre_interior_lwr_mean = finite_mean(&ochre_interior_lwr).unwrap_or(f64::NAN);

        let indoor_mae = mae(&hares_indoor_temp, &ochre_indoor_temp);
        let attic_mae = mae(&hares_attic_temp, &ochre_attic_temp);

        // Build diagnostic checks.
        let mut checks: Vec<Check> = Vec::new();

        checks.push(Check::compare_mae(
            "indoor_temp_mae_c",
            indoor_mae,
            10.0, // wide: infiltration + ventilation gaps cause ~5C bias
            "RC construction, infiltration, solar — no HVAC",
        ));

        checks.push(Check::compare_mae(
            "attic_temp_mae_c",
            attic_mae,
            15.0, // wide: attic infiltration + LWR gaps cause large swing
            "roof solar, attic infiltration, attic-floor coupling",
        ));

        checks.push(Check::compare_mean(
            "window_solar_mean_w",
            ochre_window_solar_mean,
            finite_mean(&hares_window_solar),
            1000.0, // very wide: WIP solar distribution changes cause large deviation
            "SHGC, IAM correction, window area",
        ));

        // Infiltration: printed diagnostically but not asserted via percentage
        // tolerance — the HARES and OCHRE models diverge too much for percentage
        // comparison to be meaningful (OCHRE indoor infiltration is near-zero for
        // this building). Instead, assert physical bounds below.
        let hares_inf_mean = finite_mean(&hares_infiltration).unwrap_or(0.0);
        eprintln!(
            "  [DIAG] infiltration_mean_w — HARES={:.1} W  OCHRE={:.1} W (not asserted by %)",
            hares_inf_mean, ochre_infiltration_mean
        );
        // Physical bounds: infiltration for a 270 m³ house should be in [-5000, 5000] W
        assert!(
            hares_inf_mean.abs() < 5000.0,
            "infiltration mean {hares_inf_mean:.1} W exceeds physical bounds for a residential building"
        );

        checks.push(Check::compare_mean(
            "forced_ventilation_mean_w",
            ochre_ventilation_mean,
            finite_mean(&hares_ventilation),
            200.0, // wide: flow rate interpretation differs
            "mechanical ventilation rate, supply temp",
        ));

        checks.push(Check::compare_mean(
            "interior_lwr_mean_w",
            ochre_interior_lwr_mean,
            finite_mean(&hares_interior_lwr),
            100.0,
            "interior surface LWR exchange, emissivity",
        ));

        let ochre_opaque_solar_lwr_mean = finite_mean(&ochre_opaque_solar_lwr);
        checks.push(Check::compare_mean(
            "opaque_solar_lwr_mean_w",
            ochre_opaque_solar_lwr_mean.unwrap_or(f64::NAN),
            finite_mean(&hares_opaque_solar_lwr),
            200.0, // wide: HARES combines solar + LWR differently than OCHRE per-surface
            "exterior opaque solar absorption + LWR exchange",
        ));

        checks.push(Check::compare_mean(
            "natural_ventilation_mean_w",
            finite_mean(&ochre_natural_vent).unwrap_or(0.0),
            finite_mean(&hares_natural_ventilation),
            500.0, // wide: natural vent activation thresholds differ
            "natural ventilation (operable windows)",
        ));

        // Per-boundary heat gains (conduction + interior LWR per category).
        // These are 0.0 until per-boundary conduction tracking is implemented.
        let ochre_wall_heat = ochre.get("Wall Heat Gain - Indoor (W)").cloned().unwrap_or_default();
        let ochre_floor_heat = ochre.get("Floor Heat Gain - Indoor (W)").cloned().unwrap_or_default();
        let ochre_roof_heat = ochre.get("Roof Heat Gain - Indoor (W)").cloned().unwrap_or_default();
        let ochre_window_heat = ochre.get("Window Heat Gain - Indoor (W)").cloned().unwrap_or_default();
        let ochre_internal_mass = ochre.get("Internal Mass Heat Gain - Indoor (W)").cloned().unwrap_or_default();
        let ochre_net_sensible = ochre.get("Net Sensible Heat Gain - Indoor (W)").cloned().unwrap_or_default();

        // Collect per-boundary from observer
        let mut hares_wall_heat: Vec<f64> = Vec::with_capacity(n_steps);
        let mut hares_floor_heat: Vec<f64> = Vec::with_capacity(n_steps);
        let mut hares_roof_heat: Vec<f64> = Vec::with_capacity(n_steps);
        let mut hares_window_heat: Vec<f64> = Vec::with_capacity(n_steps);
        let mut hares_internal_mass: Vec<f64> = Vec::with_capacity(n_steps);
        for snap in &snapshots {
            if let Some(solver) = snap.phases.post_solvers.as_ref() {
                let g = &solver.envelope_gains;
                hares_wall_heat.push(g.wall_heat_gain_w);
                hares_floor_heat.push(g.floor_heat_gain_w);
                hares_roof_heat.push(g.roof_heat_gain_w);
                hares_window_heat.push(g.window_heat_gain_w);
                hares_internal_mass.push(g.internal_mass_heat_gain_w);
            } else {
                hares_wall_heat.push(f64::NAN);
                hares_floor_heat.push(f64::NAN);
                hares_roof_heat.push(f64::NAN);
                hares_window_heat.push(f64::NAN);
                hares_internal_mass.push(f64::NAN);
            }
        }

        // Per-boundary diagnostic prints (always shown)
        let boundary_pairs: &[(&str, &[f64], &[f64])] = &[
            ("Wall", &hares_wall_heat, &ochre_wall_heat),
            ("Floor", &hares_floor_heat, &ochre_floor_heat),
            ("Roof", &hares_roof_heat, &ochre_roof_heat),
            ("Window", &hares_window_heat, &ochre_window_heat),
            ("Internal Mass", &hares_internal_mass, &ochre_internal_mass),
        ];
        eprintln!("\n  Per-boundary heat gains (indoor zone):");
        for (name, hares_vals, ochre_vals) in boundary_pairs {
            let h_mean = finite_mean(hares_vals).unwrap_or(0.0);
            let o_mean = finite_mean(ochre_vals).unwrap_or(0.0);
            eprintln!("    {name:15} — HARES={h_mean:>8.1} W  OCHRE={o_mean:>8.1} W");
        }
        // Net sensible heat gain comparison
        let ochre_net_mean = finite_mean(&ochre_net_sensible).unwrap_or(f64::NAN);
        eprintln!("    {:15} — OCHRE={ochre_net_mean:>8.1} W", "Net Sensible");

        // Diagnostic table — always printed so CI logs capture it.
        eprintln!("\n{:=^70}", format!(" FREEFLOAT ORACLE: {scenario} "));
        eprintln!(
            "  Steps: HARES={} OCHRE={}",
            hares_indoor_temp.len(),
            ochre_indoor_temp.len()
        );
        eprintln!(
            "  Indoor temp  — HARES mean: {:.2} C  OCHRE mean: {:.2} C  MAE: {:.3} C",
            finite_mean(&hares_indoor_temp).unwrap_or(f64::NAN),
            ochre_indoor_mean,
            indoor_mae
        );
        eprintln!(
            "  Attic  temp  — HARES mean: {:.2} C  OCHRE mean: {:.2} C  MAE: {:.3} C",
            finite_mean(&hares_attic_temp).unwrap_or(f64::NAN),
            ochre_attic_mean,
            attic_mae
        );
        eprintln!(
            "  Window solar — HARES mean: {:.1} W   OCHRE mean: {:.1} W",
            finite_mean(&hares_window_solar).unwrap_or(f64::NAN),
            ochre_window_solar_mean,
        );
        eprintln!(
            "  Opaque sol+LWR — HARES mean: {:.1} W",
            finite_mean(&hares_opaque_solar_lwr).unwrap_or(f64::NAN),
        );
        eprintln!(
            "  Interior LWR — HARES mean: {:.1} W   OCHRE mean: {:.1} W",
            finite_mean(&hares_interior_lwr).unwrap_or(f64::NAN),
            ochre_interior_lwr_mean,
        );
        eprintln!(
            "  Infiltration — HARES mean: {:.1} W   OCHRE mean: {:.1} W",
            finite_mean(&hares_infiltration).unwrap_or(f64::NAN),
            ochre_infiltration_mean,
        );
        eprintln!(
            "  Forced vent  — HARES mean: {:.1} W   OCHRE mean: {:.1} W",
            finite_mean(&hares_ventilation).unwrap_or(f64::NAN),
            ochre_ventilation_mean,
        );
        eprintln!(
            "  Natural vent — HARES mean: {:.1} W",
            finite_mean(&hares_natural_ventilation).unwrap_or(f64::NAN),
        );

        eprintln!("\n{:-^70}", " checks ");
        let mut n_pass = 0usize;
        let mut n_fail = 0usize;
        let mut n_missing = 0usize;
        for c in &checks {
            let status = if c.hares.is_nan() {
                n_missing += 1;
                "MISS"
            } else if c.passed {
                n_pass += 1;
                "PASS"
            } else {
                n_fail += 1;
                "FAIL"
            };
            eprintln!(
                "  {status} {:<34} OCHRE={:>10.2}  HARES={:>10.2}  {}",
                c.name, c.ochre, c.hares, c.note
            );
        }
        eprintln!("\n  Total: {n_pass} pass, {n_fail} fail, {n_missing} missing");

        // Hard physical-bounds assertions.
        let (ind_mn, ind_mx) = hares_indoor_temp
            .iter()
            .copied()
            .filter(|t| t.is_finite())
            .fold((f64::INFINITY, f64::NEG_INFINITY), |(mn, mx), t| {
                (mn.min(t), mx.max(t))
            });
        assert!(
            ind_mn > -30.0 && ind_mx < 70.0,
            "Indoor temperature out of physical bounds: [{ind_mn:.1}, {ind_mx:.1}] C"
        );

        let (att_mn, att_mx) = hares_attic_temp
            .iter()
            .copied()
            .filter(|t| t.is_finite())
            .fold((f64::INFINITY, f64::NEG_INFINITY), |(mn, mx), t| {
                (mn.min(t), mx.max(t))
            });
        assert!(
            att_mn > -40.0 && att_mx < 90.0,
            "Attic temperature out of physical bounds: [{att_mn:.1}, {att_mx:.1}] C"
        );

        // Tolerance assertions — widen these until we verify envelope physics.
        let failed: Vec<&Check> = checks.iter().filter(|c| !c.passed).collect();
        if !failed.is_empty() {
            let msg: Vec<String> = failed.iter().map(|c| c.note.clone()).collect();
            panic!(
                "{} freefloat oracle check(s) exceeded tolerance for scenario '{scenario}':\n  {}",
                failed.len(),
                msg.join("\n  ")
            );
        }
    }

    #[test]
    fn freefloat_spring_72h() {
        run_freefloat_scenario("beopt_spring_72h");
    }

    #[test]
    fn freefloat_summer_48h() {
        run_freefloat_scenario("beopt_summer_48h");
    }

    #[test]
    fn freefloat_winter_48h() {
        run_freefloat_scenario("beopt_winter_48h");
    }
}
