[package]
name = "hares-fleet"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[features]
check_invariants = []
observe = []

[dependencies]
hares-core = { workspace = true }
hares-io = { workspace = true }
hares-types = { workspace = true }
rayon = { workspace = true }
tracing = { workspace = true }
arrow = { workspace = true }
chrono = { workspace = true }
thiserror = { workspace = true }

[dev-dependencies]
parquet = { workspace = true }
tempfile = { workspace = true }
