#!/usr/bin/env bash
set -euo pipefail

# check_ocv.sh — Verify that hardcoded OCV/U_neg tables in ocv.rs match
# the values generated by gen_ocv.py.
#
# Usage: ./scripts/check_ocv.sh
#   Fails with exit code 1 if the generated values diverge from the hardcoded
#   values, printing a unified diff.

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"

OCV_RS="$REPO_ROOT/crates/hares-equipment/src/battery/ocv.rs"
GEN_OCV_PY="$REPO_ROOT/scripts/gen_ocv.py"

if [ ! -f "$OCV_RS" ]; then
    echo "ERROR: ocv.rs not found at $OCV_RS"
    exit 1
fi

if [ ! -f "$GEN_OCV_PY" ]; then
    echo "ERROR: gen_ocv.py not found at $GEN_OCV_PY"
    exit 1
fi

TMPDIR="$(mktemp -d)"
trap 'rm -rf "$TMPDIR"' EXIT

# --- Generate the Rust output ---
echo "Running gen_ocv.py..."
cd "$REPO_ROOT"

uv run python "$GEN_OCV_PY" > "$TMPDIR/gen_ocv_output.txt" 2>&1 || {
    echo "ERROR: gen_ocv.py failed"
    if grep -q "ModuleNotFoundError.*pybamm" "$TMPDIR/gen_ocv_output.txt"; then
        echo "PyBaMM is not installed. Install it for gen_ocv.py CI checks:"
        echo "  uv sync --extra pybamm"
        echo "Or with the pinned version:"
        echo "  uv pip install -r scripts/pybamm-requirements.txt"
    else
        cat "$TMPDIR/gen_ocv_output.txt"
    fi
    exit 1
}

echo "Extracting vec![] blocks from generated output..."

# --- Extract generated vec![] values as single-line comma-separated lists ---
# gen_ocv.py emits labels in the format: "    voltage_v: vec![2.500000, ...],"
# and "    u_neg_v: vec![1.105436, ...],"
# We extract each label and its float values into separate files.

extract_py_vec() {
    local label="$1"   # e.g. "voltage_v" or "u_neg_v"
    local input="$2"
    local output="$3"
    local nth="${4:-1}" # 1-based occurrence index (NMC=1, LFP=2, NCA=3, LTO=4)
    # gen_ocv.py always emits single-line vec blocks:
    #     voltage_v: vec![2.500000, 2.862492, ...],
    # Extract the nth occurrence of "{label}: vec![...],"
    awk -v lbl="$label" -v nth="$nth" '
        $0 ~ "^    " lbl ": vec!\\[" {
            count++
            if (count == nth) {
                if (match($0, /vec!\[.*\]/)) {
                    vec_content = substr($0, RSTART+5, RLENGTH-6)
                    gsub(/[ \t]/, "", vec_content)
                    sub(/,$/, "", vec_content)
                    printf "%s\n", vec_content
                }
            }
        }
    ' "$input" > "$output"
}

# --- Extract hardcoded vec![] values from ocv.rs ---
extract_rs_vec() {
    local label="$1"   # e.g. "voltage_v" or "potential_v"
    local input="$2"
    local output="$3"
    local nth="${4:-1}" # 1-based occurrence index
    # ocv.rs has multi-line vec blocks. Extract the nth occurrence.
    awk -v lbl="$label" -v nth="$nth" '
        $0 ~ "^[[:space:]]*" lbl ": vec!\\[" {
            count++
            if (count == nth) {
                capture = 1
                if (match($0, /vec!\[(.*)/)) {
                    rest = substr($0, RSTART+RLENGTH)
                    printf "%s", rest
                }
                next
            }
        }
        capture {
            if ($0 ~ /^[[:space:]]*\],/) {
                capture = 0
                printf "\n"
                exit
            } else {
                printf "%s", $0
            }
        }
    ' "$input" | sed 's/[[:space:]]//g; s/,$//' > "$output"
}

# Chemistries to check (in order of generation)
CHEMISTRIES="NMC LFP NCA LTO"

# Occurrence indices for each chemistry in gen_ocv.py output and ocv.rs.
# OCV: both Python and Rust have 4 blocks in fixed order (NMC, LFP, NCA, LTO).
# U_neg (Python): 4 blocks in same order (gen_ocv.py emits per-chemistry U_neg).
# U_neg (Rust): only 2 unique tables — UNegTable::for_chemistry dispatches LFP
#   and NCA to default_li_nmc(), so the Rust potential_v block indices are
#   NMC=1, LTO=2, with LFP and NCA sharing NMC's block (index 1).
# Because each PyBaMM parameter set may produce different graphite U_neg curves,
# we skip U_neg comparison for chemistries that share a table in the Rust model
# (LFP and NCA), and only compare the two chemistries with dedicated tables.
for chem in $CHEMISTRIES; do
    case "$chem" in
        NMC) idx=1; uneg_rs=1; skip_uneg=0 ;;
        LFP) idx=2; uneg_rs=1; skip_uneg=1 ;;
        NCA) idx=3; uneg_rs=1; skip_uneg=1 ;;
        LTO) idx=4; uneg_rs=2; skip_uneg=0 ;;
    esac

    # OCV
    extract_py_vec "voltage_v" "$TMPDIR/gen_ocv_output.txt" "$TMPDIR/gen_${chem}_ocv.txt" "$idx"
    extract_rs_vec "voltage_v" "$OCV_RS" "$TMPDIR/rs_${chem}_ocv.txt" "$idx"

    # U_neg — skip for chemistries whose table is shared in ocv.rs
    if [ "$skip_uneg" -eq 1 ]; then
        echo "  [SKIP] $chem U_neg (UNegTable::for_chemistry shares NMC's graphite curve; $chem has no dedicated hardcoded table)"
        continue
    fi
    extract_py_vec "u_neg_v" "$TMPDIR/gen_ocv_output.txt" "$TMPDIR/gen_${chem}_uneg.txt" "$idx"
    extract_rs_vec "potential_v" "$OCV_RS" "$TMPDIR/rs_${chem}_uneg.txt" "$uneg_rs"
done

# --- Compare ---
DIFF_FOUND=0

compare_block() {
    local name="$1"          # e.g. "NMC OCV"
    local gen_file="$2"
    local rs_file="$3"

    if [ ! -s "$gen_file" ]; then
        echo "ERROR: no generated output found for $name"
        DIFF_FOUND=1
        return
    fi
    if [ ! -s "$rs_file" ]; then
        echo "ERROR: no hardcoded table found in ocv.rs for $name"
        DIFF_FOUND=1
        return
    fi

    # Read the (potentially multi-line) content into single lines
    gen_values=$(cat "$gen_file")
    rs_values=$(cat "$rs_file")

    # Normalize: strip leading/trailing whitespace, collapse spaces
    gen_norm=$(echo "$gen_values" | tr -d '[:space:]')
    rs_norm=$(echo "$rs_values" | tr -d '[:space:]')

    if [ "$gen_norm" != "$rs_norm" ]; then
        echo ""
        echo "--- MISMATCH: $name ---"
        echo "Generated values differ from hardcoded values in ocv.rs."
        echo ""
        echo "--- generated (gen_ocv.py) ---"
        echo "$gen_values"
        echo ""
        echo "--- hardcoded (ocv.rs) ---"
        echo "$rs_values"
        echo ""
        echo "To fix: re-run 'gen_ocv.py', copy the updated vec![] blocks into ocv.rs,"
        echo "and commit the changes."
        DIFF_FOUND=1
    else
        echo "  [OK] $name"
    fi
}

for chem in $CHEMISTRIES; do
    compare_block "$chem OCV" "$TMPDIR/gen_${chem}_ocv.txt" "$TMPDIR/rs_${chem}_ocv.txt"
    # U_neg: skip chemistries whose table is shared by UNegTable::for_chemistry
    case "$chem" in
        LFP|NCA) ;;  # intentionally share NMC's graphite curve — no dedicated table
        *) compare_block "$chem U_neg" "$TMPDIR/gen_${chem}_uneg.txt" "$TMPDIR/rs_${chem}_uneg.txt" ;;
    esac
done

if [ "$DIFF_FOUND" -ne 0 ]; then
    echo ""
    echo "FAIL: OCV tables in ocv.rs are out of sync with gen_ocv.py output."
    echo "Run 'uv run python scripts/gen_ocv.py' and update ocv.rs."
    exit 1
fi

echo ""
echo "PASS: All OCV/U_neg tables match gen_ocv.py output."
exit 0
