[package]
name = "hares-equipment"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
hares-types = { workspace = true }
hares-physics = { workspace = true }
hares-control = { workspace = true }
rand = { workspace = true }
rand_chacha = { workspace = true }
serde = { workspace = true }
thiserror = { workspace = true }
postcard = { workspace = true }
crc = { workspace = true }
chrono = { workspace = true }
tracing = { workspace = true }
parquet = { workspace = true }
arrow = { workspace = true }

serde_json = { workspace = true }
uom = { workspace = true }

[features]
observe = []
check_invariants = []

[dev-dependencies]
proptest = { workspace = true }
